### ISSUE TITLE
DSW Editor features

### ISSUE THREAD

**Issue by aderidder** [ds-wizard/ds-wizard#121]
Hi,
I've been playing around with the editor for a while now and here are some features I think would be useful. 

1. Add some way to add links
      - I need to be able to point users to other pages where they can find more information
2. Multi-select / checkbox question type
      - In some cases I now need to create a repeating group, e.g. "Please indicate for whom this research may be of intereset"
3. Move question up/down the hierarchy
      - Sometimes I create a question and later it is decided it needs to be somewhere else. It would be really useful if I could move it, instead of having to create it anew, especially if the question you want to move has a lot of follow-up questions. 
4. Add some way to customise styling
      - I would really like to be able to add something in e.g. bold/italic
5. Clone questions
      - This would be extremely useful with the repeating items as in some cases the follow-up questions are relevant for multiple items. Especially in combination with the previous move questions items feature. 
6. Logic to copy answers to a different chapter
      - Probably a bit complicated, but would be useful if you could use the answers as input to other questions and/or also insert the answer as an answer somewhere
7. Add a Yes/No Question Type. 
      - I think there are a lot of questions that will have Yes/No as possible answers. It would maybe be useful to just have a type which creates this. As a user I could still add extra options / explanations, but it just saves a lot of work.
8. The "Text" box has a default text, which is actual text. The issue here is that if you don't really pay attention, you end up with that text. I think it would be better if:
      - You change the name of the box to "Question Text" and remove the content. In that case, if someone does not enter text, he is simply notified that something has to ben entered into the mandatory field.
      - Actually I just noticed this is #113 
9. Provide functionality to upload a document
      - You could e.g. attach this to the generated pdf in the future. An example would be for a user to provide a blank informed consent form
10. I can export the model, but can I also import it? I think I would in that case build some parts of the model in perhaps vi, as I could maybe just copy some of the repeated questions.
11. Add some more information. In the editor there's this "References" field I can enter as well as an "Experts" field. But when I open the actual questionnaire this information is nowhere to be found. How should I use these fields?

Cheers,
Sander

**Comment by janslifka** [comment]
Hello, thanks for the suggestions!

Some of them are almost possible or planned:

Add 1. We have almost ready new references where you can choose URL reference type and insert a URL.

Add 8. Yes, the Text field for questions should be optional.

Add 10. Well, this is possible but with a different set of permissions than the default one for the demo instance. We decided to do it this way because once you have the permission to manipulate with the KM packages, you could really mess up the portal.

Add 11. This will definitely be visible in the questionnaire.


The others are nice suggestions and may be planned in the future. I'll move this to Ideas for now.

**Comment by touwwouter** [comment]
12. Expand/collapse all questions/answers in the hierarchy with a single click.

**Comment by rwwh** [comment]
3. is one reason why I still use "vi" and my mind map to edit the knowledge model...

**Comment by MarekSuchanek** [comment]
1. Already implemented
2. Can be done using "list" question in combination with "option" question. (checkboxes are being discussed often)
3. Already implemented
4. Already implemented - markdown in descriptions
5. Already implemented
6. Duplication of questions usually means bad questionnaire design and should be avoided.
7. In backlog - https://ds-wizard.atlassian.net/browse/DSW-546
8. Already implemented
9. This (document composition) is out of scope, but if it is part of some DMP template, it can be easily done in template using Jinja2...
10. Yes (already answered)
11. Already implemented
12. Already implemented
