### ISSUE TITLE
Create URL for KM Entities

### ISSUE THREAD

**Issue by janslifka** [ds-wizard/ds-wizard#127]
Create URL for every KM entity, e.g.:

```
/{packageId}/question/{uuid}
```

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#2)](https://ideas.ds-wizard.org/posts/2/browsing-km-in-registry-with-persistent-urls)

You can vote for this feature and discuss it there.
