### ISSUE TITLE
Editor 2.0

### ISSUE THREAD

**Issue by vknaisl** [ds-wizard/ds-wizard#137]
The current editor is very interactive but it could do more.

### Possible improvements:
- [ ] suggest predefined experts (list of experts should be edited in UI)
- [ ] suggest predefined metrics (list of experts should be edited in UI)
- [ ] edit predefined metrics
- [ ] edit predefined phases
- [ ] suggest predefined book's references (list of book references should be edited in UI)
- [x] a user should be able to move some question to another part of the knowledge model ([Jira Link](https://ds-wizard.atlassian.net/browse/DSW-127))
- [x] a user should be able to see a preview of the knowledge model ([Jira Link](https://ds-wizard.atlassian.net/browse/DSW-152))

**Comment by MarekSuchanek** [comment]
Metrics: https://ideas.ds-wizard.org/posts/8/configurable-metrics
Phases: https://ideas.ds-wizard.org/posts/9/configurable-phases
Experts: https://ideas.ds-wizard.org/posts/12/define-experts-on-km-globally
