### ISSUE TITLE
Knowledge Model Management 2.0

### ISSUE THREAD

**Issue by vknaisl** [ds-wizard/ds-wizard#138]
Currently, the managing of knowledge models in the application is very simple.

The Knowledge Model is folded from followed-up packages. If we want to export all knowledge model, we have to export all these packages. 

### Suggested improvements: 
- A more advanced import process 
    - A user should be able to see what will be imported
    - The importing package will be validated also on the client side
    - A user should be able to see what importing packages are already in the system
- New Knowledge Model Detail
    - More nice and descriptive Knowledge Model detail
    - We should show in some graphic from what is KM made from (what parent packages,..)

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#11)](https://ideas.ds-wizard.org/posts/11/improved-detailed-knowledge-model-import)

You can vote for this feature and discuss it there.
