### ISSUE TITLE
Knowledge Model Registry

### ISSUE THREAD

**Issue by vknaisl** [ds-wizard/ds-wizard#139]
As ubuntu-like systems have `apt`, MacOS system has `homebrew`, Python has `pip`, Docker has `Docker Registry`, we should provide something similar to provide users easier way how to share their Knowledge Models across DSW instances - the `Knowledge Model Registry (KM Registry)`.

Our approach is to create a general knowledge model which would cover all problems of creating data management plans. As this knowledge model will evolve, with KM Registry we could easily share new versions with other users with their own instances. They would just pull it in their instances from the registry.

So KM Registry should have these features:
- allow uploading your knowledge model
- allow searching other knowledge models shared by other users

**Comment by MarekSuchanek** [comment]
Downloading already implemented, uploading/publishing in Jira https://ds-wizard.atlassian.net/browse/DSW-641
