### ISSUE TITLE
Suggest common answers in questionnaire

### ISSUE THREAD

**Issue by rwwh** [ds-wizard/ds-wizard#143]
As a user filling in a DMP it would be useful if some of the information on a database or repository that is always the same could be pre-filled if the database/repository is recognized by the system (it is an URI? FAIR?)

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#6)](https://ideas.ds-wizard.org/posts/6/suggest-common-answers-in-questionnaire)

You can vote for this feature and discuss it there.
