### ISSUE TITLE
RDF encoding of KM and Questionnaires

### ISSUE THREAD

**Issue by vknaisl** [ds-wizard/ds-wizard#146]

**Comment by MarekSuchanek** [comment]
There are multiple levels for ontology and RDFs:

- L1: Develop an ontology describing the KM metamodel (OWL)
- L2: Allow export/import of (compiled) KM in RDF/JSON-LD/OWL (as instance of L1 ontology)
- L3: Allow export/import of questionnaire in RDF/JSON-LD (as instance of L2 ontology)

We could also incorporate predefined terms from vocabularies such as Schema.org, FOAF, Dublin Core, etc. the L1 and L2 ontologies as suggested in #39

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#15)](https://ideas.ds-wizard.org/posts/15/rdf-encoding-of-km-and-questionnaires)

You can vote for this feature and discuss it there.
