### ISSUE TITLE
Disable registration and/or require approval

### ISSUE THREAD

**Issue by MarekSuchanek** [ds-wizard/ds-wizard#149]
Some organization might want to have own instance accessible from internet but forbid to register for "public". There should be a way how to disable registration (users will be created manually or by some direct import to DB, maybe sync in the future) and/or require administrator to confirm registration of a new user before the account can be used to login.

**Comment by vknaisl** [comment]
Will be done in https://ds-wizard.atlassian.net/browse/DSW-310
