### ISSUE TITLE
Registration email configuration

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#151]
As far as I can tell, the text of the registration email is set in lib/Service/Mail/Mailer.hs. Would be great if there can be a separate template file instead, allowing for easier changes.

**Comment by janslifka** [comment]
Hello, thanks for the feedback.

We are now working on configurable email templates, and it should be out with the next release (planned on 10th of March). You can see the progress in our JIRA - https://ds-wizard.atlassian.net/browse/DSW-199.

**Comment by MarekSuchanek** [comment]
This is done and released since `1.4.0`
