### ISSUE TITLE
Documentation for build version/date for server and client

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#152]
In the about window, there is a list of dates and versions for the client and server. Would be great if it could be documented how those values can be changed. It could be also be useful if they were updated automatically.

I was able to find config/build-info.cfg for the server, but can only find how to do it directly in the code for the client.

**Comment by vknaisl** [comment]
Hello Linus,

All version values are automatically updated in CI. CI runs a script `scripts/build-info.sh` which generate an app version and a built date based on several conditions (you can check this script).

If you want to change the values manually, you can do it:
- in server: `config/build-info.cfg`
- in client: `src/elm/Common/Menu/Models.elm`.

If you have any other questions, please let us know!

Vojtech

**Comment by talavis** [comment]
I really think you should update your documentation about that. I was able to follow your installation instructions and ended up with outdated (server) or unset (client) build info.

**Comment by vknaisl** [comment]
We updated client and server READMEs so it should be more clear now
