### ISSUE TITLE
Trouble loading the Public Questionaire example

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#153]
I'm unable to load the provided public-questionnaire.json file. I can load it into the database by changing the date lines into defined dates (e.g. "createdAt" : ISODate("2019-02-12T00:00:00Z")), but even when loaded they do not show up anywhere in the system (though they are present in the db). Would be great if you can document what else is needed.

**Comment by vknaisl** [comment]
Can you please share a screen what happens when you import it to the database? 

It should work out of the box. You don't have to edit anything.

**Comment by talavis** [comment]
Screenshot at http://talavis.eu/uu/Screenshot_20190227_142253.png

**Comment by vknaisl** [comment]
I see you have a problem with importing public questionnaire into a database. That's probably the reason why you don't see the public questionnaire. Do you import the file well? Do you have the right version of MongoDB?

**Comment by talavis** [comment]
Works with latest version.
