### ISSUE TITLE
Change visibility of a questionnaire

### ISSUE THREAD

**Issue by nicjar** [ds-wizard/ds-wizard#154]
I can't find if it is possible to change the visibility of a questionnaire after it is created, but I think it is a needed feature. I believe a common scenario is that you start out with a private questionnaires that you later make public for others to view.

**Comment by vknaisl** [comment]
Good idea. We put it into the backlog. You can watch progress of the issue here: https://ds-wizard.atlassian.net/browse/DSW-242

**Comment by MarekSuchanek** [comment]
This has been already implemented (issue in JIRA is done)...
