### ISSUE TITLE
Questionnaire visibility and edit rights

### ISSUE THREAD

**Issue by nicjar** [ds-wizard/ds-wizard#155]
The current access rights model makes anything that has _Public_ visibility editable by all. Correct?
I don't think this is good, and is not what most users would expect. The default should be that you can only edit your own questionnaires, regardless if they are _Private_ or _Public_. I think this is really important for getting adoption of the DSW as a tool.

**Comment by vknaisl** [comment]
Yes, we know! We are planning to do proper access rights and permissions. We have an issue on it (https://github.com/ds-wizard/ds-wizard/issues/136). Please watch this issue for future progress.
