### ISSUE TITLE
Is the configuration page outdated?

### ISSUE THREAD

**Issue by aderidder** [ds-wizard/ds-wizard#156]
Hi,

I'm trying to deploy the newest version of the software based on the manual pages [installation](https://docs.ds-wizard.org/installation) and [configuration](https://docs.ds-wizard.org/configuration). When using the specified example app-config.cfg, the dsw_server fails to start, with the docker-compose log telling: 

> [Error] CONFIG: NoOption "servicetoken"

There is no mention of this servicetoken parameter on the manual pages. However, if I add it to the app-config, I get a new error, telling me:

> [Error] CONFIG: NoSection "Messaging"

Which isn't mentioned on the manual pages either. Is the configuration page outdated?

Cheers,
Sander

**Comment by MarekSuchanek** [comment]
Hello Sander,

it is true, the documentation was a bit outdated regarding this... We somehow did not include adding _server worker_ and `messaging queue` in it.

It is fixed now, thanks for reporting! I've also improved other documentation of the configuration... Let me know if it works for you now.

Best regards,
Marek

**Comment by aderidder** [comment]
Hi Marek,

Ok thanks! 
Using the new example app-config, the next encountered error is:

> [Error] CONFIG: ParseError "couldn't parse value  from (Mail/port)"

If I give it some random value, the next one is:

> [Error] CONFIG: ParseError "couldn't parse bool  from (Mail/ssl)"

So it looks like these values are parsed even though the enabled flag for mail is set to false.

After setting that parameter to false, dsw_server's log reports:

> dsw_server_1  | [Warn] MESSAGING: failed to connect to the message broker - retry #5 in 32.0 seconds
> dsw_server_1  | [Error] MESSAGING: failed to connect to the message broker
> dsw_server_1  | dsw-server: ConnectionClosedException Abnormal "Handshake failed. Please check the RabbitMQ logs for more information"

So, looking at the rabbitmq log, the issue seems to be:

> rabbitmq_1    | PLAIN login refused: user '' attempted to log in with a blank password, which is prohibited by the internal authN backend. To use TLS/x509 certificate-based authentication, see the rabbitmq_auth_mechanism_ssl plugin and configure the client to use the EXTERNAL authentication  mechanism. Alternatively change the password for the user to be non-blank.

Apparently it's unhappy with the empty username and password in the Messaging section in the app-config?

By the way, I'm currently testing all of this on CentOS 7 and I've disabled SELinux at the moment, since I'm not sure whether that complicates things even further. I'll probably give it all another shot with SELinux enabled once I get it up and running.

Cheers,
Sander

**Comment by MarekSuchanek** [comment]
Yes, the problem with `Mail` config seems to be a bug - I will investigate and incorporate a fix in the following release (1.4.0) which will be soon.

Regarding MQ, we indeed use only the PLAIN SASL mechanism which requires `username` and `password` to be set to something. I mentioned it in the documentation and we will consider extending it to allow other mechanisms with @vknaisl.

**Comment by aderidder** [comment]
Ok I set the username and password to guest for MQ and everything seems to be working now, thanks!
Should I close this call or would you like to keep it open because of the Bug tag?

**Comment by MarekSuchanek** [comment]
Yes, please do not close this issue - I will close it when we finish https://ds-wizard.atlassian.net/browse/DSW-243

**Comment by MarekSuchanek** [comment]
@aderidder, fixed in `v1.4` which is [released](https://github.com/ds-wizard/dsw-server/releases/tag/v1.4.0)

Just be aware, that this version contains changes that make knowledge models (as well as created editors and questionnaires) incompatible and migrations will purge them. If you need help with that, feel free to contact me.
