### ISSUE TITLE
Questionnaire Migration 2.0

### ISSUE THREAD

**Issue by vknaisl** [ds-wizard/ds-wizard#161]
- More intelligent migration between IntegrationQuestionType and ValueQuestionType question (could be done without losing any data)
- Change tags during migration process

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#14)](https://ideas.ds-wizard.org/posts/14/improve-questionnaire-migration)

You can vote for this feature and discuss it there.
