### ISSUE TITLE
"Error in $[0][25]: Unsupported question value type" on KM import

### ISSUE THREAD

**Issue by pcorrigan** [ds-wizard/ds-wizard#162]
I want to import a KM on my local installation, but receive the message:
"Error in $[0][25]: Unsupported question value type
when I try to import for example dsw:root:1.4.0 Common DSW Knowledge Model

I am running a recent docker version and am logged in with the DATASTEWARD role.

**Comment by vknaisl** [comment]
Hello Peter,

can you please specify what version of DSW are you running? Are you importing the Knowledge Model from the DSW Registry [1] or from a file?

We recommend importing Knowledge Models from DSW Registry. You can easily receive updates and it's simpler. For importing Knowledge Model from DSW Registry, please follow these steps from our docs [2].

Have a great day!

[1] https://registry.ds-wizard.org
[2] https://docs.ds-wizard.org/en/latest/admin/installation.html#registry

**Comment by pcorrigan** [comment]
Hi Vojtech,
Thanks for your speedy response. I was using 1.7.0 and had not updated the token. I've upgraded to 1.8 and installed the token. I was able to import from a file exported from the demo server https://demo.ds-wizard.org
Best wishes
Peter
