### ISSUE TITLE
Entity does not exist (organization: nothing)

### ISSUE THREAD

**Issue by pcorrigan** [ds-wizard/ds-wizard#165]
When logged in as an Admin if I select Organisation or the KM Editor from the side menu I get the error: `Entity does not exist (organization: nothing)`. How do I set the Organisation?
Thanks for any assistance.

**Comment by MarekSuchanek** [comment]
Hello, it seems that you somehow removed organization from the database directly (Wizard does not deletes organizations from DB itself). Do you know what happened?

Now you will have to start over (if you have fresh installation, just purge DB) or insert organization manually (collection `organizations`):

```js
{
    "uuid" : "<random uuid>",
    "name" : "name",
    "organizationId" : "id",
    "createdAt" : ISODate("2019-06-26T17:00:00.000Z"),
    "updatedAt" : ISODate("2019-06-26T17:00:00.000Z")
}
```

**Comment by pcorrigan** [comment]
Thanks Marek,
>Do you know what happened?
I'm not sure how organization was deleted. Could it be that organization
was never created if I started with an earlier version of the app and did
not update the db? Anyway will update the db as instructed.
Thanks for your help.
Peter

**Comment by MarekSuchanek** [comment]
It is weird, because organization entity is there since the very beginning and in case of update, automatic database migrations updates what is necessary. Please, let me then know if you managed to solve this.

**Comment by pcorrigan** [comment]
Hi Marek,
When I inserted organization manually, it appears to work OK and both
Organization and KM Editor menus appear to function correctly.
Thanks for your help.
Peter

Peter Corrigan,
Head of Digital Publishing & Innovation,
James Hardiman Library,
National University of Ireland, Galway.
Tel +353-87-2798505
peter.corrigan@nuigalway.ie

**Comment by MarekSuchanek** [comment]
Great 👍 glad it is working now! (closing the issue)

Best regards,
Marek
