### ISSUE TITLE
Enable Keyboard Control

### ISSUE THREAD

**Issue by matu3ba** [ds-wizard/ds-wizard#166]
Currently I need to click everything.
A basic keyboard control, by focus on which field the user is, would be great.
Jumping through each field does not work properly.
Standard controls would be up,down,left,right,delete,tab,enter and optionally escape.

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#13)](https://ideas.ds-wizard.org/posts/13/enable-keyboard-control)

You can vote for this feature and discuss it there.
