### ISSUE TITLE
Metadata to model and questionnaire

### ISSUE THREAD

**Issue by matu3ba** [ds-wizard/ds-wizard#168]
More information like tagging, referred standard/paper by DOI etc would be great.
Not sure what the easiest solution would be there, so if presentation/import of .bib file entries would be a good solution.

**Comment by vknaisl** [comment]
Hello matu3ba,

I am a little bit confused. Is it more ideas pack in one issue?

_"More information like tagging, referred standard/paper by DOI etc would be great."_
- I identify that it would be nice to have more references in the Knowledge Model. Currently, you can add a reference to standards and papers through URL. Do you suggest to create a new type of reference where you would put just DOI?

_"Not sure what the easiest solution would be there, so if presentation/import of .bib file entries would be a good solution."_
- Can you please more specify how it should work?

Vojtech

**Comment by MarekSuchanek** [comment]
We would need more information but questions can use references including DOI as URL and tags are also already implemented.
