### ISSUE TITLE
Missing configuration settings in documentation

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#169]
There is no information in the documentation nor configuration sample about `enabled: true` being required for integration of the reqistry in dsw.

Further I wonder how you activated the "questionnaire listing" on the start page that is present in the demo instance.

**Comment by MarekSuchanek** [comment]
Hello, thanks for report, docs improved: https://docs.ds-wizard.org/en/latest/admin/configuration.html#registry

Regarding the listing, it is our experimental feature and therefore it is not documented.
