### ISSUE TITLE
In Docker server setup import of public questions fails

### ISSUE THREAD

**Issue by matu3ba** [ds-wizard/ds-wizard#171]
Dear Developers of Data Stewardship Wizard,

I am trying to setup the server for the Data Stewardship Wizard
for local testing purposes in a docker container
as described in https://docs.ds-wizard.org/en/latest/admin/installation.html#via-docker.
In step 5 I should run the server, but apparantly question import is needed.
I am running docker with `sudo dockerd` and I am using manjaro including beforehand installed packages, including mongodb-bin from AUR.
[However installed packages should not interfer.]

`$ docker-compose run dsw_server`
...
[Warn] DATABASE: failed to connect to the database - retry #1 in 2.0 seconds.
...

The command for importing the default questions is described here, but I am unsure about the collection syntax.
https://stackoverflow.com/questions/49895447/i-want-to-execute-mongoimport-on-a-docker-container.
$ `mongoimport -d <db-name> -c <c-name> --file xxx.json`

I tried so far (from the deployment example)
$ `docker exec -it dsw-deployment-example_dsw_server_1 mongo`
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"mongo\": executable file not found in $PATH": unknown

`# docker exec -it dsw-deployment-example_dsw_server_1 sh`
`# cd /tmp`
`# mongoimport -db dsw-server --collection publicPackages --file public-package-root-1.0.0.json`
019-07-31T11:34:59.250+0200    error validating settings: incompatible options: --file and positional argument(s)
2019-07-31T11:34:59.250+0200    try 'mongoimport --help' for more information

`# mongoimport -db dsw-deployment-example_dsw_server_1 --collection publicPackages --file public-package-root-1.0.0.json`
2019-07-31T11:36:00.261+0200    error validating settings: incompatible options: --file and positional argument(s)
2019-07-31T11:36:00.261+0200    try 'mongoimport --help' for more information

Do I need to manually setup a mongo database etc or what steps am I missing?
There seems to be a created dsw-deployment-example_mongo_1.
Could you provide the additional steps for the server setup to the documentation?

**Comment by janslifka** [comment]
Hello,

I think the problem is in the command:

```
$ docker-compose run dsw_server
```
Because this one starts the server only. However, as you can see in the docker-compose file, you also need other containers to run (e.g. mongo). So it seems to me that it can't connect to mongo because it is not running at all. (You can quickly check that with `docker-compose ps`).

Can you try starting all the containers with the following command?

```
$ docker-compose up -d
```

**Comment by matu3ba** [comment]
Hey,
`# docker ps`
states all containers are running.
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                             PORTS                    NAMES
601e63088720        datastewardshipwizard/client:1.8.1   "/start.sh"              5 days ago          Up 13 minutes                      0.0.0.0:8080->80/tcp     dsw-deployment-example_dsw_client_1
4da989630f7a        datastewardshipwizard/crontab        "/docker-entrypoint …"   5 days ago          Up 13 minutes (healthy)                                     dsw-deployment-example_dsw_server_worker_1
6d4e0093de6f        mongo:3.0.15                         "docker-entrypoint.s…"   5 days ago          Restarting (139) 15 seconds ago                             dsw-deployment-example_mongo_1
e60d6871c1e8        datastewardshipwizard/server:1.8.0   "./dsw-server"           5 days ago          Up 47 seconds (health: starting)   0.0.0.0:3000->3000/tcp   dsw-deployment-example_dsw_server_1

The server and database keep restarting.

**Comment by matu3ba** [comment]
The default deployment example, more specific the mongodb image, is broken.
https://github.com/docker-library/mongo/issues/245

Change 
mongo:
      image: mongo
and it works.
I now need to get the GUI running...

**Comment by matu3ba** [comment]
Oh, wow. Would be great to know what port to ask in the manual.
http://localhost:8080/
works getting data from the client.

**Comment by janslifka** [comment]
Thanks for reporting the issue, we'll update mongo with the next version.
