### ISSUE TITLE
Inconsistency in default settings for email

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#172]
The current (1.9.0) default settings for email is `port=465` (used for ssl connection) and `ssl=false`. 

Wouldn't it make more sense to either set `ssl=true` or `port=25`?

**Comment by vknaisl** [comment]
Make sense! Thanks for the feedback! I create an issue from that. You can watch the progress here - https://ds-wizard.atlassian.net/browse/DSW-471

**Comment by vknaisl** [comment]
Implemented. It will be released in the next version (2.3.0) 🎉
