### ISSUE TITLE
Permissions dont change after Role Change

### ISSUE THREAD

**Issue by rimatzki-gfz-potsdam** [ds-wizard/ds-wizard#174]
When changing a users role to ADMIN from DATA STEWARD the entries in the DB are changed, but in the frontend the user still has no way to access User Management or Organization Management. 

User Overview (Opened with another Account)
![User Overview](https://user-images.githubusercontent.com/53825887/63428935-0d6d3c80-c419-11e9-8ef0-7838f66fe6db.jpg)

User's View of the Sidebar:
![Admin Overview](https://user-images.githubusercontent.com/53825887/63428985-2d9cfb80-c419-11e9-89b2-054d627a5998.jpg)

DB reading:
{ "_id" : ObjectId("5d5d29cda5cf630001000000"), "uuid" : "af0c0997-aa36-437c-aede-7326a5668c7f", "name" : "Jonas", "surname" : "||||||||||||||||||||||||", "email" : "|||||||||||||||||||||||||||||||", "passwordHash" : "||||||||||||||||||||||||||||||||", "role" : "ADMIN", "permissions" : [ "UM_PERM, ORG_PERM", "KM_PERM", "KM_UPGRADE_PERM", "KM_PUBLISH_PERM", "PM_READ_PERM", "PM_WRITE_PERM", "QTN_PERM", "DMP_PERM" ], "active" : true, "createdAt" : ISODate("2019-08-21T11:23:57.298Z"), "updatedAt" : ISODate("2019-08-21T11:24:54.279Z") }

**Comment by vknaisl** [comment]
Hello Jonas,

It is actually not a bug. After you change a role, you need to log out and log in. We know that this is not intuitive at all thus we have an issue which will solve that - see its progress here - https://ds-wizard.atlassian.net/browse/DSW-524.

Vojtech

**Comment by rimatzki-gfz-potsdam** [comment]
Hello Vojtech,
relogging doesnt change anything (with or without emptying the cache), tried restarting via "docker-compose restart", but that didnt solve the issue either. Am I missing something in a config-file possibly?
Jonas

**Comment by vknaisl** [comment]
Hello Jonas,

Which version of the server application do you use?

Vojtech

**Comment by rimatzki-gfz-potsdam** [comment]
Hello Vojtech
datastewardshipwizard/server:1.9.1 is the one i configured in the docker-compose.yml, build-info.yml states version: v1.9.1~055b1a6.
Jonas

**Comment by vknaisl** [comment]
Hello Jonas,

please update to the version `1.9.2`. There was a bug in version `1.9.1` which is already solved. After you upgrade, you have to again change the role of the user. Then the user just logs in and he has his new assigned role.

Sorry for this inconvenience. There was a problem with re-setting permissions. But because I saw the right list of permissions in the database, I thought that this is not the case of the bug. 

Let me know if it works.

Vojtech

**Comment by rimatzki-gfz-potsdam** [comment]
Hello Vojtech,
thanks, that did it.
Jonas
