### ISSUE TITLE
Integration "Unable to get Type Hint"

### ISSUE THREAD

**Issue by rimatzki-gfz-potsdam** [ds-wizard/ds-wizard#175]
Hello,
I am trying to integrate a JSON-API and still get a "Unable to get Type Hint", which I just cant get rid of. The API does nothing more then to provide the following JSON-File:

![JSON_Overview](https://user-images.githubusercontent.com/53825887/63775662-16aa4d80-c8e0-11e9-8489-ed7531256349.jpg)

The Integration is set up the following way:
![Integration_Overview](https://user-images.githubusercontent.com/53825887/63775399-88ce6280-c8df-11e9-9780-4e803c502485.jpg)

There are no Props set or anything, so I simply assign the Integration to the Integration Question, but I still get the Error Message.
Best Regards,
Jonas

**Comment by janslifka** [comment]
Hello,

You should be able to see the request in the server log. If you are running it with docker-compose, just run `docker-compose logs -f`, try to open the type hints, and you should see the request and the error there.

The configuration looks fine at first glance, so I guess there will be some issue when the server is trying to connect to the API. Are you sure the API is accessible from within the docker container? (E.g., if you are using localhost, the localhost in the container is not the same as on your machine.)

So I would suggest looking at the log, and if you are unsure what to do, please send us what you find out in the log.

Best,
Jan

**Comment by rimatzki-gfz-potsdam** [comment]
Hello,
The Logfile shows the following error:
dsw_server_1         | [Error] AesonException "Error in $: expected Map k v, encountered Null"
dsw_server_1         | [Rqst] [U:af0c0997-aa36-437c-aede-7326a5668c7f][T:de4ff61f-c207-4928-adc5-7d376ef6cde9] 500 Internal Server Error POST /typehints
So there seams to be some kind of Null mapping, my guess would be as a key. Cant really tell how, though.

the host is running on a different machine and should be visible without restrictions.
Best,
Jonas

**Comment by vknaisl** [comment]
Hello Jonas,

I tried to simulate it and unfortunately, I found a bug. We will fix in next release. You can watch the progress here [1]. The release should be out at the beginning of September.

Current workaround:
Add some props for integration into `integration.yml` file [2].

Vojtech

[1] https://ds-wizard.atlassian.net/browse/DSW-536
[2] https://docs.ds-wizard.org/en/latest/admin/configuration.html#integration

**Comment by MarekSuchanek** [comment]
This bug has been already fixed (issue in JIRA is done)...
