### ISSUE TITLE
Supress "Content-Type"-Header in API requests

### ISSUE THREAD

**Issue by rimatzki-gfz-potsdam** [ds-wizard/ds-wizard#176]
Hello,
I am still working on setting up an integration. The external API I will be connection to rejects any request including a Content-Type-Header in the request. Is there any way to suppress the automatically addition of "Content-Type: application/octet-stream" as part of the header or is the only option to write a wrapper API? I know I can re-assign another value, but that does not help in my case.
Kind regards,
Jonas

**Comment by vknaisl** [comment]
Hello Jonas,

I am not sure about your question. Do you want to send more headers to your external web service? Or you have a problem with mapping response from external web service into DS Wizard.

Regards.

Vojtech

**Comment by rimatzki-gfz-potsdam** [comment]
Hello Vojtech,
My problem is the Header-Information which is send when Integrating an API into DS Wizard. The web service I am using is rejecting every request send to it with a "Content-Type"-Header. DS Wizard, with an empty Request-Header in the Form used to configure the requests, is sending "Content-Type: application/octet-stream" as part of the request, which then leads to rejection of the Request by the Web Service. I could configure it to be empty, but that would lead to the same result. I either need to find a way to not have DS Wizard send the Content-Type-Header in the request or have to write a wrapper web service for the web service I want to use myself.
Regards,
Jonas

**Comment by vknaisl** [comment]
Hello Jonas,

I changed the DSW to not to send `Content-type` if the request is a `GET` request and it has an empty body. This change will be out in the next release which is planned to this week.

Regards
Vojtech
