### ISSUE TITLE
Template location in 1.10

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#177]
There seems to be some trouble with templates in 1.10.

When I load the default code with `templates` at `dsw-server/dsw-server/templates`, I get the message that templates could not be loaded. If I copy/link the templates folder to `dsw-server/templates` the templates are loaded correctly, so I guess there is some location that needs to be updated in the code.

**Comment by talavis** [comment]
More specifically, the below change seems to fix the problem:
```
diff --git a/dsw-server/lib/Service/Template/TemplateService.hs b/dsw-server/lib/Service/Template/TemplateService.hs
index df0c24f..efac634 100644
--- a/dsw-server/lib/Service/Template/TemplateService.hs
+++ b/dsw-server/lib/Service/Template/TemplateService.hs
@@ -27,7 +27,7 @@ import Service.File.FileService
 import Util.List (foldEithersInContext)
 import Util.Template (mLoadFile)
 
-templateFolder = "templates/dmp"
+templateFolder = "dsw-server/templates/dmp"
 
 listTemplates :: AppContextM (Either AppError [TemplateDTO])
 listTemplates = do
```

**Comment by MarekSuchanek** [comment]
Hello @talavis,

you are running dsw-server using `stack exec dsw-server` from the project's root directory? You need to run the application from directory where `templates` and `config` subfolders are located... If you want to run it from different folder, I suggest to use the symlink as you mentioned.

**Comment by talavis** [comment]
I was indeed running it from the root. As that's where the `stack* ` files are found, I assumed that was where to run it (and I kept on using my systemd definitions from the earlier versions).

Would be great if you can keep a short log for the releases where you note the things that affect me as the person setting up the local system (e.g. the above change and new config options).

**Comment by talavis** [comment]
Would also suggest that you clarify it in the documentation, the current installation instructions skip the information about `dsw-server/dsw-server` (following the commands to copy configuration files etc would lead to errors).

**Comment by MarekSuchanek** [comment]
I will update the documentation and prepare some "How to upgrade" page for the future. Thanks for the issue and suggestions!
