### ISSUE TITLE
Unable to activate users via email link

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#178]
The activation link in the emails sent out for new users by `dsw-server` have stopped working for us.

When a user is added, either via the admin interface or via sign up, the activation email is correctly sent out. However, when the user clicks the link, they are met by the message `{"status":401,"error":"Unauthorized","message":"Unable to get token"}` and the user is not activated. The same problem occurs for password reset emails if the user is activated manually.

This is true for both of our setups, one running 1.9.2 and one running 1.10.0. I do not know when the problem started, as I've not included activating accounts in my standard testing after upgrade.

The two setups are completely separate, existing in different containers and using different databases. The configuration is similar, but with different secrets etc.

I have tried using the configuration from the documentation with only changes changes to the database, client url, and mail system. The same error still occurs.

If the user is enabled manually, they can log in and work normally. The only problem is the link in the emails.

**Comment by MarekSuchanek** [comment]
Hello @talavis. Have you changed the email templates or are you using the default one? Is it running in Docker with images from https://hub.docker.com/r/datastewardshipwizard? How does the activation/recovery link looks like?

It seems odd, because (for both version) in case of our instances there were no problems with account activation nor password recovery. I've just tried it now with the latest version myself. Must be some special edge case or misconfiguration.

**Comment by talavis** [comment]
They are running in separate lxc containers that I've setup myself. The mail template is the default one. The email is generated and provides a link in the style of `<server url>/signup/e8b74d4a-94ab-4f7b-aece-92f5435f477e/2378d56b-31b8-402a-be37-47f9eac33d78`.

I also believe I have done a mistake somewhere, but I really cannot understand where. As noted, I did try the default configuration from the docs and only added the db and mail settings, with the same result.

**Comment by MarekSuchanek** [comment]
There is where the problem might be, it should be `<dsw-client url>/signup/e8b74d4a-94ab-4f7b-aece-92f5435f477e/2378d56b-31b8-402a-be37-47f9eac33d78`. Is you settings of `general > clientUrl` in `application.yml` correct?

**Comment by talavis** [comment]
Thank you for the help. I had messed up the content of the variable I used in ansible, and then I was too blind to see it in the actual config.
