### ISSUE TITLE
External access to questionnaires

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#180]
We would be happy if it was possible to have external links for questionnaires that can be accessed for read-only access.

It would  be useful if the user can set this access independently to the visibility used inside of dsw (i.e. they can make it readable via link, but it won't be visible to other users within dsw).

1. Follow url, e.g. `/questionnaire/<hash>`
2. If not logged in, show log in prompt (or potentially even skip it)
3. Open the questionnaire in read-only mode (unless the user has write permissions)

Use case:
We are intending to create a portal to track datasets. Each dataset must have a dmp. In order to keep the information in the dmp up-to-date, we would like to link to its source rather than upload e.g. a pdf.

**Comment by talavis** [comment]
An alternative for the above: add a setting to give a (trusted) user access to any linked questionnaire.

**Comment by talavis** [comment]
This seems to become more and more urgent for us. It seems most users send a link to their questionnaire rather than exporting it, and to make it feasible we've been forced to make multiple users admin so they can access their users' dmps.

It would truly be great if you would consider adding some kind of middle-way, preferably read-only access for logged-in (special?) users if they have the link.

**Comment by janslifka** [comment]
> This seems to become more and more urgent for us. It seems most users send a link to their questionnaire rather than exporting it, and to make it feasible we've been forced to make multiple users admin so they can access their users' dmps.
> 
> It would truly be great if you would consider adding some kind of middle-way, preferably read-only access for logged-in (special?) users if they have the link.

There is an option to make a questionnaire "Public Read-Only" which makes it visible for all users but only the author is able to edit it. Would that work for your use case?

![image](https://user-images.githubusercontent.com/7797976/75463653-6698c880-5986-11ea-872f-ed4ae541722a.png)

Regarding the redirect after login to the original URL, it doesn't work now. However, we have that planned for the next version in our JIRA (https://ds-wizard.atlassian.net/browse/DSW-610).

**Comment by talavis** [comment]
Not really. The impression we have is that people prefer to not have their dmps readable by everyone, but only by the person who is to evaluate it.

In our instances we have turned off the ability to make public questionnaires to avoid having people doing it by mistake

**Comment by janslifka** [comment]
Ok, I understand the issue. We want to have more advanced permission system. However, it is a complex feature, and we don't have it planned in our roadmap yet, because of the limited resources and other features we need to implement.

I'm not sure if it will be helpful for you but what we want to have soon (in about a month or two) is a possibility to have a public link for the generated documents (they will no longer be one time export, but stay within DSW once generated).

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#3)](https://ideas.ds-wizard.org/posts/3/plans-sharing-collaboration-access-rights)

You can vote for this feature and discuss it there.
