### ISSUE TITLE
"Questionnaire demo" button shows up even if feature "public questionnaire" is disabled.

### ISSUE THREAD

**Issue by rwwh** [ds-wizard/ds-wizard#182]
I pressed the "Questionnaire demo" link in researchers.ds-wizard.org only to find out that that feature is disabled. Probably, disabling the feature should also remove the link from the top menu.

**Comment by vknaisl** [comment]
Hello Rob,

Thanks for reporting the error. You are right. I fixed it in this commit (https://github.com/ds-wizard/engine-backend/commit/251aba14c0959aacd2f54ce08b5a857941293d50). It will be released in the next version.

Vojtech
