### ISSUE TITLE
Configuration setting to add information to front (login) page

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#186]
As the number of users we have keep on increasing, we have more and more users contacting us because they are confused about what DSW actually is.

It would thus be very useful if there was some way of adding information to the login screen, rather than just showing the prompt and sign up button.

In our case, it would be a short explanation of what a DMP is and why it should be created, who we are, and what the system is. It would also include a way to contact us in case of trouble (and thus also solving issue #173).

A very crude mockup of what we mean:
![dsw_frontpage_mockup](https://user-images.githubusercontent.com/310966/74660282-1f485600-5196-11ea-99e4-7c92df942e37.png)

**Comment by talavis** [comment]
Connected to this one: it would it also be great if there was support for adding our own branding (logo) on the front page and also in the system, e.g. in the top or side bar.

**Comment by janslifka** [comment]
Hello Linus

Thanks for the suggestion, I've created an issue in our JIRA [1]. I think it could make it to the roadmap soon as it is not complicated to implement and very useful for custom deployments.

As for the logo and custom branding, this is already possible by mounting SCSS files and assets to the client image as described in the documentation [2]. You can either just add your custom logo and override `$side-navigation-logo-url` in `_variables.scss` or override the whole `` style in `_overrides.scss` if your logo has a different size. You can, of course, override any SCSS variables or entire styles to customize DSW to your brand. Mounting of all the files and assets folder is in the deployment example [3].

[1] https://ds-wizard.atlassian.net/browse/DSW-634
[2] https://docs.ds-wizard.org/en/latest/admin/configuration.html#config-client
[3] https://github.com/ds-wizard/dsw-deployment-example
