### ISSUE TITLE
Integration fails on numerical values

### ISSUE THREAD

**Issue by vildead** [ds-wizard/ds-wizard#188]
**Describe the bug**
Integration is not successful when **Response Name Field** yield numeric values.

Given super basic api call:  
```bash
curl -X GET 'https://api.carbonintensity.org.uk/intensity'  -H 'Accept: application/json'
```
with result:
```json
{ 
  "data":[{ 
    "from": "2020-03-10T12:30Z",
    "to": "2020-03-10T13:00Z",
    "intensity": {
      "forecast": 133,
      "actual": 132,
      "index": "low"
    }
  }]
}
```

Steps to reproduce the problem:
  * Request URL: https://api.carbonintensity.org.uk/intensity
  * Header: Access: application/json
  * Response List Field: data
  * Response Id Field: from
  * Response Name Field: intensity.forecast

**Observed behaviour** 
`Unable to get type hints.`  
If i use `Response Name Field: intensity.index`, it works. (getting value 'low')

**Expected behavior**
Getting available values - in this case number 133 - as an option.

**DS Wizard deployment:**
 -  demo.ds-wizard.org
 - Firefox 73.0.1 (64-bit)

You might wonder why would anyone want to add only number to a DMP. Frankly, I don't know. I can imagine cases where internal institutional project ID is well adopted and names might not be unique.

**Comment by MarekSuchanek** [comment]
@vildead thank you very much for your report! We included fixing this bug into the current sprint in our JIRA: https://ds-wizard.atlassian.net/browse/DSW-686. It will be released with version 2.2.0.

----
In case you need any assistance with building your own knowledge model, have some ideas or feedback, please let me know 😊
