### ISSUE TITLE
Non-functional password reset

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#189]
**Describe the bug**
The password reset (Forgotten Password) function does not work, neither in our instances nor the official demo instance. The client shows `Problem in deserialization of JSON` (due to lack of response?) and in our instances the server responds with:
```
[Rqst] [U:---][T:---] 400 Bad Request POST /action-keys
```

**How to reproduce**
Steps to reproduce the problem:
1. Go to e.g. https://demo.ds-wizard.org/forgotten-password
2. Fill in an email address.
3. Click Recover

**Expected behavior**
A password reset email should be sent to the user.

**DS Wizard deployment:**
 - Instance: demo.ds-wizard.org, both of our local instances
 - Browser: Chrome, Firefox

**Comment by MarekSuchanek** [comment]
Thanks for reporting and sorry for the inconvenience. Fortunately, this bug is known, fixed, and will be included in the next release (see DSW-745).
