### ISSUE TITLE
Nicer download filenames

### ISSUE THREAD

**Issue by neon-ninja** [ds-wizard/ds-wizard#190]
Currently, when you download a document, the filename is something like 6e371c99-ddf7-48a8-895b-7c7bdc62730d.pdf - it might make for a better user experience to have something human readable in the filename - like the document name. This seems to be the responsible line of code: https://github.com/ds-wizard/engine-backend/blob/41e8d47c50a5882b37d0fa638861840546140821/engine-wizard/src/Wizard/Api/Handler/Document/Detail_Download_GET.hs#L27

**Comment by MarekSuchanek** [comment]
@neon-ninja thanks for your idea, it would really enhance UX.

We will discuss this in our team as there might be some edge cases (as usually are when something uses user's input) - for example, filename should not contain some characters such as slashes or quotes. There are probably some ways of filename normalization, but it could even lead to "empty" filenames (e.g. with document name "///"). Maybe such limitations should be included when entering the document name already or maybe UUID could be used as fallback for filename... Any opinion on this?

**Comment by MarekSuchanek** [comment]
@neon-ninja Would such normalization of name be OK in your opinion: https://pypi.org/project/pathvalidate/#sanitize-a-filename with UUID fallback in case of sanitization results to empty filename?

**Comment by neon-ninja** [comment]
Sounds good to me @MarekSuchanek

**Comment by MarekSuchanek** [comment]
It is prepared and will be included in the upcoming release, see DSW-821 for more details...
