### ISSUE TITLE
Visualising progress of filling in the questionnaire.

### ISSUE THREAD

**Issue by rwwh** [ds-wizard/ds-wizard#191]
**Is your feature request related to a problem? Please describe.**
A user currently has no way of knowing how much of the questionnaire they have filled. Every question they answer can add new questions infinitely, so there is no idea how long it will still take to get to the end.

**Describe the solution you'd like**
Piotr Wojciech Dabrowski: "Ideally the users would have a feeling of advancement while being guided through the document, so they don't feel like they are investing a lot of time upfront without knowing what the payoff will be, kind of like the filtering in the search in an online store. Just as a quick idea (this could, as far as I understand the DSW format, also be done as an alternative view for the DSW) I have attached two (extremely schematic) images of a rough navigation idea: A mind-map like thing that starts collapsed, and as the user expands and selects nodes, they can see how that condenses the huge document (rightmost bar) to just the parts relevant to them."

I think indeed a thin "non-scrollbar" at the right schematically representing the whole KM could be rendered, and pieces that are filled or excluded by given answers can be colored differently to show the progress. Also, pieces that are not yet "required" in the current phase could be indicated in a different color.

As a refinement, it may be theoretically useful if questions have a property that could be queried on how "high" they are in the schema (sort of a "weight" for the question). This does not need to be implemented immediately, but it would be nice if the implementation could be extended with such a feature easily in the future. We start with all questions being considered equally weighted.

**Describe alternatives you've considered**
None

**References and resources**
n.a.

**Additional context**
This was suggested by Piotr for the RDA Covid-19 version of the wizard.

**Comment by MarekSuchanek** [comment]
Moved to: https://ideas.ds-wizard.org/posts/19/make-sure-that-people-can-see-at-a-glance-how-much-of-the-questionnaire-has-been-filled-in
