### ISSUE TITLE
new installation of DSW

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#194]
**The Question**
Bootstrap Error Application cannot load configuration. 

**DS Wizard part**
New DSW installation.using the dsw-deployment-example docker configuration. 

Dear all,
I (Paulette from IFB France)  just installed dsw on wp.fairwiki.france-bioinformatique.fr. I can access the client from my own pc, but as soon as I try to access dsw from the outside (say using a VM). DSW doesn't load and shows the above message.

Now this may seem a very stupid question, but honestly, I wouldn't know where to start looking... It is obviously an issue of authentication or something like this, but I am lost.. :( 

**Additional context**
![Screenshot from 2020-12-01 15-31-37](https://user-images.githubusercontent.com/47455219/100754157-02120a80-33eb-11eb-9284-7b0cb8ef27cd.png)

many thanks in advance !

**Comment by MarekSuchanek** [comment]
Hello Paulette, the `API_URL` is incorrectly configured to `localhost:3000` but it must point to accessible URL where DSW is (e.g. we have https://api.demo.ds-wizard.org for DSW Demo instance).

ℹ️ Just a note: the provided example deployment is not intended for production deployment.
