### ISSUE TITLE
updating of KM questionnaire & project after KM modification

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#196]
**The Question**
Updating a questionnaire

**DS Wizard part**
KM editor

**Additional context**
Once the K model has been updated, and newly (re)published, how can one update the corresponding questionnaire in the project? 
The project duly shows it is outdated but how do we update it?

**Comment by MarekSuchanek** [comment]
You should be able to "Create Migration" where you can select newer version of KM and "migrate" the replies (if possible). This process will create a new questionnaire/project related to the new KM.

![image](https://user-images.githubusercontent.com/9638527/101868916-9d8b4400-3b7e-11eb-877b-3677100a8951.png)

**Comment by froggypaule** [comment]
Perfect, thanks Marek. Exactly what I was looking for.
