### ISSUE TITLE
Autofill of some fields

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#197]
**The Question**
Autofill of some fields

**DS Wizard part**
dsw_client/server

**Additional context**
1. is there a way of filling some fields conditionally given some prior answers elsewhere?
2. Or is the 'follow up' answer the only mechanism to achieve this?
Thanks.

**Comment by MarekSuchanek** [comment]
Not exactly sure what do you want to achieve... maybe it is the same as this idea (not-yet-implemented): https://ideas.ds-wizard.org/posts/20/conditional-options-prefilled-answers-and-decision-tree-branches

If not, please give some brief example.

**Comment by froggypaule** [comment]
Indeed this is what I meant. Soonish I'll give a more precise example in this ideas link. Thanks!
