### ISSUE TITLE
Creation of list of options from a file

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#198]
**The Question**
Concerns the building of lists of options

**DS Wizard part**
dsw-server

**Additional context**
Is it possible to script the creation of the option items by reading a file listing these options ?

**Comment by MarekSuchanek** [comment]
No that is not possible directly in the DSW... if it is a JSON file available through network (published somewhere), then you could use an "integration question". You could achieve that by generating "AddAnswerEvent" in KM JSON representation (if you export KM as .km file, it is actually a JSON).

**Comment by froggypaule** [comment]
Thanks Marek. This could be what I want. Not sure I'll use this method right now (not enough time ;) ) but I'll have a closer look at that.

Very best wishes to you and your team for this end of the year. And some rest too!

**Comment by MarekSuchanek** [comment]
OK, reopen then if needed please.

Wish you Merry Christmas and Happy New Year! 🎄
