### ISSUE TITLE
Meaning of CrossReference and ResourcePage

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#200]
**The Question**
CrossReference and RessourcePage in AddReference

**DS Wizard part**
dsw-client

**Additional context**
I just discovered the AddReference functionality. While I see what 'URL' means (introducing an external link: it works, great!), I can't see what the two other options are and mean to do. I was wondering if it was possible to link back to an item in the km?

Thanks. Sorry --I am discovering bit by bit; I have the intention of creating our km programmatically, and your hint on export/import helped greatly!

**Comment by MarekSuchanek** [comment]
- Resource Page reference is currently just internal thing - references to parts of the book Data Stewardship Wizard for Open Science by Barend Mons, e.g. `atq` for refering to https://demo.ds-wizard.org/book-references/atq. In the future, we plan to allow define custom pages with more detail guidance like are those "book" pages (see DSW-701)
- Cross Reference can be used with UUID of another question in the KM, e.g. when you want to state that one questions is somehow related to a question somewhere else (it is not directly a follow-up nor the same topic where you could use tags but it is related differently). It is not currently displayed in the questionnaire but we plan to work on conditional questions and persistent links to certain questions...

**Comment by froggypaule** [comment]
Thanks Marek: good for the CrossReference Page, I was looking for such a capability.
