### ISSUE TITLE
I need help re creating json km

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#201]
**The Question**
deserialising km.json

**DS Wizard part**
dsw_server

**Additional context**
Dear Marek, I am stuck.... I created un json file representing our km. Loading it to dsw, it deserialises correctly (log files show no error). But unfortunately, once loaded the km editor doesn't show the questions for example.
I thought I understood how to construct the json file, but apparently not :( 

Could you have a look a the file in question? very much appreciated. Cheers.
[PGDQX73533.txt](https://github.com/ds-wizard/ds-wizard/files/5753967/PGDQX73533.txt)

**Comment by froggypaule** [comment]
Actually, I found the culprit: 
I thought that keeping reloading the updated file would refresh the km. Actually no:

Typically what I would do, is first delete the km and reload the file. But I realised that I still got back the old version of the km.
Only by changing kmId and giving it a new value, did the updated km load properly.

Conclusion: my km and json file work correctly.
But then, do we have a cache (or rather a database) issue? or is this behaviour expected?

Many thanks!

**Comment by MarekSuchanek** [comment]
Yeah going back should not be done... (e.g. "changing history"). There is in-memory cache that stores "compiled" KMs per ID. To clear the cache you can restart the server (or whole docker container) or use API call https://api.demo.ds-wizard.org/swagger-ui/#/default/delete_caches

**Comment by froggypaule** [comment]
Ok thanks. Basically I took 'delete km' to mean it deletion from the db (which is correct isn't it?). I'll look into the APIs.... But I understand your concept of 'compilation'; but one could understand 'deletion' as 'removeKmEvent', not necessarily as changing history?
Anyway, that's not important. thanks.

**Comment by MarekSuchanek** [comment]
Honestly, I am not sure exactly... but when you delete X.Y.Z and then upload the same version X.Y.Z but with different content it may cause a problem as such behavior is not expected.

**Comment by froggypaule** [comment]
ok, thanks, merci.
