### ISSUE TITLE
unable to migrate project/questionnaire

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#203]
**Describe the bug**
migration fails when performing a specific modification

**How to reproduce**
1. load the attached km, create a project
2. see the attached km, and go to the chapter "test options"
3. modify/add an answer and/or a follow up question
4. save and publish
5. go to project previously created: it shows it is outdated, proceed to migrate
6. the migration fails --see attached screenshot

**DS Wizard deployment:**
 - own instance from docker

**Additional context**
nothing shows in the log files

![Screenshot from 2021-01-04 12-49-24](https://user-images.githubusercontent.com/47455219/103532552-bdffa300-4e8b-11eb-8dcd-fc3d93211cb6.png)

[global bioimage-18 0.0.3.txt](https://github.com/ds-wizard/ds-wizard/files/5764488/global.bioimage-18.0.0.3.txt)

**Comment by MarekSuchanek** [comment]
I tried to import the attached KM and there is just 0.0.3 of bioimage-18, can you send the one with 0.0.4 as well?

**Comment by froggypaule** [comment]
here we are. thanks!
[global bioimage-18 0.0.4.txt](https://github.com/ds-wizard/ds-wizard/files/5795702/global.bioimage-18.0.0.4.txt)

**Comment by MarekSuchanek** [comment]
That is really strange... I modified a question and added a new followup there and it works:

![image](https://user-images.githubusercontent.com/9638527/104583614-a087c180-5661-11eb-8b93-60b0366070a6.png)

Could you export and send also the questionnaire? (Using the questionnaire-report template in JSON)

**Comment by froggypaule** [comment]
I am sorry Marek : I did some unwise cleaning and I can't reproduce this. So I'll close this. Suppose it were to happen again, I'll make sure to include all relevant files. Many thanks.
