### ISSUE TITLE
find the km upon which the project is based

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#205]
**The Question**
The project is build from a km: how in a project do we we find the name of the associated km?

I for one couldn't see (in the projetc/questionnaire) where a reference to the km could be. What did I miss? Thanks!.

**Comment by MarekSuchanek** [comment]
That should be visible from "Projects" list, the KM name and ID is even clickable:

![image](https://user-images.githubusercontent.com/9638527/106560784-de248f80-6527-11eb-81a2-07fda46e4490.png)

**Comment by froggypaule** [comment]
ooop... thanks Marek... now I see it :(  must have been asleep a long time.
