### ISSUE TITLE
Error trying to create a report

### ISSUE THREAD

**Issue by NuriaQueralt** [ds-wizard/ds-wizard#206]
**The Question**
I created a mocked CRF, and when I am trying to create a report in RDF/TTL the wizard return error with no further message and without generating a report. I don't understand why happens in order to fix the problem and create the report..

**DS Wizard part**
document generation.

**Additional context**
It is my first attempt to create a CRF and then create a report from it.

**Comment by MarekSuchanek** [comment]
Hello @NuriaQueralt, that is hard to investigate based on your description... In which DSW (or CRF Wizard) instance, did that happen?

**Comment by NuriaQueralt** [comment]
Hi @MarekSuchanek it happend in the following instance: https://dsw.kiu.ac.ug/

**Comment by MarekSuchanek** [comment]
Unfortunately, I cannot tell more regarding that as I cannot access the server logs, you will have to contact the admins of that instance. The only one I can check is https://dsw.vodan.fairdatapoint.org, can you try to reproduce it there?

It may be caused that some of the question is answered in unexpected way (incorrect format) or that the template they use is somehow customized and there is some other problem in it.

**Comment by NuriaQueralt** [comment]
Thank you @MarekSuchanek if I can I will reproduce it in your suggested FDP. I will reach the admin of our instance too.
