### ISSUE TITLE
who can see templates (privileges)

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#207]
**The Question**
What are the privileges required for logged-in users to see and peruse the templates, as well as being able to choose them for output.

**Use case**
- on a standalone instance
- case 1: logging in as another user as myself where the client is served by a VM, I can see and work with the templates as long as I am 'admin'
- case 2: user X, working remotely, is admin and logged in, cannot see the templates button in the left-handside nav bar

What are we doing the wrong way? or misunderstanding?
Thanks.

**Comment by MarekSuchanek** [comment]
- Templates can be used to export a document by any user with role "researcher" (the most basic role).
- Templates (in a list and menu) can be managed only by "admins".

It is strange that you do not see it in the menu if you are admin (if I understand correctly). Can you try to log-out and log-in again? Does that help?

**Comment by froggypaule** [comment]
Ok thanks, that's what I thought too... I'll go back to the user: maybe if was just a matter of not refreshing the page or whatever...

**Comment by froggypaule** [comment]
Hiho! solved: indeed login/out did the jobs. Sorry for that.
