### ISSUE TITLE
Another question re templates

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#208]
**The Question**
How to set templates in project's settings

**DS Wizard part**
client

**Additional context**
I have imported a few templates (Questionnaire Report, Science Europe, etc...). But why, why attempting to set a template (using project's settings), do I only see Questionnaire Report given as a choice?
Which step did I miss? thanks.

**Comment by MarekSuchanek** [comment]
Some templates are bound to a certain knowledge model... 

For example, the Science Europe template: It uses a questions about re-used datasets. But such a question is known to be in dsw:root KM with a certain UUID. Then, with any other knowledge model we don't know if and where is the question about re-used datasets and the UUID is definitely different. In case of "customizations" of the dsw:root, the question may be there with the same UUID, but there is no guarantee that the customization does not change or delete the question.

If you just enhanced your KM with new questions or made changes that do not affect the science europe template, it is needed to change the configuration of the template (best using DSW TDK). 

On the other hand, Questionnaire Report template is generic and can be used with any KM as it does not make any assumptions about it contents. It basically iterates over all chapters, questions, etc.

**Comment by froggypaule** [comment]
Ah ok, so the other templates are not generic but bound to a km? So in actual fact, I'll have to write our own templates based on our km, creating the mappings and so on...
Thinking of it, it makes sense: I guess I got sidetracked by the generic questionnaire.... 
Thanks again!
