### ISSUE TITLE
date format for 'createdAt'

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#209]
**The Question**
For timestamp, you write: Standard ISO timestamp format, e.g., 2019-06-09T14:25:58.438Z

For the life of me, what is the translation in the date command format? I've tried everything, with the most obvious being 'date -Is.' I don't understand where your format above comes from.
And of course, as a consequence, DSW shows that the km has been created at 01/01/1970.... 
thanks!

**Comment by MarekSuchanek** [comment]
You can use `date --utc --iso-8601=seconds` (but that does not support milliseconds and `Z` instead of `+00:00` - it should work anyway, even without `--utc`). To make completely matching: `date --utc +%Y-%m-%dT%H:%M:%S.%3NZ`

**Comment by froggypaule** [comment]
ok... Mumm two things:
- it doesn't do the trick 
![Screenshot from 2021-02-11 12-35-25](https://user-images.githubusercontent.com/47455219/107631739-cb1b6900-6c65-11eb-89da-68db7abf7597.png)
and the date is "createdAT": "2021-02-11T11:34:01.320Z" --the logs don't show anything
- but, why choose UTC? I prefer the format -Is or %Y-%m-%dT%H:%M:%S.%3NZ  but keeping the local time: it is much closer to the users etc...

**Comment by MarekSuchanek** [comment]
And how does `createdAt` your JSON-KM look like? It should be something like `"createdAt": "2020-12-10T14:10:21.121Z",`...

UTC is just internal thing, it is the best to store all time information in some unified timezone and clients should then render the dates based on users location (i.e. computer settings)...

**Comment by froggypaule** [comment]
hello Marek,

- ok for computer settings (I wasn't thinking this way...)
- for for you ask:
![Screenshot from 2021-02-12 09-07-11](https://user-images.githubusercontent.com/47455219/107743755-c8764d80-6d11-11eb-88c9-7fc701762d15.png)

thanks!

**Comment by MarekSuchanek** [comment]
I think the issue is that field names in JSON are case-sensitive and you have `createdAT` instead of `createdAt`.

**Comment by froggypaule** [comment]
ooops! thanks for spotting it! this must be the answer. Cheers.
