### ISSUE TITLE
Rendering tags in document templates fails for questions with multiple tags

### ISSUE THREAD

**Issue by wna-se** [ds-wizard/ds-wizard#210]
**Describe the bug**
Rendering tags in document templates fails for questions with multiple tags

**How to reproduce**
Steps to reproduce the problem:
1. Ensure that you have a KM with multiple tags assigned to a single question
2. Create a questionnaire based on the KM and select a single tag that is used together with other tags 
3. Create a new document using the template dsw:questionnaire-report:1.2.0 and any format other than JSON

**Expected behavior**
The dsw:questionnaire-report:1.2.0 should work regardless of how the questionnaire is configured.

**DS Wizard deployment:**
 - Instance: Local, docker-compose using DS-wizard 2.11.0 and dsw:questionnaire-report:1.2.0
 - Browser: Firefox

**Additional context**
The JSON document format works but I can see that the the properties of the tags that were not selected are created missing from the knowledgeModel.entities.tags object. Commenting lines 18–21 in default.html.j2 renders the documents successfully but without the tags.

**Comment by MarekSuchanek** [comment]
@wna-se Thank you for detailed reporting! Indeed, there is a bug when creating the document context - I created a JIRA task for that: DSW-1009 and it will be fixed for the next version.

Also, I adjusted the questionnaire-report template and released 1.2.1:
https://github.com/ds-wizard/questionnaire-report-template/commit/440535a21daee0e509807eff31b8a9baebac713f
https://github.com/ds-wizard/questionnaire-report-template/releases/tag/v1.2.1
https://registry.ds-wizard.org/templates/dsw:questionnaire-report:1.2.1

Please import the new template, with that it should no longer cause errors (worked for me). Close then the issue, if it helped...
