### ISSUE TITLE
FIP wizard

### ISSUE THREAD

**Issue by keesvanbochove** [ds-wizard/ds-wizard#211]
**The Question**
Is https://fip-wizard.ds-wizard.org/ the right URL for the production FIP wizard? Because I'm running into an issue where the link points to a localhost URL:
![image](https://user-images.githubusercontent.com/373418/109036530-fcfee780-76c9-11eb-9a0c-7c93aac64740.png)

**DS Wizard part**
Creating a FIP

**Additional context**
Add any other context or screenshots related to the question.

**Comment by MarekSuchanek** [comment]
Hello @keesvanbochove,
It is the correct URL, but the authors of the content there suppose you are running tool [nanobench](https://github.com/peta-pico/nanobench) locally, i.e., on your `localhost` (as it needs some local signing keys etc.). I will let them know about this issue, so they can provide more details and/or enhance the descriptions in the FIP Knowledge Model.
