### ISSUE TITLE
cannot sign up

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#212]
**The Question**
cannot sign up: nothing happens

**DS Wizard part**
client

**Behaviour**
- trying to sign up & nothing ensues

**Additional context**
the log file shows 

dsw_client_1  | 2021-04-20T10:36:37.987500155Z 2021/04/20 10:36:37 [error] 18#18: *149 open() "/usr/share/nginx/html/signup" failed (2: No such file or directory), client: 172.19.0.1, server: localhost, request: "GET /signup HTTP/1.1", host: "dsw.france-bioinformatique.fr"

**So**

- what is the configuration I have missed? 

**DSW** is self-installed and 2.13.0

**Comment by janslifka** [comment]
Hello,

There was a bug in 2.13.0 that prevents sign up under certain conditions. We've released a bug fix of the client in 2.13.1 that fixes this issue. Can you try the client version 2.13.1 and let us know if the issue persists?

**Comment by froggypaule** [comment]
hello Jana! 
that was seedy: all works! thank you..... 
Cheers.
