### ISSUE TITLE
adding listOfItems bloc to questionnaire results in a freeze 2.13

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#213]
**The Question**
Cannot add 'ListOfItems' in the project/questionnaire: freezing

**DS Wizard part**
dsw_server

**Additional context**
Now, I apologise in advance: it is very likely my dsw installation is crook.

DSW: 
- self-install
- did a recent install of 2.13
- and simply migrated (actually copied) the mongodb from old install 2.8.1 to new install 2.13

**The problem**
- taking the dsw:lifesciences:2.3.0 km, I create a project from it
- as soon as I add a listOfItems bloc, everything freezes 
with 

[T:------------------------------------] [API         ] Status {statusCode = 426, statusMessage = "Upgrade Required"} GET /questionnaires/3d31348d-ea3e-46dd-9e9c-8dc7c6c9d372/websocket?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVXVpZCI6IjRmOWE5NjYxLWQ0YzItNGYxNy1hYjc2LWYzNDgyZDgyNmU2NyIsImV4cCI6MTYyMDM5NjAxMywidmVyc2lvbiI6IjIifQ.dCtkMqyx4ysMImlUAIfnGoNTuM-tGA755OhSfCpn5w8

[docker-compose.zip](https://github.com/ds-wizard/ds-wizard/files/6378305/docker-compose.zip)

many thanks in advance.

**Comment by froggypaule** [comment]
Actually, I believe the problem occurs at the time of saving the questionnaire/project: as soon as one fills in any field, this behaviour (and the same log message) is observed.

**Comment by MarekSuchanek** [comment]
The server says `426 Upgrade Required` which means that you are probably missing correct configuration in your HTTP proxy:

```nginx
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
 ```
 
 See example here: https://docs.ds-wizard.org/en/latest/admin/upgrade.html#x-to-2-6-x

**Comment by froggypaule** [comment]
Good morning @MarekSuchanek . Unfortunately, these declarations are well in place. I understand it is a http issue, I am looking further into the pb. I'll report ASAP. thanks.

**Comment by froggypaule** [comment]
Ok, no comment: I was a fool, and I didn't properly setup these declarations. Now this works. Thanks for your time.
