### ISSUE TITLE
Carriage return not accepted in system settings, organization:  affiliations 2.13

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#214]
.**Describe the bug**
Carriage return not accepted in system settings, organization:  affiliations

**How to reproduce**
Go to system settings, organization: one can only enter one affiliation, since carriage return not accepted.

**Expected behavior**
I cite: "Affiliation options will be used to help users choose their affiliation while signing up or editing their profile. Write one affiliation option per line."

**Screenshots**
Nothing detected in the log files. All what carriage return does in expand the response field. See screeshot.

**DS Wizard deployment:**
 - self hosted docker 2.13.0
 - firefox

![Screenshot from 2021-04-27 08-08-50](https://user-images.githubusercontent.com/47455219/116193854-49998a00-a730-11eb-9cef-a76252bff2e0.png)

**Comment by MarekSuchanek** [comment]
Not sure if I understand this correctly. You copy-pasted some text with CR (or CR-LF)? Or pressing Enter key?

![image](https://user-images.githubusercontent.com/9638527/116284349-4b456b00-a78d-11eb-9e24-424c58298db7.png)

**Comment by froggypaule** [comment]
Hello @MarekSuchanek : I confirm, it is pressing the enter key that results in the field input box expanding, but there is no way do achieve what you show above.
Likewise, if I copy paste a list, everything ends up on one line.

Client 1.13.1

**Comment by MarekSuchanek** [comment]
Could you try a different browser? Is the problem there for you as well?

**Comment by froggypaule** [comment]
good point Marek: indeed it does work with Chrome, but not firefox. Ta!
