### ISSUE TITLE
creating a km using the editor from programmatically created km

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#215]
**The Question**
A km is created programmatically, is imported successfully in dsw, but I can't create a new km from it (using the km editor) without giving it another name. Why is that?

Obviously it is related to the way the km is created. See attached file.
[PGDQX2021-07-06T10-12-04CEST.txt](https://github.com/ds-wizard/ds-wizard/files/6769054/PGDQX2021-07-06T10-12-04CEST.txt)

**Additional context**
The server log file shows 'bad post request' that's all. Many thanks.

**Comment by MarekSuchanek** [comment]
What is the procedure that fails for you?

I tried:

1. Import the KM from file (success)
2. Press "Create KM editor" from dropdown (three dots in table view)
3. Form for creating KM editor without any change (prefilled)
4. Create (success)

Maybe you already have an editor with the same KM ID? You can have only one at the same time...

**Comment by froggypaule** [comment]
I am embarrassed :(  
indeed: "Maybe you already have an editor with the same KM ID? You can have only one at the same time..."
sorry for wasting you time...
