### ISSUE TITLE
bug or question: project preview fails in 3.1.0

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#216]
**Describe the bug**
Project preview 'does not work'

**How to reproduce**
- pick any project
- set any template (in settings)
- preview cycles for ever (see screenshot
![Screenshot from 2021-07-09 08-39-12](https://user-images.githubusercontent.com/47455219/125072241-a31c1e80-e0ba-11eb-97e7-e0cbb1b7850a.png)
)

**log files**

the log files actually show something interesting: 

dsw_client_1  | 2021-07-09T11:03:48.782486689Z 2021/07/09 11:03:48 [error] 20#20: *90 open() "/usr/share/nginx/html/projects/bba5ef91-28b1-48c1-adaa-fb49d37e8f16/preview" failed **(2: No such file or directory)**, client: 172.20.0.1, server: localhost, request: "GET /projects/bba5ef91-28b1-48c1-adaa-fb49d37e8f16/preview HTTP/1.0", host: "dsw.france-bioinformatique.fr"

where does this come from as it is a docker deployment?
See screeshot as well.
![Screenshot from 2021-07-09 13-41-45](https://user-images.githubusercontent.com/47455219/125072865-6ef52d80-e0bb-11eb-87e7-0d95976d7848.png)

**DS Wizard deployment:**
 - self-installed; 3.1.0, docker
 - firefox

**Additional context**
I say 'bug or question' because  I could have missed something somewhere.... Since migrating to 3.0.0 and then 3.1.0, I only recently tried to do 'serious' work again; and fell onto this problem.

**Comment by MarekSuchanek** [comment]
Are you sure that you have configured S3 URL in you yml config file?

https://github.com/ds-wizard/dsw-deployment-example/blob/master/dsw.yml#L10

**Comment by froggypaule** [comment]
euh....  this is what I have:

s3:
  url: http://minio:9000
  username: minio
  password: minioPassword
  bucket: wizard

**Comment by MarekSuchanek** [comment]
I was not able to reproduce this issue by omitting custom config file nor by supplying incomplete/incorrect config file.

The thing in logs in indeed an issue in the code; however, that code is never used if correct config file is there... Could you send me a ZIP with your config file and docker-compose.yml (with removed secrets/passwords) via email or Slack?

**Comment by froggypaule** [comment]
Good morning @MarekSuchanek , and thanks. I suspect indeed something must be fishy in how I do things (see #215 for example).
zip file sent.

**Comment by MarekSuchanek** [comment]
I don't see the ZIP file coming anywhere (yet)

**Comment by froggypaule** [comment]
Hello Marek,

Sorry, I thought I sent it.... my apologies ..... ;)
Paulette.

On 12/07/2021 14:23, Marek Suchánek wrote:
> I don't see the ZIP file coming anywhere (yet)
>
-- 
-------------------
Paulette Lieby
-------------------
Ingénieure de recherche gestion des données
Institut Français de Bioinformatique IFB
USM3601 IFB Core
-------------------
Research Engineer Data Management
French Institute of Bioinformatics
USM3601 IFB Core

**Comment by froggypaule** [comment]
yeah... got mixed up in the addresses.... :(
P.

On 12/07/2021 15:06, Paulette Lieby wrote:
> Hello Marek,
>
> Sorry, I thought I sent it.... my apologies ..... ;)
> Paulette.
>
> On 12/07/2021 14:23, Marek Suchánek wrote:
>> I don't see the ZIP file coming anywhere (yet)
>>
-- 
-------------------
Paulette Lieby
-------------------
Ingénieure de recherche gestion des données
Institut Français de Bioinformatique IFB
USM3601 IFB Core
-------------------
Research Engineer Data Management
French Institute of Bioinformatics
USM3601 IFB Core

**Comment by froggypaule** [comment]
Hello @MarekSuchanek ,
It is possible you are on leave.... if not, I picking this here again: the impossibility of previewing a project. This shows also up in the documents list 
![Screenshot from 2021-07-20 11-50-57](https://user-images.githubusercontent.com/47455219/126302819-46f54c1d-d8a3-43ed-8188-4f32bc79d2b7.png).
I can't delete the documents queued either. 

I am not sure what I can do at this stage: maybe trying to reinstall dsw from scratch and restore the db....
Thanks!

**Comment by MarekSuchanek** [comment]
@froggypaule I am sorry, was not here for some time... But if I am looking correctly, I can't see the ZIP file with your deployment configuration anywhere (email nor Slack).

**Comment by froggypaule** [comment]
[dsw-ifb.zip](https://github.com/ds-wizard/ds-wizard/files/6847453/dsw-ifb.zip)

Apologies @MarekSuchanek : I thought I did send it. 
Thanks for looking into it; it seems to me that I am a pain... but really I am lost here.

I try now to install a fresh dsw, and then to import the db. Wish me luck! ;)

**Comment by MarekSuchanek** [comment]
The problem is with your configuration file mounted to the `docworker` container.

Since `3.0` release, it is possible to use the same configuration file for both `dsw_server` and `docworker`. Try to change `docker-compose.yml:32` from this:

```yml
    volumes:
      - ./docworker/config.yml:/app/config.yml:ro
```

to this:

```yml
    volumes:
      - ./server/application.yml:/app/config.yml:ro
```

That is the best way to keep the configuration consistent among component.

**Comment by froggypaule** [comment]
ok thanks heaps @MarekSuchanek (sorry for being so clumsy with docker :(  ).  -- it workd --of course!
back in 1h or so re your km template. Cheers.

**Comment by MarekSuchanek** [comment]
Glad we solved this 🙂

**Comment by froggypaule** [comment]
me too :)
