### ISSUE TITLE
Mutliple listing of projects

### ISSUE THREAD

**Issue by korbinib** [ds-wizard/ds-wizard#219]
**Mutliple listing of projects**

Projects are listed more than once after update to v3.2.0

**How to reproduce**
Steps to reproduce the problem:
1. Go to 'projects'
3. Browse projects
4. Serveral projects with identical title and ID listed several times

**Expected behavior**
One entry per project

**Screenshots**

**DS Wizard deployment:**
 - Instance elixir-no.ds-wizard.org v3.2.0~ef49335
 - Browser Chromium 92.0, Firefox 91.0

**Additional context**
Problem occurs also in 'Create Project' from Template

**Comment by vknaisl** [comment]
Hello Korbinian,

thanks for reporting! Yes, it seems that we introduced the error in the last version. The questionnaire duplication should happen just for Admin users and just for the case when the questionnaire has more users assigned. Users that have data steward or researcher roles should not be affected by this bug. We will fix that in the next release at the beginning of September. You can watch the progress here in Jira [1]. Sorry for the inconvinience.

Vojtech

[1] https://ds-wizard.atlassian.net/browse/DSW-1164

**Comment by korbinib** [comment]
Hello @vknaisl, thank you for looking into this. It seems to me this also partially occurs for non-privileged users not only for admins.

**Comment by vknaisl** [comment]
Hello,

thanks for providing more details. There was a missing `DISTINCT` in a SQL query. We added it there. Therefore, it should fix all problems - even for non-admin users. Since the error may affect non-admin users, we decided to change it to hotfix. We release now a version 3.2.2.

Vojtech

**Comment by MarekSuchanek** [comment]
This has been fixed in `3.2.2` release... closing the issue.
