### ISSUE TITLE
migration 3.0.0 to 3.1.0: problem with the feedback feature

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#221]
**Describe the bug**
Postgres parsing issues ; see screenshot 
![Screenshot from 2021-08-31 16-10-03](https://user-images.githubusercontent.com/47455219/131649309-5b0ca7c1-36f2-4122-94bf-761c74b34867.png):
"\\u0000 cannot be converted to text."

**How to reproduce**
Steps to reproduce the problem:
1. self-installed DSW 3.0.0 ; feedback (which expects user and project name from github) has been filled using gitlab references; 
 no errors are thrown, and dsw client/server are up and running
2. attempt migration to 3.1.0, simply by updating docker-compose.yml
3. dsw server + postgres throw errors as shown above
4. once the feedback settings are filled in properly (with proper details from a github project), everything goes well

**Expected behavior**
The fact that feedback settings may be null need to be caught somehow.

**Additional context**
I thought that may be of use to you the dev.

**Comment by MarekSuchanek** [comment]
Hi @froggypaule, no sure what do you mean by "gitlab references". Did you change it via Settings in UI? It seems that it is not a problem with `null` value but `\u0000` character in some string inside the JSON...

**Comment by froggypaule** [comment]
Hello: as far as I can remember the situation was as follows:
- I did set the feedback settings to point to my gitlab repo: of course we know this cannot work (we had this discussion before); still I forgot to rectify it
- and this is how this error occurred, ie with these erroneous gitlab ref.
- again, as I say, 3.0.0 did not throw an error, but 3.1.0 did

**Comment by MarekSuchanek** [comment]
I checked the database migration `2 - Project Template` and it just changes `questionnaire` column, no change to `feedback` section... So the data had to be malformed before the data migration and just cause it now to fail during the update of the row. My guess is that there was an issue with the `token` that is encrypted in DB and could contain `\u0000`... we already work on storing encrypted values in BASE64 encoding: DSW-1170

**Comment by froggypaule** [comment]
you must be right --  anyway you said once that this feature will involve (as to be broader than just hooking into github). I can't remember if it is related to the comments feature currently under consideration at DSW.
I close this now.
