### ISSUE TITLE
Unable to migrate KM between instances | import dsw:questionnaire-report:2.0.0 from registry

### ISSUE THREAD

**Issue by korbinib** [ds-wizard/ds-wizard#222]
**Describe the bug**
Cannot import KM, exported from other instance. Upon upload DSW returns:

> Importing the package failed.

Possibly related: Upon import of dsw:questionnaire-report:2.0.0 from registry (or from file):

> Unable to import the template.

**How to reproduce**
Steps to reproduce the problem(s):

1. Freshly deployed v3.3.0~508abd4 via docker
2. Export [https://elixir-no.ds-wizard.org/knowledge-models/elixir.no:lifesciences-elixir-norway:0.1.5](https://elixir-no.ds-wizard.org/knowledge-models/elixir.no:lifesciences-elixir-norway:0.1.5)
3. Upload file via GUI

![image](https://user-images.githubusercontent.com/58505673/134078208-aea31cb1-efcf-4897-8d9a-a96dc0abe400.png)

The log does not show any error:

```
dsw-server_1  | [Info ] [I:cc40d01c-4afb-4ea6-90e2-a164438f4069] [T:ae2a440b-d6c3-4f25-828b-e97b0ef750f2] [API         ] 200 OK GET /packages?page=0&sort=name,asc&size=20
dsw-server_1  | [Info ] [I:------------------------------------] [T:fce658a6-baf6-43ce-a9dd-2a1f0fd6273b] [API         ] 200 OK GET /
```

1. Freshly deployed v3.3.0~508abd4 via docker
2. Enable registry
3. Import [https://registry.ds-wizard.org/templates/dsw:questionnaire-report:2.0.0](https://registry.ds-wizard.org/templates/dsw:questionnaire-report:2.0.0) from registry or file

![image](https://user-images.githubusercontent.com/58505673/134078507-7d1b2f3b-3b16-4f0f-9847-9c23cfa0509d.png)

The log shows S3 bucket related errors:

```
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [S3          ] MErrService NoSuchBucket
dsw-server_1  | [Info ] [I:cc40d01c-4afb-4ea6-90e2-a164438f4069] [T:da86fdb7-8d53-4234-97d1-88b77471084e] [Database    ] Transaction rollback
dsw-server_1  | [Error] [I:------------------------------------] [T:------------------------------------] [API         ] Error in s3 connection: MErrService NoSuchBucket
dsw-server_1  | [Error] [I:cc40d01c-4afb-4ea6-90e2-a164438f4069] [T:------------------------------------] [API         ] 500 Internal Server Error POST /templates/dsw:questionnaire-report:2.0.0/pull

```

But not while importing of other templates|earlier versions:

```
dsw-server_1  | [Info ] [I:cc40d01c-4afb-4ea6-90e2-a164438f4069] [T:99f77e62-041f-45b5-8997-bd98558bf65c] [Database    ] Ensuring transaction
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM app_config WHERE id = ?
dsw-server_1  | [Info ] [I:cc40d01c-4afb-4ea6-90e2-a164438f4069] [T:99f77e62-041f-45b5-8997-bd98558bf65c] [Database    ] Ensuring transaction
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM app_config WHERE id = ?
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM package
dsw-server_1  | [Info ] [I:cc40d01c-4afb-4ea6-90e2-a164438f4069] [T:99f77e62-041f-45b5-8997-bd98558bf65c] [Database    ] Transaction commited
dsw-server_1  | [Info ] [I:cc40d01c-4afb-4ea6-90e2-a164438f4069] [T:99f77e62-041f-45b5-8997-bd98558bf65c] [API         ] 200 OK GET /templates?page=0&sort=name,asc&size=20
```

**Expected behaviour**

Successful import

**Additional context**

Is this a metamodel related issue? Previous versions of the KM =< [0.0.20](https://elixir-no.ds-wizard.org/knowledge-models/elixir.no:lifesciences-elixir-norway:0.0.20) can be successfully imported. Similarly for earlier versions of the template =< [1.4.0](https://registry.ds-wizard.org/templates/dsw:questionnaire-report:1.4.0).

Earlier issue in the same direction?   #185

**Comment by MarekSuchanek** [comment]
When import that KM it shows me an error in DEBUG logs related to a missing package inside the file (`dsw:lifesciences:2.0.0`). It seems like an issue with export as some packages are indeed missing in the `.km` file. For now, you can do a workaround by importing first `dsw:root:2.3.0`, then `dsw:lifesciences:2.3.0`, and then finally your KM.

The issue with template import is caused by missing bucket in S3. Can you manually log in to the S3 (Minio?) web interface and create the bucket that is configured in your YAML file? You can do it alternatively using some client, e.g., https://docs.min.io/docs/minio-client-complete-guide.html ... Or a bit *hackish*, import older template without assets (`1.4.0`), create a document (worker should create the bucket for you), and then import the new template.

For both issues, I let @vknaisl know - he will investigate it.

**Comment by korbinib** [comment]
>  For now, you can do a workaround by importing first dsw:root:2.3.0, then dsw:lifesciences:2.3.0, and then finally your KM.

I tried exactly this workaround (already earlier). But it did not solve the issue unfortunately. I could try to identify the missing package and add it manually to the KM, but that is not the most clean solution I guess.

```
dsw-server_1  | [Info ] [I:------------------------------------] [T:924074b6-e718-401a-8288-1dadc93ee5c3] [Database    ] Transaction started
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM user_entity WHERE uuid = ?
dsw-server_1  | [Info ] [I:------------------------------------] [T:924074b6-e718-401a-8288-1dadc93ee5c3] [Database    ] Transaction commited
dsw-server_1  | [Info ] [I:e582a0ba-a6a6-47f7-867a-ef210c26bd86] [T:8aeed6eb-a1b0-40b6-9e46-4e24527a4516] [Database    ] Transaction started
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT COUNT(*)  FROM (SELECT COUNT(*)    FROM package    WHERE name ~* ?     GROUP BY organization_id, km_id) p
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM package WHERE id IN (     SELECT CONCAT(organization_id, ':', km_id, ':', (max(string_to_array(version, '.')::int[]))[1] || '.' ||                                                     (max(string_to_array(version, '.')::int[]))[2] || '.' ||                                                     (max(string_to_array(version, '.')::int[]))[3])     FROM package     WHERE (name ~* ? OR id ~* ?)      GROUP BY organization_id, km_id ) ORDER BY name asc  offset 0 limit 20
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT version FROM package WHERE organization_id = ? and km_id = ?
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT version FROM package WHERE organization_id = ? and km_id = ?
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT version FROM package WHERE organization_id = ? and km_id = ?
dsw-server_1  | [Info ] [I:e582a0ba-a6a6-47f7-867a-ef210c26bd86] [T:8aeed6eb-a1b0-40b6-9e46-4e24527a4516] [Database    ] Ensuring transaction
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT COUNT(*) FROM user_entity
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT COUNT(*) FROM package
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT COUNT(*) FROM questionnaire
dsw-server_1  | [Info ] [I:e582a0ba-a6a6-47f7-867a-ef210c26bd86] [T:8aeed6eb-a1b0-40b6-9e46-4e24527a4516] [Database    ] Ensuring transaction
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM app_config WHERE id = ?
dsw-server_1  | [Info ] [I:e582a0ba-a6a6-47f7-867a-ef210c26bd86] [T:8aeed6eb-a1b0-40b6-9e46-4e24527a4516] [Database    ] Ensuring transaction
dsw-server_1  | [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM app_config WHERE id = ?
dsw-server_1  | [Info ] [I:e582a0ba-a6a6-47f7-867a-ef210c26bd86] [T:8aeed6eb-a1b0-40b6-9e46-4e24527a4516] [Database    ] Transaction commited
dsw-server_1  | [Info ] [I:e582a0ba-a6a6-47f7-867a-ef210c26bd86] [T:8aeed6eb-a1b0-40b6-9e46-4e24527a4516] [API         ] 200 OK GET /packages?page=0&sort=name,asc&size=20
```

> Can you manually log in to the S3 (Minio?) web interface and create the bucket that is configured in your YAML file? You can do it alternatively using some client, e.g., https://docs.min.io/docs/minio-client-complete-guide.html ... Or a bit hackish, import older template without assets (1.4.0), create a document (worker should create the bucket for you), and then import the new template.

That works :)

**Comment by MarekSuchanek** [comment]
> I tried exactly this workaround (already earlier). But it did not solve the issue unfortunately. I could try to identify the missing package and add it manually to the KM, but that is not the most clean solution I guess.

That's strange, I tried that in a clean instance and downloaded KMs from https://researchers.ds-wizard.org ... You can turn on debug logs by adding this to your YAML configuration file:

```yaml
logging:
  level: DEBUG
```

**Comment by MarekSuchanek** [comment]
We added this to JIRA (fixing the FK constraint): DSW-1195

**Comment by korbinib** [comment]
I identified the (additional) issue on my side was caused by my deployment and too small configured proxy buffer size. Unfortunately this was not evident for me from the logs. It never made it to my web server logs (as 431) for some reason and it showed an error in the DSW-UI but not in the DSW debug logs. Thank you again for the support.
