### ISSUE TITLE
Could not upload template at dsw instance

### ISSUE THREAD

**Issue by barrydjenaba** [ds-wizard/ds-wizard#223]
Good Morning all,

I have a problem uploading a template in DSW.
Our DSW instance has been migrated to a higher version: v3.3.0. I use the same method to upload a template that we used there but I got this error :
```

INFO: Loading local template project
INFO: Connecting to https://api.learning.ds-wizard.org
INFO: Successfully authenticated as "username"
INFO: Creating remote template
FAILURE: Could not upload template
> Error response status
> Server responded with error HTTP status 400: Bad Request
> Probably incorrect API URL or template already exists...
```
**DS Wizard deployment:**
 - Instance : https://learning.ds-wizard.org/
 
I tried to create a new template and start from scratch  but I also have the same problem with the created template. I have checked the information I gived (credentials, API URL) .., seems good but I cannot find the error.

Did i miss something with the new version?
Thank you for your help.

**Comment by MarekSuchanek** [comment]
Resolved using emails... TDK should inform users about the incompatibility of template metamodel version (and suggest upgrading TDK if higher version of API is used) – this improvement will be released with the next version.
