### ISSUE TITLE
problem with "itemTemplateQuestionUuids"?

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#224]
**The Question**
- Some questions that are children of a list of items questions show doubled. I don't know if it is me or...
- why is the itemTemplateQuestionUuids not requested by the AddQuestionEvent ListQuestion? and only in the Edit event?

**context**
As you know I am still pushing ahead with a programmatic generation of KMs (hence my recent request for the schemas).
Following our last discussion on slack, I now implement the itemTemplateQuestionUuids feature. 
I think I am mastering it, but: I load the KM ok, but opening it in the editor shows a few of the items in temTemplateQuestionUuids showing twice, with the same uuid. 
![Screenshot from 2021-10-02 14-01-50](https://user-images.githubusercontent.com/47455219/135715220-0eeb6b2f-a14c-4590-ad39-06f98a65e04c.png)

**DS Wizard part**
KM editor

**Additional context**
I join here the KM I have constructed; the entity item in question is "d77e4609-28b5-4c3a-bcc1-0d25a40a64be". 
[dev-bioimage-pgd-structure-km-1.2.7.json.txt](https://github.com/ds-wizard/ds-wizard/files/7271397/dev-bioimage-pgd-structure-km-1.2.7.json.txt)

It is likely other List questions show the same behaviour, I haven't checked all.
As usual @MarekSuchanek , don't spend time on this if you think it is a waste of time, given I am not using DSW in the 'accepted' manner. Thanks!

**Comment by MarekSuchanek** [comment]
- The events are being processed in the order as listed in the package.
- When it encounters `AddQuestionEvent`, it adds automatically its UUID as a child of the parent entity specified in the Add event.
- The `itemTemplateQuestionUuids` on `EditQuestionEvent` should be used only if you need to change the order of the child questions. And at that point you must be careful to list all the child questions there and in the desired order (and also do not repeat any UUID).

What happens in your case:

1. The event `168f13c2-c0da-4777-af6d-bc4c8a031095` sets the order for following UUIDs via `itemTemplateQuestionUuids`:

```
"d25775a7-4f62-412a-b5fb-22f3007498e8",
"2c1d31ca-f8e4-4a7a-a8b5-b2bd9bc9c53a",
"db136cea-11aa-4868-a094-c232e8601339",
"c8b5ff11-5be4-4e9c-b44c-e961d30bacf6",
"3d2e3cd2-0f9e-4df6-b46f-179ae7747c11",
"729293f8-8955-4b8f-8161-64e9002d32b9",
"111c1e83-5d4b-4234-8e52-644b54413959",
"ceaa5161-675b-4327-b811-9dc9f65a48d6"
```

2. Then you move some questions to this list question... e.g. question `d25775a7-4f62-412a-b5fb-22f3007498e8` from `a2b52021-21de-48df-a244-77c86eb3ae25` in the event `3b1e1277-c8de-4486-be98-09961ec9f280`.
3. Notice that `d25775a7-4f62-412a-b5fb-22f3007498e8` was already in the list... and now it is added at the end of it again. That causes the duplication.

There is no internal check for this as it cannot happen when you do the event in the KM Editor, so the duplication leads to this behavior in KM Editor and Questionnaire 😞

**Comment by froggypaule** [comment]
Thanks so much @MarekSuchanek for your diagnostic. Good point for 2., didn't see it. Indeed! makes sense.
Thanks for confirming something I suspected, but wasn't certain of: that events in packages are listed in 'chronological' order. 
Cheers:)
