### ISSUE TITLE
publishing error in a specific migration situation

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#225]
**Describe the bug**
1. 
- we have KM-1.1 
- we open the editor for KM-1.1 to create another  KM-fork from  KM-1.1 
- so now, we see KM-fork in the list of KMs in the KM editor list

2.
- KM-1.1 gets updated to a new version KM-1.2
- in the KMs editor list, we see a flag indicating that KM-fork can be 'updated'
- one updates KM-fork, at the end of the migration we have the publish button
- but after filling in the publish form, we realise that migration fails

3. 
- if however one publishes KM-fork with version 0.1 for example, then migration works as expected
- this is because apparently a publication after migration expects a pre-existing version, which makes sense actually...

Conclusion: Maybe KMFork should not show an 'update' flag while it hasn't yet been published, ie, doesn't have a 
version number. Or, allow this type of publication (after migration) to allow the creation of an initial version.

Thanks!

**Comment by MarekSuchanek** [comment]
I will try to reproduce this later today, sorry that we somehow skipped this one in our notifications.

**Comment by froggypaule** [comment]
many thanks @MarekSuchanek . no worries; I just happened to stumble upon this. Luckily it is not our prod site.

**Comment by MarekSuchanek** [comment]
I tried your description a few times 😄 and it worked for me... What do you mean in 2. by last step "but after filling in the publish form, we realise that migration fails"? It worked for me:

1. I had KM (v1.1.0) and KM Editor "KM-Fork" without published version
2. I updated KM (v1.2.0)
3. I upgraded "KM-Fork" and published v1.0.0 (its first version)

**Comment by froggypaule** [comment]
Hello @MarekSuchanek , would you believe it, neither can I: more precisely, if I redo the scenatio as I descrive it, the little sticker 'update available' doesn't show up. So this situation simply can't arise. So, let's assume all the intervening version updates took care of this, or I dreamed... :)

As a consequence, I close this issue.
