### ISSUE TITLE
FAIRsharing integration in Common DSW Knowledge Model

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#227]
**The Question**
Not sure it is me or... 
- take Common DSW Knowledge Model (dsw:root:2.3.0), open it in KM editor, do a preview,
go to Chapter III, 2What existing encodings/terminologies/vocabularies/ontologies will you be using?
- we get 
![Screenshot from 2021-12-14 11-21-24](https://user-images.githubusercontent.com/47455219/145980290-fadb4687-ffb8-423c-9ede-3eaa4274f516.png)

**Additional context**
I came over this while studying how to do integration.

**Comment by MarekSuchanek** [comment]
In our demo instance it works correctly. Are you sure that you have the FAIRsharing API key configured in your integration.yml file?

**Comment by froggypaule** [comment]
ach!!!  indeed no; ok, thanks! that must be in the answer. Sorry for the bother.
