### ISSUE TITLE
problems is migrating from 3.5.0 to 3.6.0

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#228]
**Describe the bug**
Upgrading from 3.5.0 to 3.6.0 (of the demo site dsw-demo.france-bioinformatique.fr) results in error.

**Context**
self managed site, uses docker on ubuntu 20.04

**How to reproduce**
Steps to reproduce the problem:
1. restore data as it was before upgrading to 3.6.0
2. all good: Questionnaire template is 2.1.0, no migration is in progress
3. shutdown, and get docker up with 3.6.0 version: I get the dreaded 'bootstrap error'
3. Logs tell me this 
![Screenshot from 2022-01-05 11-36-33](https://user-images.githubusercontent.com/47455219/148203768-6a6b2d9f-8838-4efe-8217-7008776edf13.png)

What else can I show you?
And what did I miss?
Manyt thanks.

**Expected behavior**

**Screenshots**

**DS Wizard deployment:**
 - Instance [e.g. demo.ds-wizard.org, local, or our custom]
 - Browser [e.g. chrome, safari] (inc. version, if relevant)

In case of your own instance, describe the setup, i.e., if you are using Docker or build DSW from source, what version are you using, etc.

**Additional context**

**Comment by MarekSuchanek** [comment]
Hi @froggypaule, are you sure that you upgraded 3.5.0 to 3.6.0? (Because database migration 9, that causes the issue is between 3.4.0 and 3.5.0.)

Can you access the PostegreSQL database and check table "migration"? It should look like this after the upgrade:
![image](https://user-images.githubusercontent.com/9638527/148343950-bccebbb0-8577-46ec-ae01-401df9850666.png)

(and without rows 10 and 11 before the upgrade)

**Comment by froggypaule** [comment]
Hello @MarekSuchanek : from memory, I (re)started from 3.4.0, then 3.5.0, and 3.6.0. And it is the last step that screwed things up. But, I'll do this again to make sure.
And the migration table looks like 
![Screenshot from 2022-01-06 08-28-49](https://user-images.githubusercontent.com/47455219/148345519-97bb2a82-3cb6-4ea4-ad9f-809aa1b2d235.png)


But let me do the manœuvre again, while checking this table.

**Comment by froggypaule** [comment]
So:
- stepping back to 3.4.0, I get the migration table as shown above
- migrating to 3.5.0: the migration table does NOT change (we don't see row 9), but client and server are fine 
![Screenshot from 2022-01-06 08-43-41](https://user-images.
githubusercontent.com/47455219/148348196-b952e964-35db-4b1d-86bc-9cc30b635fa6.png)

Also, the logs looks all ok....  fishy...  Thanks!

**Comment by MarekSuchanek** [comment]
> Hello @MarekSuchanek : from memory, I (re)started from 3.4.0, then 3.5.0, and 3.6.0. And it is the last step that screwed things up. But, I'll do this again to make sure. And the migration table looks like ![Screenshot from 2022-01-06 08-28-49](https://user-images.githubusercontent.com/47455219/148345519-97bb2a82-3cb6-4ea4-ad9f-809aa1b2d235.png)
> 
> Indeed, it shows that something went wrong for 3.4.0 --> 3.5.0 But let me do the manœuvre again, while checking this table.

This state is before upgrading to 3.6 right? v3.6 should only add row with migration number 11:

- 3.5.0, you should have 1 to 10 in the table
- 3.6.0, you should have 1 to 11 in the table

**Comment by froggypaule** [comment]
To clarify:
- the pic of the migration table is show after migrating to 3.6: the state I was in when I posted the bug
- since  I didn't remember what happened for 3.4.0 --> to 3.5.0, I did it all over again, and the state of the table is still the same 
![Screenshot from 2022-01-06 15-25-28](https://user-images.githubusercontent.com/47455219/148397833-06ef1c45-07fd-4acc-aae7-f7fe5d5b59ce.png)

**both pics show the same state** in other words, row 9 is missing...
so, yes, 
Yes correct, this state is before upgrading to 3.6, and after.

I hope I haven't confused you even more.... :)

**Comment by MarekSuchanek** [comment]
I figured out what could be the issue there, but totally not sure how that could happen in your deployment. It expects that the migrations will be naturally in ascending order (as it inserts them like that).

So, to fix that, could you run this SQL script that first clears the table and then inserts the migrations back in the correct order? And then please check if the rows are in correct order?

```sql
delete from public.migration where number = 9;
delete from public.migration where number = 10;

insert into public.migration (number, name, description, state, created_at) values (9, 'Admin Operations And Submission', 'Add ADMIN_PERM to admin users and enhance submission', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (10, 'Add app', 'Allow to have more app in one instance', 'DONE', CURRENT_TIMESTAMP);
```

**Comment by froggypaule** [comment]
Oh yes!!! you are right, I was so obsessed by reading the table in order that I missed that number 9 and 10 were present :(  I am tooo old for this job... 
Ok, will report here shortly.

**Comment by froggypaule** [comment]
Now, well, I end up with the same table, ie the same unordered table. Since I am not familiar with your code, why is this order important? isn't the presence of row 9 & 10 sufficient?

**Comment by MarekSuchanek** [comment]
```sql
delete from public.migration;

insert into public.migration (number, name, description, state, created_at) values (1, 'Init database', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (2, 'Project Template', 'Allow to create reusable templates for projects', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (3, 'Metrics and Phases', 'Move metrics and phases into Knowledge Model', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (4, 'Questionnaire Events Squash', 'Add flag that indicates if questionnaire events are squashed', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (5, 'Document metadata', 'Add workerLog and embed metadata into document table', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (6, 'Password Hash', 'Add information if password hash is generated by pbkdf1 or pbkdf2', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (7, 'Book Reference', 'Add book references if missing', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (8, 'Package Foreign Key and Base64', 'Remove foreign key from package and base64 for secret data', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (9, 'Admin Operations And Submission', 'Add ADMIN_PERM to admin users and enhance submission', 'DONE', CURRENT_TIMESTAMP);
insert into public.migration (number, name, description, state, created_at) values (10, 'Add app', 'Allow to have more app in one instance', 'DONE', CURRENT_TIMESTAMP);
```

The library that deals with DB migrations in your version requires the migration records to be in order... Could you try this one? It is really strange how your DB behaves...

**Comment by froggypaule** [comment]
ok it works: table is ordered, and update to 3.6.0 has been successful. How bizarre....
Many thanks!

**Comment by MarekSuchanek** [comment]
I will make an update to the migration library so it orders the records on its own (and check for missing numbers).
