### ISSUE TITLE
question or bug?

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#229]
**The Question**
DSW 3.6.0 and preview error

**DS Wizard part**
- Preview settings are given by screenshot 1.
![Screenshot from 2022-01-20 08-59-44](https://user-images.githubusercontent.com/47455219/150297216-ddb7cc9c-6f4b-4a3b-9758-6102fa0c596b.png)
- preview fails with screenshot 2. 
![Screenshot from 2022-01-20 08-57-46](https://user-images.githubusercontent.com/47455219/150297288-032c11e5-5b83-4177-af09-452ea77f22ad.png)
- logs don't show much useful, screenshot 3.
![Screenshot from 2022-01-20 08-57-27](https://user-images.githubusercontent.com/47455219/150297420-15243cc6-fc5d-4060-a687-c09a806886ba.png)

- the error is identical if set as 'template' or not.

- INTERESTINGLY, this fails with Questionnaire Report, but succeeds with output template km-insignt, screenshot 
![Screenshot from 2022-01-20 09-03-31](https://user-images.githubusercontent.com/47455219/150297679-ed4364f5-2d54-4253-83fd-87f6e5b8dd59.png)

**Additional context**
Hello @MarekSuchanek and all, 
As far as I recall I've never seen this error yet. I'ven't got a clue. Many thanks.

**Comment by MarekSuchanek** [comment]
That's strange... might be some bug when using Phases. Are you using phases in the KM? Is phase set in the Questionnaire?

**Comment by froggypaule** [comment]
- yes, Phases are used
- something strange : looking at the document as given by km-insight, I see that some questions are not given their phases, see second question on screenshot.
![Screenshot from 2022-01-20 14-43-33](https://user-images.githubusercontent.com/47455219/150350175-eba23383-7fe0-4e54-87c6-cb572f5d9988.png)

- as it happens, in the KM, the phase for these questions (not showing their phases) is set to 'Never'
- is this still possible (yes I see that it is when creating a question) ? or should the défault be 'Before the end of the project'? 
not sure...

**Comment by froggypaule** [comment]
hello @MarekSuchanek , do you have any news? sorry to bother.

So we are in DSW 3.6.0.
Playing around, I see that other projects are failing with the same error (see above) using Questionnaire Report. Preview however always succeeds with km-insight.

Another thing: Questionnaire Report with a json output succeeds; I attach it here. Many thanks.
[France Bio Imaging DMP.json.txt](https://github.com/ds-wizard/ds-wizard/files/7931649/France.Bio.Imaging.DMP.json.txt)

**Comment by froggypaule** [comment]
@MarekSuchanek : I have good news: I have updated our site to 3.7.0, and everything behaves normally. Quite bizarre? Anyway I won't clode this as yet, just in case there is something more to add....
Ta!

**Comment by MarekSuchanek** [comment]
@froggypaule Sorry, I was stuck with some other things and missed the notifications. Glad that the upgrade helped... It should not happen since 3.7.0 (some changes in document worker handling phases). But in 3.8.0 it will be even more enhanced (internally it will use "Never phase" instead of null value - to avoid missed checks if it is real phase or null).

**Comment by froggypaule** [comment]
Don't worry Marek; we are all extremely busy :) 
Ok, let's forget this (bug). Have a great day.
