### ISSUE TITLE
Feature or small fix or bug?

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#230]
The context is that of a self admin DSW instance. There are two issues I wan to mention, all to do with output templates and versioning.

1. The situation is as follows:
- assume that the DSW version is 3.6.0, ie not the latest
- in templates, we see that all/most have a sticker 'update available'
- when choosing say 'Questionnaire Report' we'll attempt to import V2.4.0 which won't succeed since V2.4.0 matches DSW 3.7.0 only.
This is a annoying, and ideally, this 'update available' should not show since we have the correct template version for the current DSW version.

2. This also relates to output templates:
- we are in 3.6.0, and our project is set to be previeweb with 'Questionnaire Report 2.3.0'
- we upgrade to 3.7.0, and consequently we also upgrade 'Questionnaire Report' to 2.4.0
- our project still shows its preview setting to be 'Questionnaire Report 2.3.0': ideally some warning should be given that this needs updating also.
From memory, there is no such thing, and one has to remember to go through all the projects to update the template version.
Is this correct? or do I get it wrong?

Many thanks!

**Comment by MarekSuchanek** [comment]
I agree, I created two issues in our backlog in JIRA: DSW-1274 and DSW-1275

**Comment by froggypaule** [comment]
Thank you :) I close this then!
