### ISSUE TITLE
dangling link in doc

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#231]
**Describe the bug**
this link https://github.com/ds-wizard/dsw-schemas/blob/master/schemas/doc-context/doc_context_schema_v7.json goes nowhere.

**Where**
https://guide.ds-wizard.org/miscellaneous/development/metamodel-schemas

thanks!

**Comment by froggypaule** [comment]
thanks :)

**Comment by MarekSuchanek** [comment]
It is there now...

**Comment by froggypaule** [comment]
Ha! found another one: https://jinja.palletsprojects.com/en/master/templates/
Not you fault.
