### ISSUE TITLE
in document_worker/model/context.py

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#233]
**Describe the bug**
in document_worker/model/context.py, class KnowledgeModel:

we read:
```python
    def _resolve_links(self, ctx):
        self.phases = [ctx.e.phases[key]
                       for key in self.phase_uuids
                       if key in ctx.e.metrics.keys()]
 ```
 
of course, the last statement should read f key in ctx.e.phases.keys()

this explains why doing 
    {{ dc.km.phases }}  I get an empty list

while 
    {{ dc.km.phase_uuids }} correctly gives the uuid list....

**Comment by froggypaule** [comment]
Indeed, this is what I did. One day I would like to talk to you re the context model, a few things puzzle me. But this will be for another day :)

I

**Comment by froggypaule** [comment]
Good  morning @MarekSuchanek : actually I am in the process of 'rewriting' km-insight in order to use the recent to_context_obj object. Useful to get me learning.

About the question I have: in a few of the classes as given by the context, for example KnowledgeModel we see fields like chapter_uuids and chapters,etc. I suspect this for legacy/compatibility purposes?
And I suspect the same applies to having both dc.km.e.chapters and dc.km.phases (for example)? 
Ta!

**Comment by MarekSuchanek** [comment]
Yes, the object-oriented context basically extends the structure of the "JSON" like. It just adds the links for easier navigation through KM and replies. There are certain shortcuts... It is quite complex (I hope the diagram in docs is at least a bit useful in this).

In `dc.km.e` (or `dc.km.entities` are all entities in dict-like form, so you can retrieve entities using its UUID), e.g., `dc.km.e.chapters[<uuid>]`. But on an entity, related entities are in lists... so `dc.km.chapters` is a list of chapters in the specific order.

**Comment by froggypaule** [comment]
Thanks Marek for these clarifications. And indeed, the diagram helps a lot!
I'll close this now. Cheers.
