### ISSUE TITLE
Can not start docker local instance (commit "release 3.8")

### ISSUE THREAD

**Issue by aleolivo** [ds-wizard/ds-wizard#235]
**Describe the bug**
An error occurred starting the local instance "dsw-deployment-example" with docker-compose last commit  "release 3.8"

**How to reproduce**

``` shell
git clone https://github.com/ds-wizard/dsw-deployment-example.git
cd dsw-deployment-example
docker-compose up -d
```

**Screenshots**
The error:
``` shell
Creating network "dsw-deployment-example_default" with the default driver
Pulling dsw-server (datastewardshipwizard/wizard-server:3.8)...
ERROR: manifest for datastewardshipwizard/wizard-server:3.8 not found: manifest unknown: manifest unknown
```

**DS Wizard deployment:**
 - Docker local instance version 3.8

**Comment by vknaisl** [comment]
Hello Alessandro,

Try it now. We were releasing 3.8.0 today. Therefore, the backend didn't have to be yet built. Let me know if it works for you now.

Regards,
Vojtech

**Comment by aleolivo** [comment]
Great, now it works! Thanks
