### ISSUE TITLE
rewritten km-insight

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#236]
**The Question**
I have rewritten the km-insight templates so that they use the new context object to_context_obj filter; if you are interested, I 1) can either commit the branch in the km-insight repo, or 2) send you the zip file

**DS Wizard part**
km-insight

**Additional context**
- I didn't change anything to the code as is, except anything following the changing approach
- I did not do the Annotations; I have a pb with them, and I post another question in this respect

**Comment by froggypaule** [comment]
Following the above, I tweaked the KM Insight template to make it more user-friendly. Ie whose purpose is the review, sharing, of the created knowledge model.
Basically with in mind the original request of Libby I believe. Attached here is an example. 
[testing-CKM-with-paulettes-new-templates.pdf](https://github.com/ds-wizard/ds-wizard/files/7995792/testing-CKM-with-paulettes-new-templates.pdf)
 
 Ok, it is not perfect, but maybe it can be shared? put in the registry? 
 What do you think?

**Comment by MarekSuchanek** [comment]
Looks good... are you working on that in fork/branch?

**Comment by froggypaule** [comment]
Hello @MarekSuchanek : I don't have the access rights; again I happily send the zip files, or I push a branch here. Ta.

**Comment by froggypaule** [comment]
Hello again; I post here the zip files for both branches. Let me know if you need anything else.
[user-friendly-km-insight-template.zip](https://github.com/ds-wizard/ds-wizard/files/8024153/user-friendly-km-insight-template.zip)
[km-insight-template-rewritten.zip](https://github.com/ds-wizard/ds-wizard/files/8024154/km-insight-template-rewritten.zip)

**Comment by MarekSuchanek** [comment]
Hi @froggypaule, I finally managed to look at your templates... it looks fine both visually and in the code. I did not find any issue while looking at it now. If you could create Pull Request(s) in the repo https://github.com/ds-wizard/km-insight-template, that would be great. But definitely no need to rush 🙂

**Comment by froggypaule** [comment]
Hello @MarekSuchanek , the only thing missing are the annotations. 
A PR? but I can't push a branch here, last time I tried, I didn't have access to this repo.

**Comment by MarekSuchanek** [comment]
You can create a fork and then submit a PR whenever ready, that is the best way to contribute using GitHub: 
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
https://jarv.is/notes/how-to-pull-request-fork-github/

**Comment by froggypaule** [comment]
ok, will do this. Cheers.

**Comment by froggypaule** [comment]
hihi! you wouldn't believe it but I actually never did a git fork before.... ;)

Well, it's all done now,
