### ISSUE TITLE
project migration

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#239]
**The Question**
Originally when a project was migrated to a new newer KM version, the existing project was kept. This is no longer the case. Since when is this the case?

Apparently, this migration is not reflected in the project's versions.... Did I miss something? how to manage/view these different project 'versions'?

**Comment by MarekSuchanek** [comment]
This behaviour was introduced in 3.9 as it is desirable to keep the same UUID of a project even when it is migrated. If people want they can create a backup copy using the "Clone" action.

Migrations do not affect "versions" (yet), it just migrates the existing replies... in the future, there might be "migration" captured in the version history, but that is a next potential step.

**Comment by froggypaule** [comment]
ok, I see, thanks; I'll remember this. Cheers!

**Comment by froggypaule** [comment]
I reopen this: actually I see a problem with this. Suppose we forgot to clone the project, is there a simple way to revert the migration? except from reverting each item in the latest version?

**Comment by MarekSuchanek** [comment]
That is true, reverting is not possible... in ideal state it could be part of the "version history" inside project. I added it here as it is a feature request: https://ideas.ds-wizard.org/posts/14/improve-questionnaire-migration

**Comment by froggypaule** [comment]
Reopened this, I copy here my thoughts from [dsw ideas 14](https://ideas.ds-wizard.org/posts/14/improve-questionnaire-migration):

Actually, one can revert after migration (or am I wrong???)

1.    suppose I do a project migration
2.     all the changes involved in the migration show in 'version history'
3.     later, if I revert to the change occurring just before (in chronological order) then I would have effectively reverted back to prior the migration
4.     if I name this change before hand, this process is of course easier

all in all, the user experience is not optimal,  but reverting project migration is possible.
