### ISSUE TITLE
cookies in self managed instance

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#240]
**The Question**
Hello all!
I am revisiting our terms of service and privacy document. 
I need to know if a self-hosted DSW instance manages some cookies; I guess yes. 
Can you tell me more? I need to detail the situation in this respect, as all our IFB sites are in the process of being registered with our DPO. 
Many thanks.

**Comment by MarekSuchanek** [comment]
Hi @froggypaule, DSW uses local storage but I guess that is mostly considered as the same as cookies (esp. in terms of law).

Eventually @janslifka, can you provide additional info?

**Comment by janslifka** [comment]
As @MarekSuchanek said, DSW uses local storage. Under the `session` key we store information like this:

```
{
    "token": {
        "token": "eyJh..."
    },
    "user": {
        "uuid": "d0078bda-8034-4d5f-8a44-3068615a6e39",
        "email": "jan.slifka@gmail.com",
        "firstName": "Jan",
        "lastName": "Slifka",
        "role": "admin",
        "permissions": [
            "UM_PERM",
            "KM_PERM",
            "KM_UPGRADE_PERM",
            "KM_PUBLISH_PERM",
            "PM_READ_PERM",
            "PM_WRITE_PERM",
            "QTN_PERM",
            "DMP_PERM",
            "CFG_PERM",
            "SUBM_PERM",
            "TML_PERM",
            "DOC_PERM",
            "QTN_TML_PERM",
            "ADMIN_PERM"
        ],
        "imageUrl": "https://lh3.googleusercontent.com/a-/AOh14Gh9kWMjgZJvqwc2uTV5_gK4B0WqKyxRu2a4ZvOZlQ=s96-c"
    },
    "sidebarCollapsed": false,
    "fullscreen": false,
    "v6": true
}
```

**Comment by froggypaule** [comment]
Ok, thanks @janslifka et @MarekSuchanek . Sorry, but
- it seems there are still cookies (see 
![Screenshot from 2022-03-24 10-13-58](https://user-images.githubusercontent.com/47455219/160095687-f8022928-292a-4211-b0d6-bad5e5bbeef6.png)
- but for me, I do not understand how this interacts with the GDPR. Any pointer from your part?

**Comment by janslifka** [comment]
But `france-bioinformatique.fr` is not the domain where DSW Instance runs, is it? I expect it to be running on some subdomain? Those cookies are most likely related to the website running on that domain, such as Google Analytics cookies, maybe?

**Comment by froggypaule** [comment]
correct, but it does not show the subdomain (firefox)... I have nothing else open. I'll try with Chrome.

**Comment by janslifka** [comment]
Can you see what those cookies actually are? In Firefox inspector, I can see this:

![Screenshot 2022-03-25 at 11 54 39](https://user-images.githubusercontent.com/7797976/160108213-c17892c3-c81a-4e4a-87ed-db05c166b797.png)

**Comment by froggypaule** [comment]
Sorry, but I am out of my depth here :(
In chrome it correctly shows local storage only. So  for the cookies, no clue: firefox inspector also shows (for me) none exists. I do not see what you show here. 
Let's decide to forget this, and correctly decide there are no cookies concerning DSW. I thank you for your time.

(it's possibly related to the fact that on firefox I have ghostbuster add-on...)

**Comment by froggypaule** [comment]
Actually, I have to reopen this issue :(
Besides cookies, does DSW (server) store connection data (IP address etc.... ) ? if yes, which data items?
-- Still answering to the CNIL request.

Thanks again!

**Comment by MarekSuchanek** [comment]
DSW itself does not store connection data... if you are using some HTTP/S proxy, it may store/log such information, but that depends of the deployment 🤷🏻‍♂️

**Comment by froggypaule** [comment]
ok thanks. Sorry for the (stupid?) question. Cheers.
