### ISSUE TITLE
export a KM in Json ?

### ISSUE THREAD

**Issue by MalikaSmail** [ds-wizard/ds-wizard#241]
**The Question**
Is it still possible to export a KM in JSON for further editing ? 

**DS Wizard part**
knowledge model 

**Additional context**
I only can export in km format

**Comment by MarekSuchanek** [comment]
It is possible in the `.km` format, which is event-based JSON. However, it is not recommended as you need to take care about several special cases related to the order in which some events affect each other. What is your exact case for needing this (and cannot do it directly in DSW KM Editor)?

This might be related: https://ideas.ds-wizard.org/posts/54/programmatically-create-kms
