### ISSUE TITLE
Cannot create Documents in Science Europe DMP Template

### ISSUE THREAD

**Issue by BioDataAdmin** [ds-wizard/ds-wizard#243]
**Describe the bug**
Cannot create Documents in Science Europe DMP Template

**How to reproduce**
Steps to reproduce the problem:
1. Go to any project 
2. Click on "Documents"
3. Click on "New document"
4. Select "Science Europe DMP Template"
5. Select any Format and click "Create"
6. The "document" is created with an "error" tag and cannot be opened

**Expected behavior**
Following the same steps, the created document should not have the "error" tag and should be possible to download/opened.

**DS Wizard deployment:**
 - Instance [biodata-pt.ds-wizard.org]  v3.9.0~fc5b47b
 - Browser [chrome]

**Comment by MarekSuchanek** [comment]
Hi @BioDataAdmin, I fixed the templated and updated it in your instance... Could you please verify if it is working well for you now? (Use v1.10.1 of the Science Europe template.)

**Comment by BioDataAdmin** [comment]
Woow...that was fast. Yes it is working now. Thank you!
