### ISSUE TITLE
Unable to get km-editor???

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#244]
**Describe the bug**
Cannot get to the km-editor. 
![Screenshot from 2022-03-30 14-59-52](https://user-images.githubusercontent.com/47455219/160840652-add22bd4-99b9-4840-956b-9f7209d75236.png)
and 
![Screenshot from 2022-03-30 15-01-16](https://user-images.githubusercontent.com/47455219/160840693-b9746057-4cbe-44bd-94d0-d8d863ae82b0.png)

This is on self-installed dsw-demo.france-bioinformatique.fr, uptodate, see 
![Screenshot from 2022-03-30 15-04-30](https://user-images.githubusercontent.com/47455219/160840968-155e963e-a231-489e-941a-e265da74f010.png)

**How to reproduce**
Steps to reproduce the problem:
- I can open & create the editor for any KM, it shows properly, after modifications I can also publish a new version. 
- however, it is not possible to access all KMs opened in the editor
I am totally lost, not clue whatsoever what happened.

This instance is hardly used, the last time it was for testing output templates, and I didn't notice anything.....

**Comment by froggypaule** [comment]
In case you are interested, I believe several of you are actually admin on this site, see 
![Screenshot from 2022-03-30 15-17-08](https://user-images.githubusercontent.com/47455219/160844029-59352b9e-2b57-4f03-913d-94300e905aff.png)

**Comment by MarekSuchanek** [comment]
I managed to login into the instance and all editors in https://dsw-demo.france-bioinformatique.fr/km-editor works for me... did you manage to overcome this issue or was it solved by upgrading to the latest version?

**Comment by froggypaule** [comment]
Hello Marek: sorry, we should have updated this. @vknaisl helped me solve this via slack.
The answer was there was a row in the km_migration table: after clearing the table, everything went back to normal. (no clue as to what happened).
