### ISSUE TITLE
Documents have much less information than in the DMP

### ISSUE THREAD

**Issue by BioDataAdmin** [ds-wizard/ds-wizard#245]
Describe the bug
Documents have much less information than in the DMP

How to reproduce
Steps to reproduce the problem:

Go to any project
Click on "Documents"
Click on "New document"
Select "any DMP Template"
Select any Format and click "Create"
The document is very small when compared to the DMP and does not contain information on project participants, datasets, etc 
Expected behavior
Following the same steps, the created document should have all the information filled in the DMP.

DS Wizard deployment:

Instance [biodata-pt.ds-wizard.org] v3.9.0~fc5b47b
Browser [chrome]

**Comment by MarekSuchanek** [comment]
Hi @BioDataAdmin, what DMP template do you mean exactly?

There is the "questionnaire report" that outputs everything from the questionnaire. Then, there are some templates based on e.g. Horizon EU template or maDMP - there are only the information that we matched as relevant to addressing required stuff in the template.
