### ISSUE TITLE
dsw-tdk and metamodel 9 (this is also in the release slack)

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#246]
**Describe the bug**
dsw-tdk 3.10.0 does not like metamodel V9. see 
![Screenshot from 2022-04-06 14-12-52](https://user-images.githubusercontent.com/47455219/161976988-6650360c-14a2-40fd-9cb0-8f344481cd6f.png)

but the answer could be here: 
![Screenshot from 2022-04-06 14-29-01](https://user-images.githubusercontent.com/47455219/161977083-5ae5fefa-cee1-4c7b-ac01-e4dbb7bebedb.png)
that is, after installing dsw-tdk 3.10.0, its version still says it is 3.8.0.....

**Comment by MarekSuchanek** [comment]
Are you using some virtual environment or installing TDK system wide? What is the output for `pip freeze | grep dsw-tdk` and `python -m pip freeze | grep dsw-tdk` (alternatively `python3`)... it may be the case that you have multiple versions of Python and there is a clash between them, making 3.8.0 not being uninstalled and having the preference 🤷🏻‍♂️

**Comment by froggypaule** [comment]
Spot on Marek 
![Screenshot from 2022-04-06 15-55-24](https://user-images.githubusercontent.com/47455219/161991288-5788a4bf-f73f-426c-bd41-69dac1fa578b.png)

thanks. sorry for this (I should brush up my python.... ;) )
