### ISSUE TITLE
Unable to import template

### ISSUE THREAD

**Issue by thopico** [ds-wizard/ds-wizard#249]
**Describe the bug**
When trying to import _Questionnaire Report_ from DSW registry, got
```
Unable to import the template.
```
When trying to import _Questionnaire Report_ from this file (https://github.com/ds-wizard/questionnaire-report-template/blob/master/template.json), got
```
Importing the template failed.
```
When trying to import _Questionnaire Report_ from all the zip archive (https://github.com/ds-wizard/questionnaire-report-template), got
```
"template.json" was not found in archive.
```

Tried with version 2.6.0

**How to reproduce**
Steps to reproduce the problem:
1. Go to '/templates' endpoint (last item on left navigation bar)
2. Click on 'import'
3. Enter the template ID or click on 'From file' tab

**Expected behavior**
Template should be imported just as it works for knowledge models (tested it, it works).

**DS Wizard deployment:**
 - Instance : self-hosted with docker and kubernetes. DSW client : `v3.10.2~96f32cb`, DSW server : `v3.10.1~3791ce2b`
 - Browser : firefox

**Comment by MarekSuchanek** [comment]
Hello @thopico, are you importing from registry `dsw:questionnaire-report:2.6.0`? If so, can you check wizard-server logs at that point?

**Comment by thopico** [comment]
Yes :
```
[Info ] [I:f0ac0965-6da3-4e4f-a305-d205942302f1] [T:8a7955e8-ce22-4766-89a0-68edd11777ab] [S3 ] Put object: 'templates/dsw:questionnaire-report:2.6.0/29d8c9e0-b95a-49f8-8a21-1ef12a317b30'
[Info ] [I:f0ac0965-6da3-4e4f-a305-d205942302f1] [T:8a7955e8-ce22-4766-89a0-68edd11777ab] [S3 ] MErrService NoSuchBucket
[Info ] [I:f0ac0965-6da3-4e4f-a305-d205942302f1] [T:8a7955e8-ce22-4766-89a0-68edd11777ab] [Database ] Transaction rollback
[Error] [I:------------------------------------] [T:------------------------------------] [API ] Error in s3 connection: MErrService NoSuchBucket
[Error] [I:f0ac0965-6da3-4e4f-a305-d205942302f1] [T:------------------------------------] [API ] 500 Internal Server Error POST /templates/dsw:questionnaire-report:2.6.0/pull
```

**Comment by thopico** [comment]
Sorry for disturbing you, it seems to be a problem with the minio bucket. I didn't read this info from [the README](https://github.com/ds-wizard/dsw-deployment-example/blob/main/README.md):
> You have to create S3 bucket, either using Web UI (for Minio, you can expose and use http://localhost:9000) or via client: https://docs.min.io/docs/minio-client-complete-guide.html#mb, e.g. use create-bucket.sh script.

Now it is working!
