### ISSUE TITLE
Create documents template not working

### ISSUE THREAD

**Issue by BioDataAdmin** [ds-wizard/ds-wizard#251]
**Describe the bug**
Document templates are not loading, so cannot create any document

**How to reproduce**
Steps to reproduce the problem:
1. Go to any project-> documents-> create 
2. Click on The dropdown of the templates, the dropdown shows no options

**Expected behavior**

**Screenshots**

**DS Wizard deployment:**
 - Instance https://biodata-pt.ds-wizard.org/

**Comment by MarekSuchanek** [comment]
I updated the templates in your instance, sorry for the inconvenience. Can you please check now?
