### ISSUE TITLE
cannot import km

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#252]
**The Question**
I am sorry: I think I must be crazy:

- I export a km from one instance of DSW
- I cannot export it on another !!!

Both are at 3.12.0, with server at 3.12.1.

I'll send the offending km by mail due to RGDP issues. Actually I can't import anything...
I would appreciate if someone could pick what I did wrong.... :(  
See also 
![Screenshot from 2022-06-16 17-19-52](https://user-images.githubusercontent.com/47455219/174104055-8e925e20-e571-4d6d-811d-84d17753de96.png)

Thanks!!

**Comment by MarekSuchanek** [comment]
Hi @froggypaule, could you also provide part of the server logs from the time when the import fails? There should be an error message.

For me (local deployment) I am able to import the KM you sent me without any issues. Are you sure that the target server is running the correct version?

![image](https://user-images.githubusercontent.com/9638527/174238027-448f9149-b488-4f47-843a-b21bcfee66b0.png)

**Comment by froggypaule** [comment]
Hello @MarekSuchanek and thanks. Attached are two files; screenshot re versions, and log file. Honestly I couldn't see a thing. I must have done something odd, since our pro instance behaves in the same way. The question is what???
![Screenshot from 2022-06-17 08-36-06](https://user-images.githubusercontent.com/47455219/174240013-1cf5077b-8cde-48ae-a1e9-77a53c7e9f9e.png)
[dsw_dsw-server_1.out.txt](https://github.com/ds-wizard/ds-wizard/files/8925088/dsw_dsw-server_1.out.txt)

Thank you!

**Comment by froggypaule** [comment]
The thing of note I did on both instances is to reinstall dsw by dowloading/configuring the dsw-deployment-example; that was to fix the mailer issue which ceased working at the time. Attached are the yml files, just in case. Ta. (I send dsw.yml by mail for privacy reasons).
[docker-compose.yml.txt](https://github.com/ds-wizard/ds-wizard/files/8925225/docker-compose.yml.txt)

**Comment by MarekSuchanek** [comment]
I remembered that I have access to this instance... When you upload the file, the server responds with 413. It seems like your proxy limits max file size or max request size; then it won't even reach the backend of DSW.

Can you check your proxy settings? 
For nginx, you can follow e.g. this one: https://docs.rackspace.com/support/how-to/limit-file-upload-size-in-nginx/

![image](https://user-images.githubusercontent.com/9638527/174342217-507b7059-30e7-40fc-a49f-9641d37c5fec.png)

**Comment by froggypaule** [comment]
suber @MarekSuchanek , you are brilliant!!! that was the answer. If only I had the F12 reflex more often. 

Solved!!!
