### ISSUE TITLE
km editor unable to save: help

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#254]
I have a problem (DSW 3.13) with firefox:

I am doing a lot of editing on a KM, and DSW struggles to save the changes. The logs don't show a thing..., but F12 does (ha! I remembered doing this) :
![Screenshot from 2022-07-01 14-21-46](https://user-images.githubusercontent.com/47455219/176895527-a11b98e1-0c41-40f9-8918-741fe210ddb2.png

however, I did a nginx restart, the above error doesn't show any but longer, DSW is still stuck and is unable to save...

**Comment by froggypaule** [comment]
ok chrome works :(

**Comment by janslifka** [comment]
Hello, what version of Firefox and what OS do you use when this happens?

**Comment by froggypaule** [comment]
I'll close this; if this an issue in the future, I'll come back here.
