### ISSUE TITLE
a question wrt forking of kms

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#255]
**The Question**
The most amazing thing happened (wrt to forking of kms): I managed to rebase a km!!! 
Ok, let me explain.

First, the general context:

- there is a specialised km for bioimagery IFB:bioimage-fbi-embrc-pgd-structure-km:1.4.17
- I want to fork this one into a generic IFB:pgd-structure-km and I publish it as IFB:pgd-structure-km:0.0.1
- then I wish to rebase the  specialised km for bioimagery IFB:bioimage-fbi-embrc-pgd-structure-km:1.4.17 on  IFB:pgd-structure-km:0.0.1 and publish it as IFB:bioimage-fbi-embrc-pgd-structure-km:1.4.18

I agree, this sounds crazy, but I was experimenting with ways to rebase a specialised km, simply because in the future, I really want to develop the 'generic' one, and then incorporate  specific modifications from the generic km into the specialised km. Given that at the start I only have the specialised km, I thought about something  along the lines above.
It sounds crazy because in effect I 'recycle' a km ID which shouldn't be possible without erasing first all traces of IFB:bioimage-fbi-embrc-pgd-structure-km.

You will not believe this, but I managed to do it!!!! 

![Screenshot from 2022-08-17 15-54-56](https://user-images.githubusercontent.com/47455219/185152353-c745a70a-21f9-42fd-8926-13d42e47177a.png)

**Comment by froggypaule** [comment]
Below I'll explain how this came about. Yes, you would expect this not to be possible since a km id cannot be reused...

**Comment by froggypaule** [comment]
Oh no!!! I lost it all...
starting again:

- step 1
-- we start with IFB:bioimage-fbi-embrc-pgd-structure-km:1.4.17
![Screenshot from 2022-08-17 16-06-18](https://user-images.githubusercontent.com/47455219/185157779-14f37010-e4f4-417a-9cb6-32d2343ac101.png)
-- note that there is an unpublished modification
![Screenshot from 2022-08-17 16-05-54](https://user-images.githubusercontent.com/47455219/185157984-9dbf5c80-43a2-433a-90fb-e56b55b48286.png)
-- in settings, we modify its title and ID to Modèle de PGD structure & pgd-structure-km, after saving we have
![Screenshot from 2022-08-17 16-10-31](https://user-images.githubusercontent.com/47455219/185158615-99a12329-02de-491e-915e-c63b9b2b5663.png)

- Step 2
-- note that we still need to publish the modification mentioned above 
![Screenshot from 2022-08-17 16-24-40](https://user-images.githubusercontent.com/47455219/185159424-2be0a0fc-12bf-4213-b4c5-5866d85b6597.png)
-- we publish it as IFB:pgd-structure-km:0.0.1
![Screenshot from 2022-08-17 16-28-07](https://user-images.githubusercontent.com/47455219/185160383-ec9bbfe6-3a4e-4aea-8c0f-45e9887bc903.png)

**Comment by froggypaule** [comment]
- step 3
-- we fork  IFB:pgd-structure-km:0.0.1 as bioimage-fbi-embrc-pgd-structure-km
![Screenshot from 2022-08-17 16-31-19](https://user-images.githubusercontent.com/47455219/185161513-61b9ef02-686e-4684-bc45-4163f35e6e3b.png)

This shouldn't be possible right since id bioimage-fbi-embrc-pgd-structure-km already exists right?
-- we publish this fork ... as bioimage-fbi-embrc-pgd-structure-km:1.4.18
![Screenshot from 2022-08-17 16-35-10](https://user-images.githubusercontent.com/47455219/185163487-6095eedd-d7f6-4e7e-8a3e-cd952cbc2947.png)

- step 4
-- finally, for the sake of it, I modify IFB:pgd-structure-km:0.0.1 tp publish it as IFB:pgd-structure-km:0.0.2
-- and here we go!!! 
![Screenshot from 2022-08-17 16-41-23](https://user-images.githubusercontent.com/47455219/185167025-ce15e290-c395-466a-b823-c2f7211b3e6e.png)


a circle!!!! 
I leave this to your perusal: btw, you have access to the site dsw-demo.france-bioinformatique.fr, where I played this little game

**Comment by froggypaule** [comment]
Actually, thinking ot it, couldn't we think such a situation desirable?

- I may want to integrate modifications from the generic into the specific
- but I might also want to incorporate  modifications from the specific into the generic

What are your thoughts???

**Comment by froggypaule** [comment]
So, I am honestly mystified. 
Repeating this game with other kms, sometimes I manage to reproduce this 'rebase', sometimes not (but this is what would be expected) with 
![Screenshot from 2022-08-18 10-55-37](https://user-images.githubusercontent.com/47455219/185354403-7a1cdfe8-367c-433e-b28b-e17b6f2d3325.png)


I send you by mail another rebase that worked (because of gdpr).

**Comment by MarekSuchanek** [comment]
This has been a long time, sorry... basically, there are many things possible to achieve if you "play" with KMs and the dependency tree and versions. Of course, you can get into some not-intended states which may be useful for some use cases. I think this is also related to this one: https://ideas.ds-wizard.org/posts/24/merge-changes-from-a-branch-back-into-the-trunk

So, I am linking this issue there as example what can be done somehow. But currently the parent-child should be used only in a tree (no cycles).
