### ISSUE TITLE
Documents and/or previews are not created after upgrading

### ISSUE THREAD

**Issue by jokermanse** [ds-wizard/ds-wizard#256]
When generating a preview and/or creating a document, the document is never generated, i.e. the page is just "Loading..." (or "Queued...") forever. No error messages.

Our instance run version 3.14.1 (this might have occured in 3.13 as well, but not in previous versions).

From the docker logs:

dsw-server-staging  | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:------------------------------------] [API         ] 202 Accepted GET /questionnaires/5aa785b7-36f9-4c03-974c-009af36f52a2/documents/preview

nginx-staging       | 172.29.0.1 - - [18/Aug/2022:11:07:02 +0000] "GET /questionnaires/5aa785b7-36f9-4c03-974c-009af36f52a2/documents/preview HTTP/1.1" 202 24 "https://dsw-staging.ita.chalmers.se/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "129.16.31.71"
document-worker-staging  | 2022-08-18 11:07:02,858 |    DEBUG | docworker: [T:4d936598-4dfb-4841-8caf-5fac0dae473f] Trying to fetch a new job
document-worker-staging  | 2022-08-18 11:07:02,860 |    DEBUG | docworker: [T:4d936598-4dfb-4841-8caf-5fac0dae473f] Fetched 0 jobs

dsw-server-staging       | [Info ] [I:00000000-0000-0000-0000-000000000000] [T:df8da908-e395-4e8b-b86e-f551df835e92] [Database    ] SELECT * FROM app WHERE uuid = '00000000-0000-0000-0000-000000000000'  
dsw-server-staging       | [Debug] [I:------------------------------------] [T:e941e07c-8900-4e2c-8061-ce9ae770b444] [Cache       ] Get (before): 'User', key: { uuid: '7e2925a6-3e9f-4226-bcaa-4c18ea216933' }
dsw-server-staging       | [Debug] [I:------------------------------------] [T:e941e07c-8900-4e2c-8061-ce9ae770b444] [Cache       ] Get (found): 'User', key: { uuid: '7e2925a6-3e9f-4226-bcaa-4c18ea216933' }
dsw-server-staging       | [Info ] [I:00000000-0000-0000-0000-000000000000] [T:d9702641-79d6-4b02-9013-f275696ce1c1] [Database    ] SELECT * FROM app WHERE uuid = '00000000-0000-0000-0000-000000000000'  
dsw-server-staging       | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Database    ] Transaction started
dsw-server-staging       | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Database    ] SELECT * FROM questionnaire WHERE app_uuid = '00000000-0000-0000-0000-000000000000' AND uuid = '5aa785b7-36f9-4c03-974c-009af36f52a2'  
dsw-server-staging       | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Database    ] SELECT uuid, 'UserMember' AS member_type, text(user_uuid) AS member_id, perms, questionnaire_uuid  FROM questionnaire_acl_user  WHERE questionnaire_uuid = '5aa785b7-36f9-4c03-974c-009af36f52a2'   UNION  SELECT uuid, 'GroupMember' AS member_type, group_id AS member_id, perms, questionnaire_uuid  FROM questionnaire_acl_group  WHERE questionnaire_uuid = '5aa785b7-36f9-4c03-974c-009af36f52a2' 
dsw-server-staging       | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Database    ] SELECT * FROM document WHERE app_uuid = '00000000-0000-0000-0000-000000000000' AND questionnaire_uuid = '5aa785b7-36f9-4c03-974c-009af36f52a2' AND durability = 'TemporallyDocumentDurability' 
dsw-server-staging       | [Debug] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Cache       ] Get (before): 'Questionnaire Content', key: { lastEventUuuid: 'e769974c-03a7-42cf-89ac-4878202a91ea' }
dsw-server-staging       | [Debug] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Cache       ] Get (found): 'Questionnaire Content', key: { lastEventUuuid: 'e769974c-03a7-42cf-89ac-4878202a91ea' }
dsw-server-staging       | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Database    ] SELECT * FROM app_config WHERE uuid = '00000000-0000-0000-0000-000000000000'  
dsw-server-staging       | [Debug] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Service     ] Replies hash: -7900341527792319948
dsw-server-staging       | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Service     ] Waiting to generation
dsw-server-staging       | [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:40da7a6f-5c0e-4ef2-bc9b-70473571c8e5] [Database    ] Transaction committed
...

The wizard-server transactions are repeated until the app is closed.

This occurs with all (updated) templates - for example dsw:questionnaire-report:2.7.1 - and every output format. The upgrade 3.13 -> 3.14 was done according to the guidelines.

Any hints on what to look for would be really appreciated. Many thanks!

**Comment by MarekSuchanek** [comment]
Heelo @jokermanse, can you please check whether docworker component is running and check the logs from that service? It seems like it is not running or not connecting properly to the database.

**Comment by jokermanse** [comment]
Hello @MarekSuchanek 
docworker is running, but I don't get much from the docker logs, just a lot of:
document-worker-staging  | 2022-08-19 09:03:34,602 |    DEBUG | docworker: [T:9bbeb869-400c-4857-8f04-58f67b2d7af5] Trying to fetch a new job
document-worker-staging  | 2022-08-19 09:03:34,604 |    DEBUG | docworker: [T:9bbeb869-400c-4857-8f04-58f67b2d7af5] Fetched 0 jobs

I noticed when attempting a rollback of that there are differences when the docker containers are initially created, i.e:

3.13.1
document-worker-staging  | 2022-08-19 08:54:51,160 |     INFO | docworker: [T:-] Preparing PostgreSQL connection for QUERY
document-worker-staging  | 2022-08-19 08:54:51,160 |    DEBUG | docworker: [T:-] Starting call to 'document_worker.connection.database.PostgresConnection._connect_db', this is the 1st time calling it.
document-worker-staging  | 2022-08-19 08:54:51,160 |     INFO | docworker: [T:-] Creating connection to PostgreSQL database "query"

3.14.1
document-worker-staging  | 2022-08-19 09:03:34,601 |     INFO | docworker: [T:-] Preparing command queue
document-worker-staging  | 2022-08-19 09:03:34,602 |    DEBUG | docworker: [T:9bbeb869-400c-4857-8f04-58f67b2d7af5] Trying to fetch a new job
document-worker-staging  | 2022-08-19 09:03:34,604 |    DEBUG | docworker: [T:9bbeb869-400c-4857-8f04-58f67b2d7af5] Fetched 0 jobs

No mention of postgres in the logs. Maybe this is fine, or is it indicating that something as changed (maybe on our side)?

The upgrade to 3.14 was done according to the guidelines, I believe, i.e. by disabling docworker and mailer on the first run to ensure that all migrations were run.
Is there something more we could test or look for here? Is there any way to test/debug the docworker postgres connection?

**Comment by MarekSuchanek** [comment]
That seems fine... are you using the correct PostgreSQL DB? What is the version of it? Do you have the same configuration for server and docworker?

If possible, you should be able to check queued document generation commands via:

```sql
SELECT * FROM persistent_command WHERE component = 'doc_worker' AND state = 'NewPersistentCommandState';
```

If there are none, then docworker has nothing to work on... if there are some, your docworker cannot reach them for some reason.

**Comment by jokermanse** [comment]
PostgreSQL version is 13.6 (on RHEL 8.5). Same config for server and docworker.

The query above returns 11 records, such as:

```
            state           | component  | last_error_message |     function     | component  | attempts | max_attempts |               app_uuid               |              created_by              |          created_at           |          updated_at           | internal 
---------------------------+------------+--------------------+------------------+------------+----------+--------------+--------------------------------------+--------------------------------------+-------------------------------+-------------------------------+----------
 NewPersistentCommandState | doc_worker |                    | generateDocument | doc_worker |        0 |           10 | 00000000-0000-0000-0000-000000000000 | 7e2925a6-3e9f-4226-bcaa-4c18ea218833 | 2022-08-22 09:33:23.466159+02 | 2022-08-22 09:33:23.466159+02 | f
```

Note that app_uuid and body are empty (null), I don't know if they should be. 
Also it seems that documents are (at least in some cases) eventually created (after a long time). Previews only seem to work when there is a document created already. Otherwise a lot of 202 messages are returned to the browser, but nothing happens and no output is generated.

**Comment by MarekSuchanek** [comment]
These 11 are stuck there even if you see in log of document worker this line: `Fetched 0 jobs`? Or those are eventually generated (after long time), then there are no "New" and start stacking again?

**Comment by jokermanse** [comment]
It seems documents are created (after a very long time), and previews seem to just disappear eventually. The records are then removed from the persistant_command table (and new records are added when new doc/preview is created).
body is NOT null (sorry my mistake, looked more carefully now, it seems to contain meaningful content).

So it seems this is about doc creation for some reason taking a very long time, despite the server making continous requests?
When looking back I also think this might have been an issue already in 3.13 (but not 3.12).

**Comment by MarekSuchanek** [comment]
Can you share your docker-compose.yml and config file(s) with changed sensitive information, please? I tried to reproduce but no luck, also in our all environments it works without any issues...

The document worker is waiting using LISTEN query for a NOTIFY from server that a new document is requested... then it may also timeout after some time when no NOTIFY happened, checks for new documents (process them) and start waiting again. In your case is weird that it actually does not somehow retrieve the new documents even when timeouted or at least not always (?).

**Comment by jokermanse** [comment]
Configs have been mailed.

**Comment by jokermanse** [comment]
So from what I understand, it is the LISTEN query from docworker that is failing? 
I don't know how long the timeout period is, but it does seem that documents are actually (always?) created eventually, presumably at timeout?

It seems also that the dsw-server is just repeating the same (?) transaction "forever", with nothing happening in the frontend. We see hundreds of these when attempting to create a document:

```
2022-08-26T09:25:58.621597736Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Database    ] Transaction started
2022-08-26T09:25:58.621816793Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Database    ] SELECT * FROM questionnaire WHERE app_uuid = '00000000-0000-0000-0000-000000000000' AND uuid = 'c2801268-ac73-4414-9588-e1fc8373e858'  
2022-08-26T09:25:58.631282192Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Database    ] SELECT uuid, 'UserMember' AS member_type, text(user_uuid) AS member_id, perms, questionnaire_uuid  FROM questionnaire_acl_user  WHERE questionnaire_uuid = 'c2801268-ac73-4414-9588-e1fc8373e858'   UNION  SELECT uuid, 'GroupMember' AS member_type, group_id AS member_id, perms, questionnaire_uuid  FROM questionnaire_acl_group  WHERE questionnaire_uuid = 'c2801268-ac73-4414-9588-e1fc8373e858' 
2022-08-26T09:25:58.632357597Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Database    ] SELECT * FROM document WHERE app_uuid = '00000000-0000-0000-0000-000000000000' AND questionnaire_uuid = 'c2801268-ac73-4414-9588-e1fc8373e858' AND durability = 'TemporallyDocumentDurability' 
2022-08-26T09:25:58.633545305Z [Debug] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Cache       ] Get (before): 'Questionnaire Content', key: { lastEventUuuid: '455b58a2-fa0f-44b2-9598-15d0b4528f02' }
2022-08-26T09:25:58.633650199Z [Debug] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Cache       ] Get (found): 'Questionnaire Content', key: { lastEventUuuid: '455b58a2-fa0f-44b2-9598-15d0b4528f02' }
2022-08-26T09:25:58.633728094Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Database    ] SELECT * FROM app_config WHERE uuid = '00000000-0000-0000-0000-000000000000'  
2022-08-26T09:25:58.636026844Z [Debug] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Service     ] Replies hash: 3283670646535937537
2022-08-26T09:25:58.636316534Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Service     ] Waiting to generation
2022-08-26T09:25:58.636890007Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:5019381a-1cf8-4a53-b37b-af0b4d7fc575] [Database    ] Transaction committed
2022-08-26T09:25:58.637094624Z [Info ] [I:7e2925a6-3e9f-4226-bcaa-4c18ea216933] [T:------------------------------------] [API         ] 202 Accepted GET /questionnaires/c2801268-ac73-4414-9588-e1fc8373e858/documents/preview
2022-08-26T09:26:00.008626936Z [Info ] [I:------------------------------------] [T:------------------------------------] [Worker      ] PersistentCommandRetryWorker: starting
2022-08-26T09:26:00.008925357Z [Info ] [I:00000000-0000-0000-0000-000000000000] [T:48dbac08-9654-4b5a-98e6-334c8a39fd38] [Database    ] SELECT uuid, app_uuid, created_by FROM persistent_command WHERE (state = 'NewPersistentCommandState'   OR (state = 'ErrorPersistentCommandState' AND attempts <= max_attempts AND updated_at < (now() - (2 ^ attempts - 1) * INTERVAL '1 min')))   AND internal = true
2022-08-26T09:26:00.010302182Z [Info ] [I:------------------------------------] [T:------------------------------------] [Worker      ] PersistentCommandRetryWorker: ended
```
...

**Comment by MarekSuchanek** [comment]
You can try to adjust the queue timeout like this (default is 120 seconds and usually it is not needed to change it):

```
database:
  queueTimeout: 5
```

From your config, I do not see any significant difference from what we usually have and is working. Are you certain that with 3.12 (and the same configuration), there was no such issue? I can check if we updated some Postgres-related library between these versions that may affect this somehow...

**Comment by jokermanse** [comment]
Hi Marek,


Exactly where should the timeout setting go?

Adding it to docker-compose.yml (in services) I get a "services.database Additional property queueTimeout is not allowed" message.


Many thanks.


/ Urban


________________________________
Från: Marek Suchánek ***@***.***>
Skickat: den 27 augusti 2022 19:58
Till: ds-wizard/ds-wizard
Kopia: Urban Andersson; Mention
Ämne: Re: [ds-wizard/ds-wizard] Documents and/or previews are not created after upgrading (Issue #256)


You can try to adjust the queue timeout like this (default is 120 seconds and usually it is not needed to change it):

database:
  queueTimeout: 5


From your config, I do not see any significant difference from what we usually have and is working. Are you certain that with 3.12 (and the same configuration), there was no such issue? I can check if we updated some Postgres-related library between these versions that may affect this somehow...

**Comment by MarekSuchanek** [comment]
It should be in the configuration YAML `dsw.yml` file mounted to DSW server/docworker/mailer.

```yaml
database:
  connectionString: postgresql://username:password@host:5432/dbname
  queueTimeout: 5
```

**Comment by MarekSuchanek** [comment]
I suspect the SSL connection as that is the only difference from our setups... But I guess there is not other way for you to try that without SSL (e.g. with SSH tunneling or some other technique) so we are sure that it is the culprit?

**Comment by jokermanse** [comment]
Would casting the field 'updated_at' to UTC in the query issued by docworker perhaps solve this? It seems that we (in our local setup) are currently comparing UTC dates with CET here (which might explain the delay when creating new documents).  

Maybe something like (in document_worker/consts.py, line 81):

```
...
SELECT_CMD = f"""
        SELECT *
        FROM persistent_command
        WHERE component = '{CMD_COMPONENT}'
          AND attempts < max_attempts
          AND state != '{CommandState.DONE}'
          AND state != '{CommandState.IGNORE}'
          AND **updated_at AT TIME ZONE 'UTC'** < (%(now)s - (2 ^ attempts - 1) * INTERVAL '1 min')
        ORDER BY attempts ASC, updated_at DESC
        LIMIT 1 FOR UPDATE SKIP LOCKED;
...
```

**Comment by jokermanse** [comment]
I can confirm that adding the above change as a hotfix on our test server seems to have solved the problem. Documents and previews are now being generated instantly again.

**Comment by MarekSuchanek** [comment]
OK, there was some misunderstanding probably... I thought that for some documents it works and some (majority) got stuck and eventually are created in the future. But the issue was that none were created immediately but after certain period of time (timezone diff with UTC). Sorry for that and thanks for diving deep into the issue - I will work on the official hotfix as the same issue exists also for mailer.

Really interesting that this issue did not pop up earlier as this was indeed changed in 3.13 😞

**Comment by MarekSuchanek** [comment]
3.15.2 is released now with this fix, please let me know if it works for you...

**Comment by jokermanse** [comment]
There was a lot of confusion when we tried to debug this at first, and we should probably have studied the logs in a more structured way... It's not the first time we've run into timezone issues in various systems, mostly our own.

Anyway, I have upgraded the test server now and it works perfectly. Many thanks!
