### ISSUE TITLE
Cached Inactive Accounts Can Still Perform Various Actions

### ISSUE THREAD

**Issue by BenjaminWinks** [ds-wizard/ds-wizard#257]
**Describe the bug**
Any account that has been made inactive via the user settings in the admin panel is still functional until the user's cached credentials are removed from the browser.

**How to reproduce**
Steps to reproduce the problem:
1. Make any user inactive via the admin panel while that user is still logged into the application (i.e. Albert Einstein)
2. Do not logout of the application as the inactive user, simply close the browser tab.
3. In the same browser, reopen the application - the inactive user is still logged into the application via cached credentials and can perform actions as if they're active still. This remains true even after a reboot because (potentially) the session cookies are being stored in local_storage rather than session_storage.

**Expected behavior**
Once a user is made inactive, the API should respect this new status and should therefore no longer allow inactive users to interact with the application or perform any sort of manipulation via the UI.

**DS Wizard deployment:**
 - Instance: Local
 - Browser: Chrome/Edge 

In case of your own instance, describe the setup, i.e., if you are using Docker or build DSW from source, what version are you using, etc.

We have installed this application using "docker-compose up" as specified in the readme.md via instruction from Jakub Jirka and Vojtech Knaisl.

**Comment by vknaisl** [comment]
Hello Benjamin,

Thanks for reporting. We will fix that ASAP in the next release at the beginning of September.

Vojtech

**Comment by vknaisl** [comment]
Fixed in the `3.15.0` that was released now
