### ISSUE TITLE
Activating a user using the API

### ISSUE THREAD

**Issue by jokermanse** [ds-wizard/ds-wizard#258]
Hello,

I'm trying to create and activate a new user automatically by using the API.

Creating the user is fine, but when trying to activate it, like:

```
PUT /users/8b82fc69-8544-4a58-865c-d7627ffffd23/state
{
  "active": true
}
```

I get the following error:

```
{
    "status": 400,
    "type": "UserSimpleError",
    "error": {
        "params": [],
        "code": "error.validation.hash_absence",
        "defaultMessage": "A hash query param is absent or doesn't exist in database"
    }
}
```

I am authenticated as admin when making the request, and the "hash" param is not marked as required in the docs. Also I'm not sure what exactly it should be.
 
Setting active:true in the POST request when creating the user does not seem to work, and I'm not sure if it should be. So I guess I have to do it like this somehow (if I can get it to work)? Or maybe I'm missing something?

It would be very helpful if you could shed some light on this.

**Comment by vknaisl** [comment]
Hello Urban,

Please, use the endpoint `PUT /users/userUuid` to adjust the `active` flag for the users. Here is a link to the docs (https://api-researchers.ds-wizard.org/swagger-ui/#/User/put_users__uUuid_).

The endpoint you used serves for activating the user through the link that comes to your mailbox. The hash is required for that endpoint, I made a note to fix it in the docs.

Regards,
Vojtech

**Comment by jokermanse** [comment]
Yes, using PUT instead works perfectly (of course). Many thanks!
