### ISSUE TITLE
edit permission

### ISSUE THREAD

**Issue by imsachaves** [ds-wizard/ds-wizard#259]
**The Question**
The question you want to ask us.
- How can I give edit permission too other logged-in users

**DS Wizard part**
Write down to which part of DS Wizard is the question related (e.g. knowledge model editor or document generation).
- Projects page

**Additional context**
Add any other context or screenshots related to the question.

**Comment by MarekSuchanek** [comment]
Hello @imsachaves, you can do it via the "Share" button in the top-right corner when you open the project; then the dialog will be shown and you can set permissions there:

![image](https://user-images.githubusercontent.com/9638527/191325051-7d890003-ca10-471b-aa00-a051d522dfa1.png)

**Comment by imsachaves** [comment]
nice! Thank you!
