### ISSUE TITLE
Always restart also for the minio service

### ISSUE THREAD

**Issue by AleCeric** [ds-wizard/ds-wizard#260]
**The Question**
Why do not use the compose specification "restart: always" also for the minio service ?

**DS Wizard part**
I refer to the [docker-compose.yml](https://github.com/ds-wizard/dsw-deployment-example/blob/main/docker-compose.yml) file of the **dsw-deployment-example**

Thanks in advance

**Comment by MarekSuchanek** [comment]
It was missing there... thank you for letting us know. I fixed it: https://github.com/ds-wizard/dsw-deployment-example/commit/f2f9de4200c4ba5c1d6a699500468ec69e733350
