### ISSUE TITLE
Some questionnaires produce a 502  Bad Gateway error

### ISSUE THREAD

**Issue by jokermanse** [ds-wizard/ds-wizard#261]
**Describe the bug**
Some questionnaires cannot be opened in the UI 

After upgrading to 3.16.0 on our local server, some (a few) existing questionnaires shows an "Error - Unable to get the Questionnaire", when trying to open.

From the browser console (Chrome, 2 messages):
Access to XMLHttpRequest at 'https://dsw.chalmers.se:3443/questionnaires/3073a93a-a97d-4044-812f-9cd738752b89' from origin 'https://dsw.chalmers.se' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
...
GET https://dsw.chalmers.se:3443/questionnaires/3073a93a-a97d-4044-812f-9cd738752b89 net::ERR_FAILED 502

nginx log:
2022/10/26 12:38:37 [error] 30#30: *4311 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: dsw.chalmers.se, request: "GET /questionnaires/3073a93a-a97d-4044-812f-9cd738752b89 HTTP/1.1", upstream: "http://172.21.0.6:3000/questionnaires/3073a93a-a97d-4044-812f-9cd738752b89", host: "dsw.chalmers.se", referrer: "https://dsw.chalmers.se/"

server log:
[Info ] [I:9e98b640-ac55-43f6-941c-8893f87c4eb9] [T:e7e395bc-f9e9-41fd-9983-0694374f09b4] [API] 200 OK GET /questionnaires/3073a93a-a97d-4044-812f-9cd738752b89
parseTimeOrError: no parse of "2021-12-22 09:10:59.229821+01"
CallStack (from HasCallStack):
  error, called at libraries/time/lib/Data/Time/Format/Parse.hs:82:12 in time-1.9.3:Data.Time.Format.Parse

Not sure if these are related and/or why there would be a cross origin issue with just a few of the questionnaires. Or maybe this is indicating something else failing (such as the date parse error)?

Any help on this would be very appreciated.

Best regards,
Urban

**Comment by vknaisl** [comment]
Hello Urban, 

Sorry for any inconvenience. There was a bug in the date deserialization from the database. We created a hotfix 3.16.3. Please upgrade and let us know if it helps. 

Regards,
Vojtech

**Comment by jokermanse** [comment]
Hello Vojtech,


Yes it's working perfectly now. Thanks again for your quick support.


/ Urban


________________________________
Från: Vojtech Knaisl ***@***.***>
Skickat: den 27 oktober 2022 09:46
Till: ds-wizard/ds-wizard
Kopia: Urban Andersson; Author
Ämne: Re: [ds-wizard/ds-wizard] Some questionnaires produce a 502 Bad Gateway error (Issue #261)


Hello Urban,

Sorry for any inconvenience. There was a bug in the date deserialization from the database. We created a hotfix 3.16.3. Please upgrade and let us know if it helps.

Regards,
Vojtech
