### ISSUE TITLE
Changes to the PUT /questionnaires/content  API function?

### ISSUE THREAD

**Issue by jokermanse** [ds-wizard/ds-wizard#263]
Hello,

Has there been any changes to the /questionnaires/content PUT method in recent versions of the DS Wizard API (> 3.14)?

Simple example (adding a contributor name to an existing questionnaire):

`PUT /questionnaires/14ac82fe-81b6-474a-aac7-4f37f5ce97b7/content

{
    "events": [
        {
            "path": "1e85da40-bbfc-4180-903e-6c569ed2da38.73d686bd-7939-412e-8631-502ee6d9ea7b",
            "uuid": "b9002dbf-3fe5-464b-8f9c-939842bb714f",
            "value": {
                "value": [
                    "dc46ce96-134a-4cf1-b666-78b332a42572"
                ],
                "type": "ItemListReply"
            },
            "type": "SetReplyEvent"
        },
        {
            "path": "1e85da40-bbfc-4180-903e-6c569ed2da38.73d686bd-7939-412e-8631-502ee6d9ea7b.dc46ce96-134a-4cf1-b666-78b332a42572.6155ad47-3d1e-4488-9f2a-742de1e56580",
            "type": "SetReplyEvent",
            "uuid": "feb59588-dd81-4905-94b4-b499944a8516",
            "value": {
                "value": "John Doe",
                "type": "StringReply"
            }
        }
    ]
}`

Now returns 400 "Problem in deserialization of JSON"

The paths should be fine and these requests have worked fine previously.
The example in the documentation also uses the phasesAnsweredIndication, but that does not seem to make any difference, or maybe I'm using this in a wrong way.

Our test environment is currently running v 3.17, but the same occurs in 3.16. I am quite sure I could run these requests as above without problems in v 3.14. 

Many thanks for any hints!

/ Urban

**Comment by vknaisl** [comment]
Hello Urban,

Yes, there was a change in that endpoint. Due to some performance optimalization, there is a need to send also indications about answered/unanswered question. The property is used for showing a progress bar in the “Project List” page. Don’t worry - If you send a wrong values, it will be automatically corrected during the night.

Vojtech

**Comment by jokermanse** [comment]
Hello Vojtech,

Thanks for the clarification. Don't know why it didn't work when I tried this, but it is working perfectly now.

Many thanks!

/ Urban
