### ISSUE TITLE
lost access to DSW slack channel

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#264]
Hello all,

Not sure what happened, I re-installed my computer, and lost DSW in my slack space. Could someone send me an invite?
Thanks heaps!

**Comment by MarekSuchanek** [comment]
You should be able to login again here: https://ds-wizard.slack.com/ (your account uses your gmail address, so you should be able to login via Google).

**Comment by froggypaule** [comment]
Many thanks @MarekSuchanek ; cheers!
