### ISSUE TITLE
following hot fix 3.18.2 server and client

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#265]
**Describe the bug**
Server kapput: docker install. 

```
2022-12-02T08:32:10.522878610Z engine-wizard-bin: internal error: Itimer: Failed to spawn thread: Operation not permitted
2022-12-02T08:32:10.522900279Z     (GHC version 9.2.5 for x86_64_unknown_linux)
2022-12-02T08:32:10.522903694Z     Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
2022-12-02T08:32:10.622204225Z ./docker-run.sh: line 11:     8 Aborted                 (core dumped) /application/engine-wizard-bin
```

```
  dsw-server:
    image: datastewardshipwizard/wizard-server:3.18.2
    restart: always
```

**Comment by froggypaule** [comment]
Reverting to 3.18, I have the same issue...  
I am sorry, I am bit lost :(  

thanks!

**Comment by froggypaule** [comment]
More info:
```
Linux dsw 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by froggypaule** [comment]
....  tell me something:

```
4ae   9 months ago   248MB
ifb-user@dsw:~/dsw (main)$ docker image ls
REPOSITORY                              TAG                            IMAGE ID       CREATED        SIZE
datastewardshipwizard/wizard-server     3.18                           3e90c0fd8b66   11 hours ago   244MB
datastewardshipwizard/wizard-server     3.18.2                         3e90c0fd8b66   11 hours ago   244MB
datastewardshipwizard/wizard-client     3.18                           52f79d7723fa   11 hours ago   72.8MB
datastewardshipwizard/wizard-client     3.18.2                         52f79d7723fa   11 hours ago   72.8MB
datastewardshipwizard/document-worker   3.18                           f0e2d3175159   3 days ago     794MB
datastewardshipwizard/mailer            3.18                           775eca1f3200   3 days ago     486MB
postgres                                13.6                           a0b9c5d9ee48   6 months ago   373MB
minio/minio                             RELEASE.2022-02-24T22-12-01Z   4776fd99f4ae   9 months ago   248MB

```

it seems that 3.18 and 3.18.2 are the same images?  what is it I am missing?

**Comment by MarekSuchanek** [comment]
That is really weird, as other deployments work without issues... What version of Docker Engine are you using? Are there some limits set for the image (it seems like it cannot spawn some more threads)...

3.18 is always the same as latest 3.18.X

**Comment by froggypaule** [comment]
thanks @MarekSuchanek 

ah, thanks for the images id. 

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:28:23 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by froggypaule** [comment]
I'll try to upgrade; don't know why my version is so far behind.

**Comment by MarekSuchanek** [comment]
Yes, please try to update... current version is `20.10.21`, our servers use currently `20.10.19`... your version is from February 2021. I saw some suggestions to upgrade Docker Engine, so I hope it helps 🤞🏻 🍀

**Comment by froggypaule** [comment]
I am sorry to report that I still have the same problem. 

A question: why do images from different versions have the id?

So, what on earth can I do?

**Comment by froggypaule** [comment]
Hang on, I am still stuck with the same docker version.  This is not a good day for me. Very odd. (I did a full reinstall).

**Comment by froggypaule** [comment]
after lots of issues (because of rootless docker), I am no at 

```
ifb-user@dsw:~/dsw (main)$ docker version 
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

and the bad news is that I am still stuck.

How I can possibly backtrack to prior to the hotfix, where everything worked?  

because our site is down now....

**Comment by froggypaule** [comment]
Yes, I don't understand why hot fix images have the same id.

**Comment by froggypaule** [comment]
just a silly question:

```
 internal error: Itimer: Failed to spawn thread: Operation not permitted
```

this has nothing to do with running docker as rootless right?

**Comment by MarekSuchanek** [comment]
You are running Docker daemon with root permissions? That might be an issue, is there a way you can try it with root?

**Comment by froggypaule** [comment]
thanks for the explanation re the docker images.

yes I can try with root, but this is not our favoured choice due to security issues. No, the docker daemon is not run with root permissions.

we use the 'systemctl --user' mecanism...


another question: why would this issue only pop up now?

talk to you later.

**Comment by MarekSuchanek** [comment]
I created image `mareksuchanek/dsw-wizard-server:chore-fix-ubuntu` which is built and runs on `ubuntu:22.04`, can you please check if that helps by some change?

**Comment by froggypaule** [comment]
merci :) I'll try now

**Comment by froggypaule** [comment]
bad luck :(  

Btw, I didn't update to 18.1 yesterday, went directly to 3.18.2

**Comment by froggypaule** [comment]
docker with root works

but surely there must be a way to get around sudo?

we typically run our containers as a password-less user (of course also sudo-less)

**Comment by MarekSuchanek** [comment]
So, `mareksuchanek/dsw-wizard-server:chore-fix-ubuntu` did not help but running Docker under root works with `3.18.2`? And previously `3.18.0` worked without root? Did you make any updates on your server between having `3.18.0` running and making upgrade to `3.18.2`?

**Comment by froggypaule** [comment]
yes to all our questions: I made a standard apt update/upgrade just before switching to 3.18.2

**Comment by froggypaule** [comment]
I need your help: how do I set the volumes so that I can point to the existing ones? (created under the rootless scenario)

**Comment by MarekSuchanek** [comment]
Then it might be the case that the apt upgrade changed something, e.g., if you use some SElinux and there were some upgrades 🤷🏻‍♂️

The volumes should work in the same way without any change... what is the issue?

**Comment by froggypaule** [comment]
but the mapping change since previously they were under /home/ifb-user/.local etc....

**Comment by MarekSuchanek** [comment]
If the containers are stopped, you can move/copy the mounted directories wherever you need and adjust the permissions if necessary. Then you change the mapping under `volumes` to use the correct directory.

**Comment by froggypaule** [comment]
sorry, I found my answer!  : the source for the mapping can be a path, so all is good!


I recover my volumes without any moving etc...

But, do you think it is possible for the server image to work again with a root-less docker?

**Comment by froggypaule** [comment]
so at least, the server is back; I got a serious fright!

**Comment by MarekSuchanek** [comment]
I can try to reproduce on some other VM, but for that I would need what Linux distro and version are you using...

You can try to create new deployment of DSW, e.g. 3.18.0 or 3.17 that worked for you before your apt upgrade. Then, we could somehow check what package upgrade caused the issue. But I am not sure what can we do with that, might a bug somewhere else.

**Comment by froggypaule** [comment]
```
plieby@dsw:~$ uname -a
Linux dsw 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
plieby@dsw:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by froggypaule** [comment]
yes I agree, we don't exactly know where the pb lies...

I have another vm a bit behind:

```
ifb-user@dsw-demo:~/dsw (main)$ uname -a
Linux dsw-demo 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```


but I am running 3.18.2 (dam!! I should have tried 3.18 first)  
and the same error occurs.

for today (where I am on leave ;)  ) I'll leave it at that; maybe we get some bright ideas later on....

**Comment by froggypaule** [comment]
indeed, I and @MarekSuchanek  looked long and hard and couldn't find an answer. 
Possibly one day someone in the same situation will report something or I'll find out where my configuration is amiss...

**Comment by MarekSuchanek** [comment]
We always recommend using the latest version and support hotfixes for the latest, so I close this now. If the issue appears again in a newer version, please feel free to create a new issue.
