### ISSUE TITLE
installing dsw-tdk 3.20

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#266]
**Describe the bug**
I install  dsw-tdk  to get  dsw-tdk 3.19.2.

**How to reproduce**
Steps to reproduce the problem:

```
python3 -m venv dsw-tdk-virt
source  dsw-tdk-virt/bin/activate
(dsw-tdk-virt) paule@kame:~/ifb_sandbox/dsw/output_templates$ pip3 install dsw-tdk
(dsw-tdk-virt) paule@kame:~/ifb_sandbox/dsw/output_templates$ which dsw-tdk 
/home/paule/ifb_sandbox/dsw/output_templates/dsw-tdk-virt/bin/dsw-tdk
(dsw-tdk-virt) paule@kame:~/ifb_sandbox/dsw/output_templates$ /home/paule/ifb_sandbox/dsw/output_templates/dsw-tdk-virt/bin/dsw-tdk --version
dsw-tdk, version 3.19.2
```

I am confused. Is it me?

Note,
```
(dsw-tdk-virt) paule@kame:~/ifb_sandbox/dsw/output_templates$ less /home/paule/ifb_sandbox/dsw/output_templates/dsw-tdk-virt/lib/python3.10/site-packages/dsw_tdk-3.20.0.dist-info/METADATA 
```

gives
```
Metadata-Version: 2.1
Name: dsw-tdk
Version: 3.20.0
Summary: Data Stewardship Wizard Template Development Toolkit
```

**Expected behavior**

**Screenshots**

**DS Wizard deployment:**
 - Instance [e.g. demo.ds-wizard.org, local, or our custom]
 - Browser [e.g. chrome, safari] (inc. version, if relevant)

In case of your own instance, describe the setup, i.e., if you are using Docker or build DSW from source, what version are you using, etc.

**Additional context**

**Comment by froggypaule** [comment]
oh yes, I guess so!

**Comment by froggypaule** [comment]
but actually using dsw-tdk tu upload templates, I end up with the same error as Libby reported....

**Comment by MarekSuchanek** [comment]
@froggypaule `dsw-tdk==3.20.1` is now released, could you please confirm that the issue is resolved?

**Comment by froggypaule** [comment]
hoho!!! all fixed now, templates can be properly uploaded :)

Thanks!!!
