### ISSUE TITLE
importing templates with dsw-tdk to v 3.20

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#267]
**The Question**
Not sure if it is me or a bug or....

**DS Wizard part**

When doing
```
 dsw-tdk -e .envdsw put forked-km-insight-template/
```

I get this warning
```
WARNING: There is different organization ID set in the DSW instance (local: dsw, remote: IFB)
```

![Screenshot from 2023-02-09 14-46-03](https://user-images.githubusercontent.com/47455219/217840938-f1d1967d-5bf1-49ca-84eb-9d98efdf1e46.png)

I wonder if this could explain why I can't see the updated template version from  within DSW....

Thanks for your insight....

**Comment by MarekSuchanek** [comment]
Since v3.20, there are "Document Template Editors" in DSW that you can use to also adjust the template but also to see the preview (test it) and then "release". It now works like for KM editors and KMs... you can edit it and preview as data steward, regular users will not see it as it is not in "Document Templates", but once you have it ready, you can "publish" the template (via the Editor in DSW).

Again, as in KM editors, the organization ID used within the DSW instance is the one from Settings. Thus, if your template.json uses a different one it will be changed = warning is shown.

In case you want to have the template with the different organization ID, you can create a ZIP file using `dsw-tdk package` and import it in DSW manually.

Maybe we can discuss what "new" commands could help in TDK with this flow... maybe some command to release template draft directly from CLI? And one that creates automatically a ZIP and pushes it to DSW (but there you cannot "overwrite version" if already used)?

**Comment by froggypaule** [comment]
ok,  I'll have a look and come back to you :)

**Comment by froggypaule** [comment]
Ok, I understand what is happening: indeed the organisation ID is changed, but this is not what I want. (Note this happened with using the CLI dsw-tdk).
An example: 
![Screenshot from 2023-02-10 08-49-31](https://user-images.githubusercontent.com/47455219/218033302-fbfff4fd-308f-46e0-91db-2b354ac1eb00.png)

These templates are actually dsw's,  templates which you remember I've rewritten a little while ago. So I think it is fair to keep them with ID DSW. See the list 
![Screenshot from 2023-02-10 08-49-31](https://user-images.githubusercontent.com/47455219/218033996-e071f73a-7854-49bc-85a9-b83ba0053f9a.png)
Note that I see this list using the 'editor' function, and these same templates didn't list with the 'list' function, adding to my confusion 
![Screenshot from 2023-02-10 08-55-17](https://user-images.githubusercontent.com/47455219/218034414-9dfc4f5f-2411-4cca-adc6-72b66beadc85.png)


At least now I understand why I didn't see any template update, still it would be nice and convenient to be able to set a different ID as the one from settings. 
Maybe an option with the CLI dsw-tdk, and also with the editor: 'warning: the template's organisation ID is different from the one set in 'Settings'. Change to the ID set in 'Settings'?  
or something along  these lines....

**Comment by froggypaule** [comment]
And actually, I cannot edit (via the 'editor' function) all the `dsw:insight-template` templates...

I understand the rationale behind it: as soon as I edit within the site (or via the CLI) it ipso facto becomes a IFB template...

**Comment by froggypaule** [comment]
Hello! I tried with the new tools 3.20.2, but I still end up with the same issue.
Client is 3.20.2 
![Screenshot from 2023-02-11 14-09-12](https://user-images.githubusercontent.com/47455219/218259822-b1ce6873-56eb-449a-ae79-ae5905ac9b57.png)

Output from CLI is now good and informative
![Screenshot from 2023-02-11 14-08-19](https://user-images.githubusercontent.com/47455219/218259878-3fbca1a8-ad82-4442-bd0a-203a6e165a8d.png)

But I still end up with IFB:template 
![Screenshot from 2023-02-11 14-07-56](https://user-images.githubusercontent.com/47455219/218259910-daed719d-4efc-4983-bd5e-8f539b906427.png)

and the dsw:template hasn't been updated 
![Screenshot from 2023-02-11 14-13-48](https://user-images.githubusercontent.com/47455219/218259948-120ffbb3-53a2-40cc-a536-a31da17a06f1.png)
....

thanks!

**Comment by froggypaule** [comment]
Hello!

There is more to this problem: for the projects who, say, used the `dsw:km-insight-rewritten` template, I can't assign the `IFB:km-insight-rewritten` template... 

Still, I definitely need the newest version. Sorry for this, woudn't want to harass ;)

**Comment by froggypaule** [comment]
Ok good news @MarekSuchanek : at least the dsw-package and importing works as expected: I am now able to update the dsw:templates.

But this still leaves the issue of the CLI...

**Comment by MarekSuchanek** [comment]
This is more related to that TDK is intended for development, and for that you should be OK with use of local organization ID in your DSW instance. Then for distribution you should create a package and work with that... Only think that comes to my mind how we can improve is to allow ZIP-upload using CLI. I noted that down as potential additional feature of TDK (I have some ideas for more): https://ideas.ds-wizard.org/posts/130/extend-use-cases-of-tdk
