### ISSUE TITLE
name for items (from list of items)

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#269]
Depending on the type of questions, items (when adding items from item list), get named or not:
![Screenshot from 2023-03-02 16-46-50](https://user-images.githubusercontent.com/47455219/222479011-5fea28f0-36b2-4b89-a4ce-6d45e7b52ffa.png)

For the question "Informations sur la structure", the first question in the following item list is a string value question, so the item get's the name "truc" from this value question.

But for the question "Personnes et/ou entités assumant des rôles et" the first question is an option question, so that the item stays named "item x".

Is there a way to alleviate this? because the DMP becomes confusing to decipher....
Thanks!

**Comment by MarekSuchanek** [comment]
The name for item appears there only if the first question is value/integration question... if it would be also for options, then you would have repeated label of the option, for multi-choice it would be even more complex, and for list question as a first question in a list question I cannot even imagine some solution.

Please let us know if you have some ideas how to improve that...

**Comment by froggypaule** [comment]
see https://ideas.ds-wizard.org/posts/129/name-for-items-from-list-of-items
