### ISSUE TITLE
DS Wizard cannot import the French locale

### ISSUE THREAD

**Issue by emilinecsa** [ds-wizard/ds-wizard#270]
**Describe the bug**
We installed DS Wizard on our test server. The application works fine and it imports knowledge models and document templates properly. However, DS Wizard cannot import the French locale nor any other one.

**How to reproduce**
Steps to reproduce the issue:
1. Go to the main window (dashboard) of DS Wizard.
2. On the left pane, click _Administration_.
3. The _Locales_ option shows up below _Administration_ on the left pane. Click _Locales_.
4. We currently have just one locale, which is the default one: English 1.0.0 wizard:default:1.0.0
6. Click the _Import_ button above. The _Import Locale_ windows shows up.
7. Select the _From DWS Registry_ tab.
8. Enter **dsw:fr:0.3.0** in the text field and click the _Import_ button.
9. This error happens: Importing the locale failed. There are no extra details.
10. Select the _From file_ tab.
11. Drag and drop the PO file from your [GitHub repository](https://github.com/ds-wizard/wizard-client-locales/tree/v3.20.1/locales/fr). 
12. This error happens: Importing the locale failed.
**Note:** Adding the PO file to a ZIP file with or without the JSON file give us this error: "locale.json" was not found in archive.

**Expected behavior**
We expect DS Wizard to import the French locale successfully just like it does for both knowledge models and document templates.

**Screenshots**
I am sorry, but our firewall does not allow us to upload image files. Security concern. Sorry about that.

**DS Wizard deployment:**
 - Local instance on a test server. _Linux - Ubuntu 20.04_
 - DS Wizard was installed with Compose Docker.
 - Browser: Firefox

**Additional context**
The error message is not explicit. We do not have any extra detail.

**Comment by vknaisl** [comment]
Hello Emiline,

Sorry that you are having a problem with DSW. There can be more things that cause your problem. 

**1. Wrong connection to the S3** - Are you sure that you set up correctly the S3 Storage (or Minio if you use it)? If you want to ensure that it's working correctly, try to create a project and create a document based on the project. If you are able to download it, then it is working correctly.

**2. Wrong connection to registry" - To validate it, try to import, for example, a document template from the registry

**3. Wrong file** - You are importing the wrong file from your computer. The DSW accepts a ZIP file that includes the PO file and metadata. Therefore, the files downloaded from the following location will not work (https://github.com/ds-wizard/wizard-client-locales/tree/v3.20.1/locales/fr). Nevertheless, this should not be a good option to go for you. You should import from the registry, so you are able to receive updates in the future directly from the UI.

**Comment by emilinecsa** [comment]
Thanks for your reply.

So far, we know that the connection to the S3 is good since we can create new projects and documents based on our new projects. In addition, our instance of DSW imports knowledge models and document templates properly. This part works fine.

We still have the same issue while trying to import the French locale from the registry. (see the steps in the post, above)
By the way, none of the locales listed on [this page](https://registry.ds-wizard.org/locales) work. This error happens: **Importing the locale failed**. There are no extra details. We use "**dsw:fr:0.3.0**" as locale ID. Is that correct? By the way, dsw:fr:0.2.0 or dsw:fr:0.1.0 do not work as well.

Is there a way to get more details such as looking into a log file? If so, could you tell us in what folder the log files are located in. Our instance of DSW runs on Linux - Linux - Ubuntu 20.04.

In addition, we use Firefox? Is this browser recommended to work with DSW?

Thank you

**Comment by janslifka** [comment]
Hello Emiline,

First thing you can try to explore the actual response from the API to see what is there because the error message _"Importing the locale failed"_. is a fallback in the UI when something unexpected happens. To do that, you can do the following steps in Firefox:

1. Open the import from the registry page, right-click anywhere on the page, and select **Inspect**.
2. Click on the **Network** tab in the developer tools (it will be empty now).
3. Try to import the locale from the registry.
4. New POST request should appear there with an error status. Click on it.
5. It will open more details, choose the **Response** tab and see what's there.

See the attached image for these steps:
![](https://user-images.githubusercontent.com/7797976/224372220-687ee016-6399-49a1-b636-793922b1e25e.png)

If nothing useful is there, you can try to explore the logs from the server container. There is no log file, but the logs are in the container in standard output.

**Comment by emilinecsa** [comment]
Thank you for your feedback. I followed your steps and tries to import `dsw:fr:0.3.0`.  I got an **Internal Server Error** (**Status: 500**).

**Note:** Importing `dsw:staging:fr-ca:0.1.0` causes a different error: Desired locale ('%s') wasn't found in Registry (**Status: 400**). It makes sense because my instance of DSW cannot find it.

In case, this might helpful for you, here is the content of the whole POST message: (`dsw:fr:0.3.0`)
```
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "110.0.1"
    },
    "browser": {
      "name": "Firefox",
      "version": "110.0.1"
    },
    "pages": [
      {
        "startedDateTime": "2023-03-13T07:09:59.396-07:00",
        "id": "page_1",
        "title": "CSA Open Data Management Plan",
        "pageTimings": {
          "onContentLoad": -134806,
          "onLoad": -134710
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_1",
        "startedDateTime": "2023-03-13T07:09:59.396-07:00",
        "request": {
          "bodySize": 0,
          "method": "OPTIONS",
          "url": "http://localhost:3000/locales/dsw:fr:0.3.0/pull",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:3000"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Access-Control-Request-Method",
              "value": "POST"
            },
            {
              "name": "Access-Control-Request-Headers",
              "value": "authorization"
            },
            {
              "name": "Referer",
              "value": "http://localhost:8081/"
            },
            {
              "name": "Origin",
              "value": "http://localhost:8081"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "empty"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "cors"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "same-site"
            }
          ],
          "cookies": [],
          "queryString": [],
          "headersSize": 487
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Transfer-Encoding",
              "value": "chunked"
            },
            {
              "name": "Date",
              "value": "Mon, 13 Mar 2023 14:09:59 GMT"
            },
            {
              "name": "Server",
              "value": "Warp/3.3.23"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Access-Control-Allow-Credential",
              "value": "true"
            },
            {
              "name": "Access-Control-Allow-Headers",
              "value": "Origin, X-Requested-With, Content-Type, Accept, Authorization"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "OPTIONS, HEAD, GET, POST, PUT, DELETE"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/plain",
            "size": 0,
            "text": ""
          },
          "redirectURL": "",
          "headersSize": 338,
          "bodySize": 338
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": 0,
          "connect": 2,
          "ssl": 0,
          "send": 0,
          "wait": 5,
          "receive": 1
        },
        "time": 8,
        "_securityState": "insecure",
        "serverIPAddress": "127.0.0.1",
        "connection": "3000"
      },
      {
        "pageref": "page_1",
        "startedDateTime": "2023-03-13T07:09:59.520-07:00",
        "request": {
          "bodySize": 0,
          "method": "POST",
          "url": "http://localhost:3000/locales/dsw:fr:0.3.0/pull",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:3000"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Authorization",
              "value": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzk1MDg4MTIsInRva2VuVXVpZCI6IjcxYWVlY2FkLThjNjQtNDg2Zi05OGJmLTBiNTRlMjU2NWIyYyIsInVzZXJVdWlkIjoiZWM2ZjhlOTAtMmE5MS00OWVjLWFhM2YtOWVhYjIyNjdmYzY2IiwidmVyc2lvbiI6IjMifQ.TGgItaGhLzweLptMpVzoBfDCq_e2ugmHlOBXp4wYpqM"
            },
            {
              "name": "Origin",
              "value": "http://localhost:8081"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Referer",
              "value": "http://localhost:8081/"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "empty"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "cors"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "same-site"
            },
            {
              "name": "Content-Length",
              "value": "0"
            }
          ],
          "cookies": [],
          "queryString": [],
          "headersSize": 702
        },
        "response": {
          "status": 500,
          "statusText": "Internal Server Error",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Transfer-Encoding",
              "value": "chunked"
            },
            {
              "name": "Date",
              "value": "Mon, 13 Mar 2023 14:10:01 GMT"
            },
            {
              "name": "Server",
              "value": "Warp/3.3.23"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Access-Control-Allow-Credential",
              "value": "true"
            },
            {
              "name": "Access-Control-Allow-Headers",
              "value": "Origin, X-Requested-With, Content-Type, Accept, Authorization"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "OPTIONS, HEAD, GET, POST, PUT, DELETE"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json",
            "size": 14,
            "text": "{\"status\":500}"
          },
          "redirectURL": "",
          "headersSize": 389,
          "bodySize": 403
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 1700,
          "receive": 0
        },
        "time": 1700,
        "_securityState": "insecure",
        "serverIPAddress": "127.0.0.1",
        "connection": "3000"
      }
    ]
  }
}
```

**Comment by vknaisl** [comment]
Hello Emiline,

Can you please try to import the locale via both ways - from the registry and from the file and send us logs from the `dsw-server` to our info@ds-wizard.org?

Thanks,
Vojtech

**Comment by emilinecsa** [comment]
We cannot find the log files on our server. May you tell me what is the default folder?
We run on Linux Ubuntu 20.04.

Thank you

**Comment by vknaisl** [comment]
Hello Emiline,

It depends on your configuration. If you don't configure anything special, then the logs will be on the stdout. You can access them via the `docker logs` command.

Vojtech

**Comment by emilinecsa** [comment]
Hello,

We just emailed the log file. It looks like a bucket is not found. Does it mean anything to you?

[Database]   GeneralServerError "Error in S3: MErrService NoSuchBucket"
[API]             Error in S3: MErrService NoSuchBucket
[API]             500 Internal Server Error POST /locales/dsw:fr:0.4.0/pull

So far, we know that the connection to the S3 is good since we can create new projects and documents based on our new projects. In addition, our instance of DSW imports knowledge models and document templates properly. This part works fine. 

We followed your steps and tries to import dsw:fr:0.3.0. I got an Internal Server Error (Status: 500). Our understanding is that the request is sent properly, but our instance cannot pull back the response for an unknown reason.

**Note:** Importing dsw:staging:fr-ca:0.1.0 causes a different error: Desired locale ('%s') wasn't found in Registry (Status: 400). It makes sense because my instance of DSW cannot find it.
In case, this might helpful for you, we attached the content of the whole POST message: (dsw:fr:0.3.0)

Thanks for your support

**Comment by MarekSuchanek** [comment]
Hi @emilinecsa, it really seems you did not create the S3 bucket (`MErrService NoSuchBucket`)... Are you sure it is there and with the matching name as you have in your YAML configuration file? As noted [here](https://github.com/ds-wizard/dsw-deployment-example#important-notes)?

Are you also sure that you can create and download document files in your DSW instance?

**Comment by emilinecsa** [comment]
Thank you so much for your support. The problem is now fixed and we were able to import the French locale.

**Comment by emilinecsa** [comment]
Thank you so much for your support. The problem is now fixed and we were able to import the French locale.
