### ISSUE TITLE
v3.21.0 has teething problems

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#271]
**Describe the bug**
This is a root docker install. Replacing the V3.20.x by V3.21 ends up in a "502 bad gateway pb". 

Nothing is shown in the sys log files or the container log files. 
Restoring to the previous version 3.20.x restored a fully fonctionning dsw instance.

**Comment by janslifka** [comment]
There was a change in the client image. It no longer runs on port 80 but 8080, so it doesn't have to run as a root user inside the container for security reasons. All you have to do is change the mapping of the ports in your deployment, and everything should work as before.

This change should be eventually described in our upgrade guidelines in the guide.

**Comment by froggypaule** [comment]
ha good, I didn't bother to check this. Will retry.

**Comment by froggypaule** [comment]
ok, at least something easily fixed :)
