### ISSUE TITLE
Another issue, not necessarily related to V3.21.0

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#272]
**Describe the bug**
Root docker install. With V.3.21.0. 

Using image postgres:15.2 as shown in current dsw-deployement-example on dsw github shows an error 
`dsw-server can't talk to database` (sorry, no screenshot since reverted to older version)

Restoring to postgres:13.6 didn't show this error, and dsw-server connected properly to db. 
Did not try with V3.20.x, possibly related to #271?

**How to reproduce**image p
Steps to reproduce the problem:
1. replace postgres:13.6 by postgres:15.2
2. dsw-server log shows connection issue with db

**Comment by vknaisl** [comment]
Hello Paulette, 

That's strange. We are also running Postgres 15.2 on one of our managed DSW instances, and everything seems fine. Did you correctly follow the Postgres upgrade process? There were some changes in the configuration, as far as I remember.

Vojtech

**Comment by froggypaule** [comment]
heuh... I certainly didn't follow the postgres upgrade process; will do this and report here. Thanks @vknaisl .
