### ISSUE TITLE
Files (documents, exports, preview) not downloadable in v3.21

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#273]
**The Question**
Not sure if it as a bug or... 
- project preview does not show anything, irrespective of templates used
- same for documents....

**DS Wizard part**
document-worker

**Screenshot**
It seems that everything is alright 
![Screenshot from 2023-03-09 16-22-09](https://user-images.githubusercontent.com/47455219/224071868-fc14ba7e-c610-436a-ac5b-6f2325b7d315.png)

**Comment by MarekSuchanek** [comment]
Indeed it seems all OK from the point of view of the logs...

1. Are you sure that the same MinIO/DB is configured for the docworker and server?
2. In the preview / doc generation, is it stuck on "In Progress" or ends with "Error"?
3. This started with deployment of 3.21 and everything else is working fine? Can you for example download the previously generated documents?

**Comment by froggypaule** [comment]
hello @MarekSuchanek 

1. minio: I suppose, I didn't modify the yml file (attached)
2. it doesn't show either `progres` or `error`, simply nothing
3. I can't dowload any documents, ie anything ever created (nothing in the logs either); if it started at 3.21, possibly, it is a feature I use a lot, so...

If this pb doesn't show up on your side, then I am scared...
[docker-compose.yml.txt](https://github.com/ds-wizard/ds-wizard/files/10939864/docker-compose.yml.txt)

**Comment by MarekSuchanek** [comment]
So what happens when you click create? Or when you open the preview tab? Can you send some screenshot(s) of it?

**Comment by froggypaule** [comment]
- creating a document: everything goes to plan but then it is a big blank when trying to download 
![Screenshot from 2023-03-10 09-41-48](https://user-images.githubusercontent.com/47455219/224267298-27643411-6168-4c73-b5e3-a609171ab69b.png)


- preview: a big blank as well, 
![Screenshot from 2023-03-10 09-37-53](https://user-images.githubusercontent.com/47455219/224266725-c1f161aa-75e3-4393-8fca-716d264a1a2a.png)

**Comment by froggypaule** [comment]
I hope we'll find an answer; if later today we haven't got more of clue, I'll revert to 3.20 to get the site up and running.

**Comment by froggypaule** [comment]
ok, I will have to revert for now.

**Comment by froggypaule** [comment]
Hello!  do you have any news on this topic?

Trying to debug this, I installed V3.21 on a vbox vm. If you could bear with me and help me decipher this:
- previewing a document gives 
![Screenshot from 2023-03-21 08-42-48](https://user-images.githubusercontent.com/47455219/226547196-4959051e-e065-49c5-988d-5fa93e3e3131.png)
- the log files show
![Screenshot from 2023-03-21 08-43-43](https://user-images.githubusercontent.com/47455219/226547251-8e0a9a99-042a-4961-896b-fb4e8414f323.png)

To make sure, I did a V3.20 install on the same vm, and all worked well. I am not sure if the above helps, but obviously this problem can be reproduced. This time on a machine with sudo docker, but without nginx since I access it via localhost.

**Comment by froggypaule** [comment]
No,  doesn't work either. 

Same type of logs. But why do we this: 
![Screenshot from 2023-03-21 12-55-23](https://user-images.githubusercontent.com/47455219/226598788-7abcd2ec-9788-461c-80e8-7650edc42afc.png)

since nginx is not installed...

**Comment by MarekSuchanek** [comment]
Hi Paulette, do you have access to your S3 service from outside? That is needed to download the files... You need to have it exposed and correspondingly configured in your YAML config file.

**Comment by froggypaule** [comment]
hello Marek,
... euh.. .sorry, but I don't see what you mean.
The yaml file is as the one taken from the dsw-deployment-example repository.

**Comment by MarekSuchanek** [comment]
I suppose you are using MinIO, right? Do you have access to the MinIO console (using which you probably created the bucket)? Let's say you have it exposed to https://s3.example.com (proxied to minio:9000, console to minio:9001, see [their docs](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html); then you should use that externally accessible URL in your YAML configuration (as when you are downloading locally the document, clients cannot access something like http://minio:9000 inside the Docker network).

The deployment example (and Guide) is indeed not updated in this way, I will take a look at that. But the local deployment (for testing) is very specific as it does not even use proxy or domain names... I think we will make some FAQs and notes for such deployments as well as custom deployments of people. With the growing feature set and security demands, things like this become also more complex.

**Comment by froggypaule** [comment]
Re-reading your comments, I certainly never exposed minio before.... and still documents and previews worked properly, until V3.21.
So, I must conclude that something changed with V3.21? 
Paulette is confused...

**Comment by froggypaule** [comment]
In the minio doc I read `A DNS hostname which uniquely identifies the MinIO deployment`, this is definitely new to me....

**Comment by MarekSuchanek** [comment]
For local testing, [this](https://github.com/ds-wizard/dsw-deployment-example/commit/daf0a2259dd4d138b5e91b2756b839311846f557) should fix it (as `host.docker.internal` points from Docker container to the host machine where port 9000 is exposed as well as on the host machine where it points to localhost... added to `/etc/hosts` via Docker installation). Can you check whether that works for you please?

For deployments with HTTP proxy, you basically need to proxy out also MinIO... e.g. https://s3.example.com (DNS hostname) with proxy pass to http://minio:9000 inside your Docker environment. Just as you proxy out DSW API and DSW Client, but follow the documentation of MinIO what should be set for the proxy. Indeed, this changed in v3.21... unfortunately, it was not well captured in the upgrade guidelines, I am fixing it now. We are sorry for that.

Previously, only DSW Server communicated with the MinIO/S3 as object storage. But for example when downloading a document, token had to be passed in the URL (and eventually could be stored in some metadata of file or in download history of browser). Now it uses a temporary URL of file in S3 which is more secure and common way of handling such things when working with S3 storages.

**Comment by froggypaule** [comment]
Ok, now I understand what is happening, this makes sense. 

unfortunately your suggestion doesn't work (yet), I must have made a mistake of some sort....

![Screenshot from 2023-03-25 14-41-18](https://user-images.githubusercontent.com/47455219/227720841-b3e280b7-9c0b-4176-9b19-3cb9a14b9087.png)
![Screenshot from 2023-03-25 14-41-18](https://user-images.githubusercontent.com/47455219/227720848-2390d604-8ffe-4d94-be16-ec581b6258b5.png)

**Comment by MarekSuchanek** [comment]
There are also some changes in `docker-compose.yml` related to this (https://github.com/ds-wizard/dsw-deployment-example/commit/3ee8e8389f5d6d14b36b3d11c2817443e51e0407), mainly adding `extra_hosts` so `host.docker.internal` resolves correctly (this should work also on Linux).

**Comment by froggypaule** [comment]
1. bad news: on the vbox vm, I can't make it work, see attached ymls
[docker-compose.yml.txt](https://github.com/ds-wizard/ds-wizard/files/11075702/docker-compose.yml.txt)
[dsw.yml.txt](https://github.com/ds-wizard/ds-wizard/files/11075704/dsw.yml.txt)

2. GOOD NEWS:  I got my dsw-s3 DNS, and now our institutional site is on V3.21 and all good.

Let's forget about 1., we are all too busy. Thanks @MarekSuchanek

**Comment by MarekSuchanek** [comment]
@froggypaule I just verified again that it works well on Windows, I will try on Linux (I will need to set up some VM)... But please make sure that you created the S3 bucket in the local deployment. And also if you can check `/etc/hosts` that there is a row `127.0.0.1   host.docker.internal` (or something similar with this hostname).

**Comment by froggypaule** [comment]
Hello Marek, I did create the s3 bucket. Ha1, no, I didn't check the hosts file.
