### ISSUE TITLE
publishing KM in V3.22: versioning wrong???

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#275]
### What web browser is used when the issue appears?

Firefox

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [ ] Using DSW managed by someone else (specify in text)
- [X] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [X] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

Client
Version: v3.22.0~672ade6
Built at: 2023-04-05T07:20:08Z
---
Serveur
Version: v3.22.0~e96e7cfd
Built at: 2023-04-04T14:51:46Z
---
Document Worker
Version: v3.22.0~cdb0ab7
Built at: 2023-04-04T15:05:17Z
---
Mailer
Version: v3.22.0~cdb0ab7
Built at: 2023-04-04T15:05:18Z

### What happened?

A bug happened! indeed!!! actually you will tell me:

I edit a KM 
![Screenshot from 2023-04-06 15-23-13](https://user-images.githubusercontent.com/47455219/230392915-7533140f-7165-4f1e-9b2c-d8481e3e1006.png)

you see that it has version 2.0.6

I want to publish it
![Screenshot from 2023-04-06 15-30-18](https://user-images.githubusercontent.com/47455219/230393262-53130cd1-463d-41e6-967d-eaa6a9021cec.png)
![Screenshot from 2023-04-06 15-30-33](https://user-images.githubusercontent.com/47455219/230393525-50affe21-325c-4457-9be9-9646fe6df5f4.png)

and indeed
![Screenshot from 2023-04-06 15-23-39](https://user-images.githubusercontent.com/47455219/230393719-dd536562-0f2a-4c9f-ac4d-4ddeafa09415.png)

everything (the whole history) has gone....
tell me it is not me.... 

### Relevant log output

```plain text
nothing to report
```

**Comment by janslifka** [comment]
Dear Paulette,

Do not worry nothing is gone. All you need to do is to go to settings and set the version you want to publish there.

This was caused by changing the flow of publishing knowledge models to support the deprecated knowledge models and make KM Editor and Document Template Editor more consistent. For the existing editors, the version was set to 1.0.0 during the database migration to 3.22, as it is not straightforward to figure out the correct version.

We are internally discussing how to approach this better, as it might be confusing.

**Comment by froggypaule** [comment]
Dear Jan,
Thanks for working on your holiday time (I believe, as it is for me ;) ). I understand what your latest deprecated feature has entailed.

Ok I did what you said, and it worked somehow. I day somehow because it took two steps
(as far I recall)
- publish button
- fill in settings manually
- go back to list of editors, new version wasn't there
- re publish button where it came up with the version set in 1rst step

nothing of note in the logs; but don't worry things worked out at the end.

One thing: I lost all the changelog which was extensive and full of hyperlinks (copy and paste didn't do it).

So if I could ask you for the psql cmd to extract the old changelog and update for the latest version. With time and effort I might find it, but it's easier if I ask you ;)

But this is not urgent at all, and can wait Tuesday (we have a big DMP day on Wed...).
Many thanks! 
Cheers.

**Comment by froggypaule** [comment]
Further, I tried to play with it (the new version), delete the editor, recreate it, publish again. Indeed, I was quite confused as processes were not as they were (I would need to document this is more detail). I guess you are well aware of this.
Till next week!

**Comment by froggypaule** [comment]
hello again,
there is really an issue with publishing: 
suppose I published a KM to V1;

if I leave it open in the editor, I cannot publish it since it wants to publish in V1 again

so, what I have to do
- delete editor for V1
- reopen one from the KM in the list of KMs, where I am asked which version, where I answer V2
- now I can modify V2 and publish it as V2

also, nowhere can I fill in the README, publishing is done without any interaction on my part (except from providing the version)


I will be at my laptop only tomorrow late arvo. thanks heaps

**Comment by vknaisl** [comment]
Hello Paulette, 

Did you try to upgrade to the new versions (wizard-client 3.22.1 and wizard-server 3.22.2)? The publishing of KM is reworked.

Regards,
Vojtech

**Comment by froggypaule** [comment]
ha no, I didn't.
why? I went away on a mission with forgetting my laptop :(  so I can't check slack

in which case I upgrade asap and let you know, once I recovered my worktool.....
thanks!!!  I'll let you know

**Comment by froggypaule** [comment]
hello @vknaisl : all good now after update to the new version!!!
:)
