### ISSUE TITLE
Bug???

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#276]
### What web browser is used when the issue appears?

Chrome

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [ ] Using DSW managed by someone else (specify in text)
- [X] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [X] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
Client
Version: v3.22.0~672ade6
Built at: 2023-04-05T07:20:08Z
---
Serveur
Version: v3.22.0~e96e7cfd
Built at: 2023-04-04T14:51:46Z
---
Document Worker
Version: v3.22.0~cdb0ab7
Built at: 2023-04-04T15:05:17Z
---
Mailer
Version: v3.22.0~cdb0ab7
Built at: 2023-04-04T15:05:18Z
```

### What happened?

(sorry if this is not a bug...)

For one particular project, one can create documents but not download them. But preview does work.
The log file shows 
![Capture d’écran du 2023-04-12 13-46-44](https://user-images.githubusercontent.com/47455219/231449414-2a34d1fc-33d2-4afb-9139-5a2501e16489.png)

This is the document 
![Capture d’écran du 2023-04-12 13-55-40](https://user-images.githubusercontent.com/47455219/231449695-3d5b7c2f-7e2c-4d7a-9e40-bba9b6aa012d.png)

No problem with preview however;
thanks!!!!!

**Comment by vknaisl** [comment]
Hello Paulette,

Not sure where the problem can be. I created a project with the same name in our instance and it works as expected. Maybe you have the `s3.url` in the `application.yml` not open to the public?

Vojtech

**Comment by froggypaule** [comment]
thanks!!!!!

**Comment by froggypaule** [comment]
Good morning!

For the url, it is `url: https://dsws3.france-bioinformatique.fr`
no now it is defnitely open.

since the problem appears for one project only, I take the liberty to send you the json version (obtained via a preview copy and paste) by mail (because of GDPR). thanks!

**Comment by vknaisl** [comment]
Hello Paulette,

I checked the internet and found the following article - https://bobbyhadz.com/blog/aws-cli-signature-does-not-match. Can you please check if it is not your case?

Regards,
Vojtech

**Comment by froggypaule** [comment]
Thanks @vknaisl ,

Yes that was where to look, but possibly not quite: reading this https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html and others I thought that maybe the problem was with the title of the document.

This sound a crazy idea, but yes it is the problem here:
- for example `Copy of debug interop template MicroPICell DMP 1.0.6` does not work
- `interop template MicroPICell DMP 1.0.6` and `Copy of debug` work 
- `FJfkjqw,rfqpewffdgtekftjeklqwwerrtpdgresdffftoaqshewe` works too (in case the length was the problem)

... so I am lost: I wish we had a better answer

**Comment by vknaisl** [comment]
I understand. However, I tried to create a document with the same title as you have (`Copy of debug interop template MicroPICell DMP 1.0.6`), and it is working at our instance. Therefore, I thought about where the difference could be between our instance and yours.

**Comment by froggypaule** [comment]
Finally, just to understand better, I tried the latest minio version: to my dismay, no document was accessible at all.

Surely, you understand why this is so? 

To conclude, this is a bug I simply do not understand. Maybe with time, we'll find an answer.

**Comment by vknaisl** [comment]
We are running on the `minio/minio:RELEASE.2021-03-17T02-33-02Z`. Could you try to run DSW with the following version?

**Comment by froggypaule** [comment]
this really baffles me

**Comment by froggypaule** [comment]
what is the `create-bucket.sh` exe actually doing?

**Comment by vknaisl** [comment]
It creates a bucket if you are using Minio

**Comment by froggypaule** [comment]
Yes, but we do this once only isn't it? ie, not when upgradind the image?
