### ISSUE TITLE
KM export does not work from KM list

### ISSUE THREAD

**Issue by marikapop** [ds-wizard/ds-wizard#277]
### What web browser is used when the issue appears?

Firefox

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [X] Using DSW managed by someone else (specify in text)
- [ ] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [X] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
Client
Version	v3.22.1~2f951c0
Built at	11. 4. 2023, 16:16
Style Version	
Server
Version	v3.22.3~520f52ba
Built at	13. 4. 2023, 10:16
API URL	https://api-biohack.ds-wizard.org
API Docs	https://api-biohack.ds-wizard.org/swagger-ui/
Document Worker
Version	v3.22.0~cdb0ab7
Built at	4. 4. 2023, 17:05
Mailer
Version	v3.22.0~cdb0ab7
Built at	4. 4. 2023, 17:05
```

### What happened?

https://biohack.ds-wizard.org

Clicking "Export" from the right item menu (three dots) does not do anything while should export KM.
If I open KM and click "Export" there (top right corner) export happens.

By the way, I think export and import icons are swapped :) Usually, export is arrow out from a box (see attached screenshot) while in DSW export is arrow in.
<img width="226" alt="Screenshot 2023-04-13 at 10 34 27" src="https://user-images.githubusercontent.com/108409595/231702746-c163b041-609c-4a34-aa3c-275982807c4b.png">
<img width="709" alt="Screenshot 2023-04-13 at 10 32 59" src="https://user-images.githubusercontent.com/108409595/231702750-3cad776a-1099-48dc-b358-ff12a3c99148.png">

**Comment by janslifka** [comment]
This issue was fixed in 3.23.
