### ISSUE TITLE
broken link on dashboard

### ISSUE THREAD

**Issue by erlefloch** [ds-wizard/ds-wizard#279]
### What web browser is used when the issue appears?

Firefox

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [X] Using DSW managed by someone else (specify in text)
- [ ] Using DSW that I manage

### What parts of DSW are affected?

- [X] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
v3.23.0
```

### What happened?

broken link on the dashboard of the elixir-converge instance (https://converge.ds-wizard.org/dashboard): 
section "Import Document Template", the link "[DSW TDK](https://guide.ds-wizard.org/miscellaneous/development/template-development)" (https://guide.ds-wizard.org/miscellaneous/development/template-development) is invalid (link visited on 2023-05-15).

**Comment by janslifka** [comment]
Thanks for reporting the issue. I moved this into our [JIRA](https://ds-wizard.atlassian.net/browse/DSW-1997), and it will be resolved in the next version.
