### ISSUE TITLE
I'm not sure why login is no longer working for the demo side?

### ISSUE THREAD

**Issue by AdrienneCanino** [ds-wizard/ds-wizard#283]
### What web browser is used when the issue appears?

Chrome

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [X] Using DSW managed by someone else (specify in text)
- [ ] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [X] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [X] Users and Authentication

### Version

```plain text
https://registry.ds-wizard.org/login
```

### What happened?

A bug happened!
I'm trying to login and the screen is just blank.

**Comment by vknaisl** [comment]
Hello Adrienne,

Not sure where you want to log in. You mention a **demo** instance in the title. Nevertheless, then, you talk about **DSW Registry**)[1]. Can you please be more specific about where you want to log in?

Regards,
Vojtech

[1] https://registry.ds-wizard.org/login
