### ISSUE TITLE
KM/Plans sharing with GitHub (publish + load)

### ISSUE THREAD

**Issue by MarekSuchanek** [ds-wizard/ds-wizard#31]
Users could have an option to publish their knowledge models (data stewards) and plans (all users, filled-in questionnaire or also generated reports) and then also to load them = sharing and reusing.

## Advantages

* Outsourcing management and "social" functionality
  * Issues and communication
  * Related documentation (storage)
  * Releases, history, [DOI](https://guides.github.com/activities/citable-code/)
* Opening and being visible also on GitHub
* Simple sharing of knowledge models and plans ("repository")

## Disadvantages

* Other service where users need account
* Possible Vendor lock (allow others "share" extensions: [OSF](https://osf.io), [Google Drive](https://www.google.com/drive/), [Dropbox](https://www.dropbox.com/), etc.)
* Lost track of sharing the KM/Plans (unless somehow "connected")
* Every integration with external service brings risks and maintenance issues

## Related assumptions and conclusions

* We still should have some own (fairly FAIR) API for sharing the model and not force users to use other service
* Using other services will probably lead to some SSO via other services (for the "global" DSW) or at least linked accounts
* A documentation in human-readable format should be generad aside to the machine-actionable file(s) if it is not the same one

💡  **Any ideas, thoughts, or exprience are welcomed! This is just idea that needs to be elaborated in higher detail.**

**Comment by vknaisl** [comment]
# Today's update
- We will store events in repository. We will track changes in commits and upgrade as a pull requests
- We will publish knowledge model as a release in GitHub
- DSW will synchronise data (events, knowledge models,...) with GitHub

**Comment by MarekSuchanek** [comment]
We are using registry and will improve it in this way... Therefore, this issue is no longer relevant.
