### ISSUE TITLE
Connect to ELIXIR AAI

### ISSUE THREAD

**Issue by roper79** [ds-wizard/ds-wizard#36]

**Comment by MarekSuchanek** [comment]
The ELIXIR Authorization and Authentication Infrastructure (AAI) allows single sign-on to services across ELIXIR. It allows to login via organizational account (e.g. university or research centre account) or via LinkedIn, Google, and ORCID.

https://www.elixir-europe.org/services/compute/aai

- It still should be just one of the options. We probably want also people that are not from ELIXIR to be able to login and also if organization has own instance, they would need to setup AAI app connections... 
- In the future (maybe next IS?), it would be nice to have some _omniauth_ allowing simple adding new ways: classical registration, AAI, organizational LDAP, etc.

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-98
