### ISSUE TITLE
Semantic web and schema.org 

### ISSUE THREAD

**Issue by MarekSuchanek** [ds-wizard/ds-wizard#39]
Schema.org vocabulary defines some entities which will be used in DSW. Maybe we could get some inspiration there and/or use semantic markup.

- http://schema.org/Question
- http://schema.org/Answer
- http://schema.org/DataCatalog
- ...

**Comment by perglr** [comment]
We need to analyze this with respect to client-server architecture: now we render the UI on the client, but this will need server-side rendering. Maybe some dual solution? Like https://www.npmjs.com/package/spider-detector

**Comment by MarekSuchanek** [comment]
Yeah, of course... this is more like far-future idea, just to have it somewhere "captured". 

It is true that this might be an interesting solution - interactive browsing thru the questions for humans and static pages (even could be simplified just-views) for bots, spiders, and other creatures 😄

**Comment by perglr** [comment]
https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html

**Comment by MarekSuchanek** [comment]
This also relates to integration with [TeSS](https://tess.elixir-europe.org/about#howtoadd)

**Comment by MarekSuchanek** [comment]
# Proposal (WIP)

- KM/Plan:
- Chapter: 
- Question: http://schema.org/Question
- Answer: http://schema.org/Answer (for options in Planner, for all in HTML DSP)
- Expert: http://schema.org/Person and http://schema.org/Organization
- Book ref: https://bib.schema.org/Chapter (problem: just from-to pages, not numbering X.Y.Z)
- URL ref: 


## Comments:

- It should affect DS Planner and HTML DS Plan, no need to do it in KM Editor...
- There will be (probably) per-question pages (see https://github.com/DataStewardshipWizard/dsw-common/issues/1)

**Comment by MarekSuchanek** [comment]
Now in #146
